### ISSUE TITLE
[question] Heartbeat during message (messages) processing

### ISSUE THREAD

**Issue by n-n1ks** [karafka/karafka#1020]
Hello!
I have a question about heartbeat during message (messages) processing.

Use case:
- karafka 1.14.13;
- session timeout 9000 ms;
- heartbeat interval 3000 ms.
If message processing takes 10000 ms – a consumer will be kicked, offset won't be committed, and an infinity recursion can happen.

Is it expected behavior that a consumer doesn't send a heartbeat during message processing?

I am looking forward to your answer and thanks a lot!

**Comment by mensfeld** [comment]
Hey,

First of all thank you for using Karafka. Please keep in mind `1.4` EOLs in 6 months: https://karafka.io/docs/Versions-Lifecycle-and-EOL/

What you are looking for does not exist in 1.4. You need to trigger a manual heartbeat: 

https://github.com/karafka/karafka/blob/1.4/lib/karafka/base_consumer.rb#L15

> Is it expected behavior that a consumer doesn't send a heartbeat during message processing?

In 1.4 yes. In 2.0 no.

This feature is shipped out of the box with 2.0. There is no heartbeat needed and the only limitation is on max poll interval but even this can be bypassed with long running jobs: https://karafka.io/docs/Pro-Long-Running-Jobs/

**Comment by n-n1ks** [comment]
@mensfeld thanks a lot for your answer!
