### ISSUE TITLE
Consider using separate subscription group by default for Long Running Jobs

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#1027]

**Comment by whithajess** [comment]
@mensfeld If it helps after reading https://karafka.io/docs/Pro-Long-Running-Jobs/#using-long-running-jobs-with-regular-jobs my head also went straight to the fact that even if it's unlikely for a `regular job` to hit this in the case you have `long running jobs` separated adequately that it would be worth setting `subscription_group` just in case.

**Comment by mensfeld** [comment]
Yeah, that's why it's scheduled for 2.1 and will probably become the default.

**Comment by mensfeld** [comment]
Ok, after getting some sample use-cases from pro customers I am not going to do that by default. I've seen either good usage within the same subscription group or usage within separate consumer groups. Due to that, I don't want to introduce another "magical" remapping layer anymore.
