### ISSUE TITLE
Improve instrumentation API to expose committed/uncommitted message

### ISSUE THREAD

**Issue by NotGrm** [karafka/karafka#1113]
We use Bugsnag to track errors in our application, and we have defined a `BugsnagListener` for Karafka that uses instrumentation API and `#on_error_occurred` hook to do so.

To improve our reports we would like to include some data about the Kafka event that caused an error to be raised during the consumer processing. This is not easily doable with the current API, on Slack @mensfeld mentioned that it is possible to combine `event[:caller].coordinator.seek_offset` and `event[:caller].messages` to do so.

For the `#on_error_occured` hook I think it could be great to have a direct pointer to the event that was not successfully processed. Having something like `event[:current_message]` accessible sound great to me to return the message pointed by seek_offset.

But I don't know if this information could be useful for other instrumentation hooks

**Comment by mensfeld** [comment]
> I don't know if this information could be useful for other instrumentation hooks

I don't think so.

We can expose `last_committed_offset` which for non batch related stuff could be used to get the correct one.  The notion of "current offset" is rather blury for anyone doing batch operations ;)

**Comment by mensfeld** [comment]
Or better: lets expose the `seek_offset` which would indicate the offset of the broken message in linear processing. Ha!

**Comment by mensfeld** [comment]
@NotGrm would it be enough to expose the `seek_offset` and add docs on how to calculate the message out of it? I do not want to expose anything like `current_message` because for any type of window/batch operations there is no "current message".

**Comment by NotGrm** [comment]
@mensfeld that would be great 👍 

No problem  to not expose too much because there is multiple way to consume messages (in batches vs one by one). 

What do you think to also to also add a method to retrieve a message using its offset? Your answer on Slack works perfectly but it may be a bit hard to guess.

**Comment by mensfeld** [comment]
This method would be specific to a per message consumption with manual offset management where you mark per message. I will make a proper description in the docs though.
