### ISSUE TITLE
Rails auto detection loads karafka files too soon

### ISSUE THREAD

**Issue by AleksanderSzyszka** [karafka/karafka#1126]
## Is your feature request related to a problem? Please describe.

Karafka 2.0 has [rails auto-detection](https://github.com/karafka/karafka/blob/78ea23f7044b81b7e0c74bb02ad3d2e5a5fa1b7c/lib/karafka/railtie.rb#L19) and it is loaded early, so some components may be not available yet e.g. when `ApplicationConsumer` inherits from `BaseConsumer` that is provided by the separate gem that needs initializer.

Moreover, despite the same code base, some processes (`rails s`, `rails db:migrate`, `sidekiq s`) do not need to know about karafka and there is no need to load it.

The problem is presented in the PR with an example app: https://github.com/karafka/example-apps/pull/190

## Describe the solution you'd like

Do not use rails auto-detection. Allow to load railties by hand (`require karafka/railtie`), whenever and wherever the user wants.

## Describe alternatives you've considered

1) https://github.com/karafka/karafka/pull/1102 - this PR would solve the issue (railtie can be loaded manually), however that requires setting a flag for processes that shouldn't know about existing of karafka, which may cause issues.
2) Empty karafka bootfile. Having file structure like this:
```
+-- karafka_root_dir
|   +-- karafka.rb     # default bootfile (empty file)
|   +-- karafka_app.rb # real bootfile with Karafka::App definition and other stuff
|   +-- ...
```
It is possible to postpone the definition of karafka app and do it manually whenever & wherever the user wants (`karafka_app.rb` could be loaded for example in some initializer).

```ruby
# karafka_app.rb

class KarafkaApp < Karafka::App
  setup do |config|
    config.client_id = 'my_application'
    ...
  end
end

# config/initializers/karafka_init.rb

require 'karafka_root_dir/karafka_app'
```
Still not a perfect solution, because e.g. karafka gem is still loaded.

## Summary

Solution 2) it is a bit tricky, but it solves the problem and allows us to be more flexible.
So in general need to change karafka behavior. PR opened to show problems and potential solutions for others.

**Comment by mensfeld** [comment]
Closing as I also added this solution here: https://karafka.io/docs/FAQ/#can-i-use-karafka-with-ruby-on-rails-as-a-part-of-an-internal-gem
