### ISSUE TITLE
Run particular partitions per process 

### ISSUE THREAD

**Issue by Azdaroth** [karafka/karafka#1230]
## Is your feature request related to a problem? Please describe.

We already can be selective about which topics to process per process (https://karafka.io/docs/CLI/#running-particular-topics-per-process), which can help optimise resources' utilisation and speed of processing for the topics where the throughput is significantly higher. However, the same thing can happen within the particular topic where some partitions have way more messages.

## Describe the solution you'd like

Running particular partitions per process, just like it's possible for topics: https://karafka.io/docs/CLI/#running-particular-topics-per-process

**Comment by mensfeld** [comment]
@Azdaroth as far as I remember you established it is not possible with librdkafka as it is, right?

**Comment by Azdaroth** [comment]
@mensfeld True, the limitation is on librdkafka.
