### ISSUE TITLE
Plans for New Relic integration (similar to existing DataDog/StatsD)

### ISSUE THREAD

**Issue by jdanielian** [karafka/karafka#1238]
Curious if there are formal plans to create a New Relic instrumentation integration? I might be able to help out, but wanted to open this up to see if this was already on the roadmap, or if you would want this contribution? Our system uses New Relic, so getting something baked in to this gem to provide further instrumentation would be pretty cool for us. Thanks for your hard work - this has been a fantastic tool!

**Comment by mensfeld** [comment]
Hey, so far, no plans mainly because I do not use it. On top of that with the Web-UI, there will be less of a need. I would be of course happy to accept the PR :)

**Comment by mensfeld** [comment]
@jdanielian whenever you have time we can coop on this one.

**Comment by mensfeld** [comment]
@jdanielian I am going to close this one due to lack of activity. If anyone that uses newrelic is interested, please ping me and we can reopen.
