### ISSUE TITLE
Suggestion: Explain in readme why so many dependencies...

### ISSUE THREAD

**Issue by mustmodify** [karafka/karafka#1260]
I'm new to Kafka. I installed your gem -- looks great, thank you for your work.

```
jw@logopolis:/projects/client/project$ git diff Gemfile.lock | wc -l
166
```

🤔 😟 

I hate the idea of adding _that much stuff_ to a monolith... or any project... would be nice to understand why that's necessary and how much space isn't going to use in production.

If you give me some direction I'll create the documentation and send a PR.

**Comment by mensfeld** [comment]
That is impossible. Karafka has three direct dependencies. What karafka version are we talking about?

**Comment by mensfeld** [comment]
Karafka adds following gems to a rails project (I removed duplicates):

```
+    karafka (2.0.24)
+      thor (>= 0.20)
+      concurrent-ruby (>= 1.1)
+    rdkafka (0.12.0)
+      ffi (~> 1.15)
+      mini_portile2 (~> 2.6)
+      rake (> 12)
+    waterdrop (2.4.8)
+      karafka-core (>= 2.0.8, < 3.0.0)
+      zeitwerk (~> 2.3)
```

ref https://rubygems.org/gems/karafka/versions/2.0.24/dependencies
