### ISSUE TITLE
Monitor caller_label not working with super on inheritance

### ISSUE THREAD

**Issue by kwestein** [karafka/karafka#128]
👋 

The base Monitor class defines the [caller_label method](https://github.com/karafka/karafka/blob/master/lib/karafka/monitor.rb#L73) as
````
index = self.class.ancestors.index(Karafka::Monitor) + 1
caller_locations(index, 2)[1].label
````

I am wondering why the choice was made to have the method return ````caller_locations(index, 2)[1].label````? As an example, when monitor.notice is called from within a block, these values are returned:
````
caller_locations(index, 2)[0].label = 'notice'
caller_locations(index, 2)[1].label = `block in notice_signal'
````

In the ReadMe, the [example monitor with new relic support](https://github.com/karafka/karafka#example-monitor-with-newrelic-support) calls method by name based on the string value returned by caller_label. Given that the defined method would be called  ````notice```` not ever ````block in notice signal````, should this method not be returning caller_locations(index, 2)[0].label? I overrode it to do so in the app monitor we are using in our app and it works perfectly.

Let me know if I am missing something and it behaves this way intentionally. Otherwise I am happy to make the change. @mensfeld 

cc: @kevinhughes27

**Comment by mensfeld** [comment]
Hello @kwestein  :-) thank you for your interest in Karafka. This is a really interesting question. I will investigate that and get back to you max on Monday it that's not an asap

**Comment by mensfeld** [comment]
Btw you can always ask questions and get support faster on our gitter account: https://gitter.im/karafka/karafka

**Comment by mensfeld** [comment]
@kwestein  @kevinhughes27  could you please provide me with your monitor? To investigate it further I will have to have your monitor on which I could play. Caller label gets tricky when it comes down to the inheritance so. having yours and seeing how you use it would be a big help for me.

**Comment by kwestein** [comment]
This is what we currently have:

````
# frozen_string_literal: true
module Karafka
  class AppMonitor < Karafka::Monitor
    def notice(caller_class, options = {})
      super
      return unless respond_to?(caller_label, true)
      send(caller_label, options)
    end

    def notice_error(caller_class, e)
      super
    end

    private

    def caller_label
      index = self.class.ancestors.index(Karafka::Monitor) + 1
      caller_locations(index, 2)[0].label
    end

    def consume(params)
      content = JSON.parse(params[:content])
      logger.info("#{params[:controller]} received kafka event: #{content}")
      record_count params[:topic], content.try(:[], "event_name"), __method__
    end

    def perform_async(params)
      record_count params[:topic], params[:event_name], __method__
    end

    def perform(params)
      record_count params[:topic], params[:event_name], __method__
    end

    def record_count(topic, event_name, method)
      key = metric_key(topic, method)
      StatsD.increment(key, tags: ["event_name:#{event_name}"])
    end

    def metric_key(topic, action)
      "Karafka.#{topic}.#{action}"
    end
  end
end
````

**Comment by mensfeld** [comment]
Good afternoon @kwestein , @kevinhughes27. I hope you had a great weekend. I've analysed the problem and it is a bit more sophisticated that I've initially anticipated.

First of all, thank you for providing me with your monitor - it was a huge help for me! Indeed with your example the ```#caller_label``` should return the 0 element. ```caller_locations``` is really tricky to use and you've found a corner case that I didn't cover with specs. Generally speaking we have three cases for monitor:

- default monitor
- custom monitor that inherits from the default one
- custom monitor AND super execution on ```caller_label``` executing method

The tricky part is that ```#caller_locations``` works differently dependent on that and what I've assumed is that it would work exactly the same way in all the cases. I've pushed a fix for that with specs.

Here's an example that I hope will explain to you all the details of this problem:

```ruby
class BaseTracker
  def notice
    caller_label
  end

  private

  def caller_label
    index = self.class.ancestors.index(BaseTracker) + 1
    is_super = caller_locations(1, 2)[0].label == caller_locations(1, 2)[1].label

    scope = is_super ? 1 : nil
    scope ||= index > 1 ? 0 : 1

    p caller_locations(index, 2)[scope].label
  end
end

class InheritedTracker < BaseTracker
  def notice
    super # Here's 1 more chaining in the super scope
    caller_label
  end
end


class CallerSource
  def this_should_be_printed
    BaseTracker.new.notice
    InheritedTracker.new.notice
  end
end

CallerSource.new.this_should_be_printed
```

You can just copy paste it into irb.

**Comment by kwestein** [comment]
Thank you for the quick fix and the detailed explanation!

**Comment by mensfeld** [comment]
@kwestein  you are welcome. I will close this issue once @agwozdowski  merges fix into the master.
