### ISSUE TITLE
running karafka console results in NameError with Rails

### ISSUE THREAD

**Issue by carlost** [karafka/karafka#1280]
## Expected behavior

Running `bundle exec karafka console` should open up an irb like REPL.

## Actual behavior

Running `bundle exec karafka console` results in:

```
<path>/karafka-console-test/karafka.rb:3:in `<top (required)>': uninitialized constant Karafka (NameError)

class KarafkaApp < Karafka::App
                   ^^^^^^^
	from <path>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.2/lib/irb/init.rb:403:in `require'
	from <path>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.2/lib/irb/init.rb:403:in `block in load_modules'
	from <path>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.2/lib/irb/init.rb:401:in `each'
```

Meanwhile, running `bundle exec karafka server` works just fine.

## Steps to reproduce the problem

Run the following:
- rails new karafka-console-test
- cd karafka-console-test
- bundle add karafka --version ">= 2.0.28"
- bundle install
- bundle exec karafka install

## Your setup details

Created a new rails v7.0.4.2 project

```
Karafka version: 2.0.28
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
Rdkafka version: 0.12.0
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Application client id: example_app
Boot file: <path>/karafka-console-test/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
Does `bundle exec rails console` work? Karafka detects Rails and uses proper initializer setup via railtie in that case.

**Comment by mensfeld** [comment]
Ok, I can confirm the error and that rails console works. I actually never thought about making karafka console run with rails because you can use rails console but this def. should not end up with an error.

Please use rails console for now and I will figure out a re-alias for `karafka c` to `rails c` with rails.

**Comment by mensfeld** [comment]
As a bypass if you want (but will double require stuff outside of karafka console) add this to your  `karafka.rb` at the top:

```ruby
require 'karafka'
require_relative 'config/environment.rb'
```
