### ISSUE TITLE
Bundle install failure due to librdkafka SHA mismatch

### ISSUE THREAD

**Issue by jordanfbrown** [karafka/karafka#1290]
## Expected behavior

`bundle install` should install the gem

## Actual behavior

`bundle install` raises an error while installing C extensions

Stack trace:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jordan/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rdkafka-0.12.0/ext
/Users/jordan/.rbenv/versions/3.1.2/bin/ruby -I/Users/jordan/.rbenv/versions/3.1.2/lib/ruby/3.1.0 -rrubygems /Users/jordan/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake
RUBYARCHDIR\=/Users/jordan/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/extensions/arm64-darwin-21/3.1.0/rdkafka-0.12.0 RUBYLIBDIR\=/Users/jordan/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/extensions/arm64-darwin-21/3.1.0/rdkafka-0.12.0
Downloading v1.9.0 (  0%) 
Downloading v1.9.0 (  0%) 
Downloading v1.9.0 (  0%) 
Downloading v1.9.0 (  1%) 
Downloading v1.9.0 (  1%) 
Downloading v1.9.0 (  1%) 
Downloading v1.9.0 (  1%) 
Downloading v1.9.0 (  2%) 
Downloading v1.9.0 (  2%) 
Downloading v1.9.0 (  2%) 
Downloading v1.9.0 (  3%) 
Downloading v1.9.0 (  3%) 
Downloading v1.9.0 (  3%) 
Downloading v1.9.0 (  3%) 
Downloading v1.9.0 (  4%) 
Downloading v1.9.0 (  4%) 
Downloading v1.9.0 (  4%) 
Downloading v1.9.0 (  5%) 
Downloading v1.9.0 (  5%) 
Downloading v1.9.0 (  5%) 
Downloading v1.9.0 (  5%) 
Downloading v1.9.0 (  6%) 
Downloading v1.9.0 (  6%) 
Downloading v1.9.0 (  6%) 
Downloading v1.9.0 (  6%) 
Downloading v1.9.0 (  7%) 
Downloading v1.9.0 (  7%) 
Downloading v1.9.0 (  7%) 
Downloading v1.9.0 (  8%) 
Downloading v1.9.0 (  8%) 
Downloading v1.9.0 (  8%) 
Downloading v1.9.0 (  8%) 
Downloading v1.9.0 (  9%) 
Downloading v1.9.0 (  9%) 
Downloading v1.9.0 (  9%) 
Downloading v1.9.0 ( 10%) 
Downloading v1.9.0 ( 10%) 
Downloading v1.9.0 ( 10%) 
Downloading v1.9.0 ( 10%) 
Downloading v1.9.0 ( 11%) 
Downloading v1.9.0 ( 11%) 
Downloading v1.9.0 ( 11%) 
Downloading v1.9.0 ( 11%) 
Downloading v1.9.0 ( 12%) 
Downloading v1.9.0 ( 12%) 
Downloading v1.9.0 ( 12%) 
Downloading v1.9.0 ( 13%) 
Downloading v1.9.0 ( 13%) 
Downloading v1.9.0 ( 13%) 
Downloading v1.9.0 ( 13%) 
Downloading v1.9.0 ( 15%) 
Downloading v1.9.0 ( 18%) 
Downloading v1.9.0 ( 22%) 
Downloading v1.9.0 ( 25%) 
Downloading v1.9.0 ( 28%) 
Downloading v1.9.0 ( 32%) 
Downloading v1.9.0 ( 36%) 
Downloading v1.9.0 ( 38%) 
Downloading v1.9.0 ( 41%) 
Downloading v1.9.0 ( 45%) 
Downloading v1.9.0 ( 48%) 
Downloading v1.9.0 ( 52%) 
Downloading v1.9.0 ( 55%) 
Downloading v1.9.0 ( 58%) 
Downloading v1.9.0 ( 61%) 
Downloading v1.9.0 ( 65%) 
Downloading v1.9.0 ( 68%) 
Downloading v1.9.0 ( 71%) 
Downloading v1.9.0 ( 75%) 
Downloading v1.9.0 ( 78%) 
Downloading v1.9.0 ( 81%) 
Downloading v1.9.0 ( 85%) 
Downloading v1.9.0 ( 88%) 
Downloading v1.9.0 ( 91%) 
Downloading v1.9.0 ( 95%) 
Downloading v1.9.0 ( 98%) 
Downloading v1.9.0 (100%) 
rake aborted!
Downloaded file 'ports/archives/v1.9.0' has wrong hash: expected: 59b6088b69ca6cf278c3f9de5cd6b7f3fd604212cd1c59870bc531c54147e889 is: 82a0d4b4f79c15410f0f6147179588578ee78011fbab3e327c42234df735a702

Tasks: TOP => default
(See full trace by running task with --trace)
```

## Steps to reproduce the problem

1. Add `karafka` to your `Gemfile`
2. Run `bundle install`

## Your setup details

I'm using the latest version of Karafka. Relevant gems from `Gemfile.lock`:

```
karafka (2.0.29)
  karafka-core (>= 2.0.9, < 3.0.0)
  thor (>= 0.20)
  waterdrop (>= 2.4.10, < 3.0.0)
  zeitwerk (~> 2.3)
karafka-core (2.0.9)
  concurrent-ruby (>= 1.1)
  karafka-rdkafka (>= 0.12)
karafka-rdkafka (0.12.0)
  ffi (~> 1.15)
  mini_portile2 (~> 2.6)
  rake (> 12)
```

I did a bit of digging and located the issue.

1. librdkafka is downloaded here by MiniPortile: https://github.com/karafka/karafka-rdkafka/blob/main/ext/Rakefile#L19-L22
2. It's expecting SHA `59b6088b69ca6cf278c3f9de5cd6b7f3fd604212cd1c59870bc531c54147e889` for version 1.9.0: https://github.com/karafka/karafka-rdkafka/blob/v0.12.0/lib/rdkafka/version.rb#L3-L4
3. It downloads https://codeload.github.com/edenhill/librdkafka/tar.gz/v1.9.0, which has the wrong SHA

```
❯ curl https://codeload.github.com/edenhill/librdkafka/tar.gz/v1.9.0 | shasum -a 256
82a0d4b4f79c15410f0f6147179588578ee78011fbab3e327c42234df735a702  -
```

**Comment by jordanfbrown** [comment]
It looks like this is an issue with librdkafka - just found this issue in that project: https://github.com/confluentinc/librdkafka/issues/4167

**Comment by ziggythehamster** [comment]
As pointed out on [ruby.social](https://ruby.social/@george/109780954833581338) by @georgeclaghorn, this appears to be [a change that GitHub is (was?) doing](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/).

I am currently making a change in a fork of rdkafka-ruby to use a locally-provided .tar.gz file, but as I need rdkafka 0.11.1, this is not that useful to you.

**Comment by ziggythehamster** [comment]
I've published .gem files for rdkafka 0.12.0 and rdkafka 0.11.1 to https://github.com/orgs/art19/packages/rubygems/package/rdkafka which bundle the librdkafka tar.gz file .. use at your own risk :).

I've also added a `.1` to the end to distinguish the versions, and in the case of rdkafka 0.12.0, I updated it to use librdkafka 1.9.2 instead of 1.9.0 because 1.9.0 has a nasty vulnerability and because I couldn't find a suitable .tar.gz that matches a known good SHA256 for 1.9.0 but could for 1.9.2.

**Comment by jordanfbrown** [comment]
Looks like the Github change that led to this issue has been reverted and I'm now able to install native extensions. Closing this issue. Thanks @ziggythehamster for the additional information!

**Comment by mensfeld** [comment]
It may be worth bundling the sources in the package itself to prevent this from happening next time.
