### ISSUE TITLE
Not able to run rspec without bundle exec

### ISSUE THREAD

**Issue by vishaltps** [karafka/karafka#1306]
## Expected behavior

I am using the [chruby](https://github.com/postmodern/chruby) as a ruby version manager.  My other teammates who are using `rvm` or `rbenv` are not facing this issue. However, people who are using either `chruby` or [`asdf`](https://asdf-vm.com/) are facing this issue. Rspec commands should run with bundle exec.

## Actual behavior

rspec command is not working without the bundle exec command, when I run any command with `rails` it is working fine. However, if I run `rspec` command it is giving below error

```
An error occurred while loading ./spec/models/order_spec.rb. - Did you mean?
                    rspec ./spec/models/buyer_spec.rb
                    rspec ./spec/models/merchant_spec.rb
                    rspec ./spec/models/invoices_spec.rb

Failure/Error: require File.expand_path('../config/environment', __dir__)

LoadError:
  cannot load such file -- /Users/vishalsadriya/.gem/ruby/3.1.1/gems/karafka-2.0.30/lib/karafka/active_job
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:176:in `block in actual_eager_load_dir'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/karafka-2.0.30/lib/karafka.rb:114:in `<top (required)>'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
# ./config/application.rb:22:in `<top (required)>'
# ./config/environment.rb:4:in `require_relative'
# ./config/environment.rb:4:in `<top (required)>'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
# ./spec/rails_helper.rb:24:in `<top (required)>'
# /Users/vishalsadriya/.gem/ruby/3.1.1/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
# ./spec/models/order_spec.rb:3:in `<top (required)>'
No examples found.

Top 0 slowest examples (0 seconds, 0.0% of total time):

Finished in 0.00004 seconds (files took 2.95 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

## Steps to reproduce the problem

Use chruby or asdf as your ruby version manager, Install `gem 'rspec-rails', '~> 6.0.1'`, and `gem 'karafka'` together to try to run rspec command.

## Your setup details

```
bundle exec karafka info
Initializing the background worker with 2 threads
[Sessions] Sessions won't be captured without a valid release

@@@                                             @@@@@  @@@
@@@                                            @@@     @@@
@@@  @@@    @@@@@@@@@   @@@ @@@   @@@@@@@@@  @@@@@@@@  @@@  @@@@   @@@@@@@@@
@@@@@@     @@@    @@@   @@@@@    @@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@@@@@    @@@    @@@   @@@     @@@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@  @@@@  @@@@@@@@@@   @@@      @@@@@@@@@@    @@@     @@@  @@@@   @@@@@@@@@@


Karafka version: 2.0.30
Ruby version: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
Rdkafka version: 0.12.0
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Application client id: <clientid>
Boot file: /Users/vishalsadriya/<path to app>/karafka.rb
Environment: development
License: LGPL-3.0
Shutting down background worker
Killing session flusher
```

p.s: 

I have tried to debug this issue in my local and found out the issue is in `gem_root` method in the `lib/karafaka.rb:54` file. This method tries to find the correct path where gem is installed. It is getting the correct path for rbenv and rvm version manager. However, in the chruby and asdf version manager, it is giving current directory result instead of gem directory location. I have tried another way to find the root location of the gem and got succeeded in both rvm and chruby version manager. Here is what i have tried, 
```
    # @return [String] root path of this gem
    def gem_root
      spec = Gem::Specification.find_by_name('karafka')
      spec.gem_dir
      Pathname.new(File.expand_path(spec.gem_dir, __dir__))
    end
```
I wanted to raise a PR request but then thought it would be appropriate if I raise the issue first.

**Comment by mensfeld** [comment]
Yup looks like a bug.

**Comment by vishaltps** [comment]
> Yup looks like a bug.

This was quick.. didn't expect though. should i raise PR for this?

**Comment by mensfeld** [comment]
> This was quick.. didn't expect though. should i raise PR for this?

Sure :) I still need to repro it better because `gem_root` has been used by me for a long time but we do want Karafka to work with asdf for sure!

On the other hand I need to check if karafka will work with asdf chruby with bundler - if so, it may not be worth looking into as you anyhow need (should?) have bundler installed and used, right?

**Comment by vishaltps** [comment]
> > This was quick.. didn't expect though. should i raise PR for this?
> 
> Sure :) I still need to repro it better because `gem_root` has been used by me for a long time but we do want Karafka to work with asdf for sure!
> 
> On the other hand I need to check if karafka will work with asdf chruby with bundler - if so, it may not be worth looking into as you anyhow need (should?) have bundler installed and used, right?

Yes, I am using bundler. it makes sense to first check with the bundler. Let me know if you require anything from my side. i am not raising PR at the moment.

**Comment by mensfeld** [comment]
Ok now I am confused.

> Not able to run rspec without bundle exec

> Yes, I am using bundler

Those two contradict each other. Can you clarify on that please?

**Comment by vishaltps** [comment]
I am using bundler in my terminal and when i try to run the rspec without bundle exec it is giving above error. If i run the rspec with bundle exec it is working fine.

**Comment by mensfeld** [comment]
Ok, so what is the problem actually? I thought it's not working at all but if it is working via bundle exec (which is recommended way) why not `bundle exec`?

**Comment by mensfeld** [comment]
> Ideally, rspec should work without bundle exec. it was working fine in our app until we installed the karafka gem.

Can you reference me to any documentation that would back up this claim? Don't get me wrong, I can look into that and potentially we can fix this but partial usage of bundler is not something I would convince optimal and could be a source of many problems. Bundler does not only install dependencies but also manages their correct loading. To me (but I may be wrong) it seems like an internal convention that is not actually correct. Especially since Bundler now is part of Ruby core.

**Comment by vishaltps** [comment]
> 

There is no such documentation available to claim. However, as dev, we all have this tendency to not use bundle exec before rspec and it is working unless you install karafka with a particular ruby version manager. Would be better if we fix it in the gem because not many devs prefer to go by an alias.

**Comment by mensfeld** [comment]
I'm not certain it can be called a bug anymore. Running project partially with and partially without bundler is not a good idea in my opinion (happy to discuss it if you can back it up). That said, Karafka is designed to work with bundler and as far as I understand ti works for chruby and asdf well when executed with bundler.

**Comment by mensfeld** [comment]
>  However, as dev, we all have this tendency to not use bundle exec before rspec

This is first time I've heard about it. 

> and it is working unless you install karafka with a particular ruby version manager

Luck. It works now, it may not in the future. It also potentially may introduce inconsistencies in the loading process because you attempt to run a certain functionality (rspec) bypassing the loading cycle of bundler. 

While I understand it causes inconvenience to you, I would not consider it as a bug, however if you create a PR I am willing to take a look at it :)
