### ISSUE TITLE
Topic name validation issue

### ISSUE THREAD

**Issue by sastromskis** [karafka/karafka#1325]
PR #1300 introduced an updated regex for topic naming validation which throws an error in case the topic name contains both dot and underscore. 

We are using Debezium MySQL CDC connector on confluent cloud, which by default creates topics having exactly the forbidden naming convention:

`server.database_name.table_name`

Would it be possible to make this validation optional?

**Comment by mensfeld** [comment]
> Would it be possible to make this validation optional?

Yes.

**Comment by sastromskis** [comment]
Thank you!

**Comment by mensfeld** [comment]
@nijikon @CandyFet My suggestion for this would be to validate potential collisions in the scope of Karafka routing: that is only failing if there are topics that would collide. For example:

`server.database_name.table_name` and `server.database.name.table_name` within the routing (any consumer groups). WDYT?

I think this would be less restrictive but in a context of Karafka would still ensure correctness. I don't think we should be that strict to limit overall scope of operations.

**Comment by mensfeld** [comment]
Ok others have same problem. Example: `xyz-web.development.data_flows.avro`

**Comment by mensfeld** [comment]
Merged. I will release it this week. Just need to finish one or two more things.

**Comment by sastromskis** [comment]
@mensfeld Thank you!

**Comment by mensfeld** [comment]
@sastromskis exactly. We want to promote good practices but sometimes you already have what you have ;) just set it to false and it won't cause you any problems anymore!
