### ISSUE TITLE
Easier validation extendability for Topics & associated Routes

### ISSUE THREAD

**Issue by Vadimvf** [karafka/karafka#1347]
## Is your feature request related to a problem? Please describe.

Having more freedom around topic validation and setup could allow for more extendability. The current routes pattern is great in that its simple and recognizable to folks coming from Rails or similar setups.
But the downside is the [block is being passed to instance_eval](https://www.rubydoc.info/gems/karafka/Karafka/Routing/Builder#draw-instance_method) => and evaluated in the routes builder. So it makes it difficult to make a custom topic method or extend the behavior. i.e we want added validations around topic names and their route setups, but don't want devs patching behavior in Karafka to do it.
**Examples**
1) You have rules around a topic string: 
  - Topics require a prefix, prefixes are checked against allowed values 
  - Rules like no underscores, allow (-, .) only to prevent collisions 
  - Topics must be from a predefined list. If you're using an external topic operator/manager for your cluster.
2) You have rules around a topic route/the topic itself 
  - “All topics of type X must have a DLQ of type Y”
  - You want to enforce a minimum partition count 

A simple case for the above, `topic “queue.user”` should work, `topic “queue_user”` should blow up. Ideally, you’d want to make your own wrapper like `validated_topic “queue.user” do`, but with the eval - you’d have to patch Karafka's Builder since defining it yourself doesn’t work with the instance_eval. Or do something like `topic TopicString.create!(‘queue.user’) do`, but that won’t cover any other behavior like DLQs.

## Describe the solution you'd like

1. Making topic routes/strings "contractable" or "validatable" in some way
2. Making Topic classes instead of referring to them as strings, since the idea of a topic is more complicated logically than what String provides.

### Solution 1 pseudo-code
**Rails-ish way**
```ruby
topic :example do
  consumer Consumer
  validates_with CustomValidator # Could receive a Karafka::Routing::Topic, functions like a rails model validator. 
end
# ----
class CustomValidator < BaseValidator # holds global rules for all topics
 # Can expand if needed for subset of topics e.g. user topics
  def validate(topic)
    errors.add(:name, "Starts with banned") if topic.name.start_with?('banned')
```

**With Contracts**
Where custom contract functions like the others: https://github.com/karafka/karafka/blob/master/lib/karafka/routing/features/dead_letter_queue/contract.rb
```ruby
topic :example do
  consumer Consumer
  with_contract CustomContract
end
```

### Solution 2 pseudo-code
**Not referencing topic names as strings or blocks**

This might have the most extensibility. Topics are no longer referred to with plain strings. Instead like consumers, you define Topic classes. The only requirement being that they have a `name`, who's string is used for creating routes and producting messages and a `config`.
 
```ruby 
class MyTopic < Karafka::ExtendableTopic
   # you're now free to extend as you please
  def name 
   'example'
  end

  def config 
    @config ||= Karafka::Topic::Config.new
  end
 
  # so the name could be dynamically prefixed (e.g. devs shared a lower env kafka cluster, to prevent events from going to each others servers their personal server gets a prefix added 
  def name
    base = 'example' 
    return base unless MyApp.env.dev_cloud?
    prefix(my_namespace, base)
  end

  # you can include custom validations etc
  include ActiveModel::Model
  validates :name, presence: true, length: {minimum: 2}
end 

# later on in karafka.rb

routes.draw do
  topic MyTopic # done, uses the config from MyTopic. Similar to how `resources :users` is a valid Rails route
  
  consumer_group :group_name2 do 
    topic MyTopic  do 
      consumer SimpleConsumer # overrides MyTopic.config.consumer
      dead_letter_queue(topic: 'dead_messages') # overrides MyTopic.config.dead_letter_queue
    end
  end
end

# because its no longer a string, you can extend to using it with producers/in place of strings: 
module Karafka
  class ExtendableTopic
    include Produceable # just delegates to Karafka.producer
  end
 end
 
# so instead of Karafka.producer.produce_async(topic: 'example', payload: '{}')
MyTopic.produce_async(payload: '{}')

# at the very least you prevent string typos, but in the case of the prefix example you now don't need to worry about it
MyTopic.produce_async(payload: '{}')
# => Produces message to 'my-topic' in production
# => Produces message to 'my-uniq-ns.my-topic' in a dev env that shares a kafka cluster with multiple people testing events

topic MyTopic do 
  consumer SimpleConsumer
# => Defines route for 'my-topic' in production
# => Defines route for  'my-uniq-ns.my-topic' in a dev env that shares a kafka cluster with multiple people testing events


ImportantTopic.produce_safely_async(payload: invalid_payload) # OR
ImportantTopic.produce_async(payload: invalid_payload) 
# => ImportantTopic:::InvalidPayloadError ! 
# Because we're able to extend the class, in this case where there's no schema & more concern with payload validity than performance, you can just extend the topic class todo:

def produce_async(payload:, key:)
  validate_payload! payload
  super
end
```

## Describe alternatives you've considered

For now we've stuck to plain Rails patterns - e.g. we don't reference topics as strings directly and do something like the following: 
```ruby
class Topic
    class Name
      ALLOWED_CHARS = /\A[a-z0-9.-]+\Z/i.freeze

      include ActiveModel::Model


      attr_reader :value, :type, :resource

      validates :value, presence: true, format: { with: ALLOWED_CHARS }
      validates :type, presence: true, inclusion: {in: Prefix.all}
      validates :resource, presence: true, length: {minimum: 2}
```

```ruby 
# karafka.rb 
topic Topic.create!(‘queue.user’) do # this will now throw at boot for invalid topics
```

## Additional context

- Karafka Slack thread here: https://karafka-io.slack.com/archives/C01T8MNJLRZ/p1677684169595309

**Comment by mensfeld** [comment]
Amazing report!

My suggestion would be to slightly re-organize the `Karafka::Routing::Topic`.

I don't want to extract topics as separate entities mostly because this would break up the clean (at least in my opinion) abstraction where you have `karafka.rb` + consumers and things just work™. 

We now inject per-feature topic validations by pretending the the routing builder more or less like so:

```ruby
consumer_group.topics.each do |topic|
  scope::Contract.new.validate!(topic.to_h)
end
```

we could instead introduce a `#contracts` st (Set.new) with all the default contracts and allow anyone to just add additional contracts by accessing the `#contracts` object. This would also allow for contracts removal or changes of default contracts (see the case of topic regexp validation).

The DSL would then be like so:

```ruby
topic :example do
  consumer Consumer
  # this would have defaults already loaded
  contracts << CustomContract
end
```

Such an approach would also simplify the features management because their contracts would be injected the same way (just automatically) when feature is registered.

A separate thing is answering a question whether we could have a "model like topic abstraction" that could be automatically re-written:

```ruby
# (notice no block)
topic MyTopic.new
topic EventsTopic.new
```

but this would not require anything beyond automatic remap of values. This would not have to be provided by the framework itself.

WDYT?

**Comment by Vadimvf** [comment]
> I don't want to extract topics as separate entities mostly because this would break up the clean (at least in my opinion) abstraction where you have karafka.rb + consumers and things just work™.

I think that's fair, it also puts more work on Karafka and you to maintain what a "topic" should be. Looking back, the emphasis should be on extendibility/maintainability in the end and managing how people interact with topics would be a large lift. 

> we could instead introduce a #contracts st (Set.new) with all the default contracts and allow anyone to just add additional contracts by accessing the #contracts object.

I think this would pretty much cover the use cases I covered. If anyone wanted to extend it/formalize it more on their end, then they could implement a MyApp::Topic class on their own and have it work with their workflow. 

```ruby
topic MyApp::Topic.name do
  consumer Consumer
  contracts << MyApp::Topic.contract
end
```
And if you wanted the namespacing etc then you can make your own Produceable Topic:
```ruby
    module Produceable
      delegate :buffer, to: :producer, private: true
      delegate :flush_async, to: :producer, private: true
      delegate :flush_sync, to: :producer, private: true
      delegate :produce_async, to: :producer, private: true
      delegate :produce_sync, to: :producer, private: true
      delegate :produce_many_async, to: :producer, private: true
      delegate :produce_many_sync, to: :producer, private: true

      # @return [WaterDrop::Producer]
      def producer
        Karafka.producer
      end
    end
    
# so now, this works
topic MyApp::Topic.name do
  consumer Consumer
  contracts << MyApp::Topic.contract
end

# and you can do this: 
MyApp::Topic.produce_async(...)
```

> A separate thing is answering a question whether we could have a "model like topic abstraction" that could be automatically re-written

I think in this case it almost becomes too similar to managing topics as their own entity, and I agree it probably shouldn't be provided by Karafka. If you get clever you can always do something like:

```ruby 
class ExampleTopic
  def self.name
    :example
  end

  def self.to_proc
    proc do
      consumer SimpleConsumer
    end
  end

# In karafka.rb
routes.draw do
  topic(ExampleTopic.name, &ExampleTopic)
end
```

**Comment by mensfeld** [comment]
> I think in this case it almost becomes too similar to managing topics as their own entity, and I agree it probably shouldn't be provided by Karafka. If you get clever you can always do something like:

Exactly. You can pretty much wrap the karafka DSL yourself to convert it into "objects" representation.

**Comment by mensfeld** [comment]
@Vadimvf I wonder here i we should create a generic validation layer applicable for each topic or allow to define validations per topic?

Imho generic would be good because we could easily add requirements like "never use dots, always use at least two partitions" etc. WDYT?

**Comment by Vadimvf** [comment]
Would contracts stay classes like: https://github.com/karafka/karafka/blob/master/lib/karafka/routing/features/dead_letter_queue/contract.rb

If so the generic validation layer could be supplied by having a ApplicationContract and follow a similar pattern to ApplicationConsumer. 
 
```ruby
class ApplicationTopicContract < Karafka::Topic::Contract::Base 
  required never_use_two_dots { |topic| topic.name.match(/((\.){2,})/).nil? }
end

class LogTopicContract < ApplicationTopicContract
  required log_prefix { |topic| topic.name.start_with? 'log' }
end
```

**Comment by mensfeld** [comment]
Firstly, I'd like to express my genuine gratitude for detailing your feature request.

After careful consideration, I cannot proceed with this specific feature request at the moment. The primary reason for this decision is that the suggested changes would require significant reorganization of the current API. Our design principles have been built upon a foundation that aims to strike a balance between extensibility and simplicity. Integrating the suggested feature would veer considerably away from the path I've set.

I'm on the verge of introducing patterns feature that will further extend the routing system. This will likely render the validation methods you've suggested more prone to edge cases and unforeseen complications.

However, please know that this decision keeps your proposal's value high. While I might not be integrating the proposed changes into the core of Karafka, I'm more than willing to assist you in crafting a custom implementation atop the existing routing engine. I'm always keen to support and empower Karafka users to craft solutions that meet their needs. I'd happily provide guidance or answer questions as you navigate this process.
