### ISSUE TITLE
NonMatchingRouteError exception raised

### ISSUE THREAD

**Issue by jpcaissy** [karafka/karafka#135]
We encountered a `NonMatchingRouteError` exception in production. Code says to contact you @mensfeld 

Not sure what I can provide you with to help debug. It happened only twice randomly

**Comment by mensfeld** [comment]
Hello @jpcaissy. Thank you for contacting us. You found a great non-predicted by us case (probably)! Which is awesome as now we can cover that. 

Did it happen in Karafka directly or in Sidekiq Karafka's process?

This can happen in two cases:

1. Karafka received a message on a topic and this message internally contains a different topic name (highly impossible :D) 
2. Karafka received a message, processed it, enqueued a job to Sidekiq and then... you guys stopped Karafka's Sidekiq and changed routing so the enqueued jobs topic no longer matches any controllers.

I'm almost sure that this is what happened to you guys. We will have to update docs and cover this with a different error name in case of this happening in Sidekiq. If it happens in Karafka's main process during message receiving, that you will have to provide me with more details. 

Meanwhile please verify if the flow that I assume happened is valid. :)

**Comment by jpcaissy** [comment]
Confirmed, this happened in a job enqueued on Sidekiq. That specific job had failed and is being retried.  The routing did change in the meantime, but the topic name didn't change at all.

I'll try to reproduce locally.

**Comment by mensfeld** [comment]
@jpcaissy this can happen only when the topic name that is saved as one of (first to be exact) the params does not match any routes from the routes. I will keep this issue open so once I'm back from a holiday (1 week from tomorrow) I will remember to make this error more descriptive.

**Comment by jpcaissy** [comment]
Ok, found the culprit, problem was on our side. The job had failed and was being retried by Sidekiq. Between the time it failed and when it was retried, we moved kafka queues to a new one. Since this was being retried from the old queue, it didn't have karafka loaded at all, so couldn't find the route.

**Comment by mensfeld** [comment]
It's always great to know that it's not my fault :)

As I said, if you don't mind I will keep this issue opened until I make the error more descriptive.

**Comment by mensfeld** [comment]
@jpcaissy  how would you like to have it fixed? With a more comprehensive error or with a some sort of fallback mechanism?

**Comment by mensfeld** [comment]
@jpcaissy  ping ;)

**Comment by jpcaissy** [comment]
I guess a better error messaging. As you mentioned, it shouldn't happen unless you have changed topic before, and haven't restarted your sidekiq workers.

**Comment by mensfeld** [comment]
Thanks. I'll take care of it soon.

**Comment by mensfeld** [comment]
Ok - descs are changed for this error in errors.rb
