### ISSUE TITLE
Bump ruby-kafka

### ISSUE THREAD

**Issue by jpcaissy** [karafka/karafka#136]
Any reasons why ruby-kafka is locked to v0.3.15?

It seems that v0.3.16 was released a couple of months ago. It fixes a problem we have with SSL: https://github.com/zendesk/ruby-kafka/commit/36fb1a2de0cf59d6c9d20b9b65411274c35f43fe

I did bump it locally, and all tests pass except an unrelated change to dry-configurable.

@mensfeld

**Comment by mensfeld** [comment]
@jpcaissy no particular reason. I didn't want to keep open dependencies that's all. Will do that this week.

**Comment by jpcaissy** [comment]
Thanks!
