### ISSUE TITLE
Question about multiple app consumers for the same topic.

### ISSUE THREAD

**Issue by krapans** [karafka/karafka#1375]
Hi, I have a question about following scenario. Let's say we have a event called `ProjectUpdated` from external system.

Systems: A, B.
A emits event `ProjectUpdated`.
B needs to consume this message.

How you would create two separate consumers in same app B. Lets say I want to have consumers `ProjectCacheUpdater` that listens on `ProjectUpdated` topic and `ProjectImageResizer` that listens on the same `ProjectUpdated` topic.

Ideally those are two separate consumers which don't know about each other. Is there possibility to archive something like that with karafka?

**Comment by mensfeld** [comment]
Yes.

You can either use a consumer wrapper (one consumer delegating the job to wherever) - but this will be a subject to collective error handling, etc and that's my guess why you want it to be done separately ;)

or you can use consumer groups for this:

```ruby
consumer_group :cache_management do
  topic :events do
    consumer ProjectsCacheUpdated
  end
end

consumer_group :resizer do
  topic :events do
    consumer ProjectImageResizer
  end
end
```

**Comment by mensfeld** [comment]
In the above multi-group scenario, management of offsets, lags, error handling, etc is isolated. They consume the same topic but know nothing about each other.

**Comment by mensfeld** [comment]
Ah and on top of that, such a setup allows to run those in parallel.

**Comment by krapans** [comment]
> You can either use a consumer wrapper (one consumer delegating the job to wherever)

This was my initial thought but decided to check in :) 


> but this will be a subject to collective error handling, etc and that's my guess why you want it to be done separately ;)

Eeexactly, that would be main concern having one consumer that delegates actions to other classes or background jobs.


> or you can use consumer groups for this:

Perfect. this is what I was looking for. Thank you so much for quick response 🙇

**Comment by mensfeld** [comment]
@krapans feel free to join our slack channel - there are a lot of ppl there that can answer many questions: https://slack.karafka.io/

**Comment by krapans** [comment]
Perfect 👍 , will definitely do that.

**Comment by mensfeld** [comment]
ref: https://karafka.io/docs/FAQ/#can-i-consume-the-same-topic-independently-using-two-consumers-within-the-same-application
