### ISSUE TITLE
You should be able to have no worker class defined if inline_mode is being used everywhere

### ISSUE THREAD

**Issue by kwestein** [karafka/karafka#138]
When using `inline_mode = true` everywhere, you should not need to define a worker since everything would be performing inline. Yet I am still seeing `Karafka::Errors::BaseWorkerDescentantMissing` when I try to remove our worker definition. 

@mensfeld cc: @kevinhughes27 @SebastianSzturo

**Comment by mensfeld** [comment]
- Should not validate base worker descendants at all
- Should not try to build anything at all
