### ISSUE TITLE
Karafka presentation needs an update

### ISSUE THREAD

**Issue by carlos-contreras** [karafka/karafka#139]
Specifically this part: http://mensfeld.github.io/karafka-framework-introduction/#/22,

Since now the `thow(:abort)` needs to be used instead of returning `false` within the callbacks.

**Comment by mensfeld** [comment]
@carlos-contreras  thank you for pointing that out. I've updated this one and few other slides. In the future please always refer to the master docs as they are the most up 2 date thing :) 

Have a nice Sunday!
