### ISSUE TITLE
karafka tries to connect to localhost even boostrap.servers is set to different host

### ISSUE THREAD

**Issue by dimitriwoei** [karafka/karafka#1416]
karafka tries to connect to localhost even boostrap.servers is set to different host

--------

## Expected behavior

I would expect karafka to connect to my non localhost server

## Actual behavior

rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 6 identical error(s) suppressed)
rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)

## Steps to reproduce the problem

bundle add karafka

> Installing karafka-rdkafka 0.12.1 with native extensions
> Fetching karafka-core 2.0.12
> Installing karafka-core 2.0.12
> Fetching waterdrop 2.5.1
> Installing waterdrop 2.5.1
> Fetching karafka 2.0.39
> Installing karafka 2.0.39

bundle exec karafka install

> Installing Karafka framework...
> Ruby on Rails detected...
> 
> Created karafka.rb
> Created app/consumers/application_consumer.rb
> Created app/consumers/example_consumer.rb
> 
> Installation completed. Have fun!

Then I updated karafka.rb

```
class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = { 'bootstrap.servers': 'my.non.localhost.server:9092' }
    config.client_id = 'my_application'
    # Recreate consumers with each batch. This will allow Rails code reload to work in the
    # development mode. Otherwise Karafka process would not be aware of code changes
    config.consumer_persistence = !Rails.env.development?
  end

  # Comment out this part if you are not using instrumentation and/or you are not
  # interested in logging events for certain environments. Since instrumentation
  # notifications add extra boilerplate, if you want to achieve max performance,
  # listen to only what you really need for given environment.
  # Karafka.monitor.subscribe(Karafka::Instrumentation::LoggerListener.new)
  # Karafka.monitor.subscribe(Karafka::Instrumentation::ProctitleListener.new)

  # This logger prints the producer development info using the Karafka logger.
  # It is similar to the consumer logger listener but producer oriented.
  # Karafka.producer.monitor.subscribe(
  #   WaterDrop::Instrumentation::LoggerListener.new(Karafka.logger)
  # )

  routes.draw do
    # Uncomment this if you use Karafka with ActiveJob
    # You need to define the topic per each queue name you use
    # active_job_topic :default
    topic :"my-topic" do
      # Uncomment this if you want Karafka to manage your topics configuration
      # Managing topics configuration via routing will allow you to ensure config consistency
      # across multiple environments
      #
      # config(partitions: 2, 'cleanup.policy': 'compact')
      consumer MyConsumer
    end
  end
end

```

## Your setup details

Please provide kafka version and the output of `karafka info` or `bundle exec karafka info` if using Bundler.

Here's an example:

```
$ [bundle exec] karafka info
Karafka version: 2.0.39
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
Rdkafka version: 0.12.1
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Application client id: worqmanager
Boot file: /app/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
are you sure your non-local server is not resolved to localhost? Can you create a reproduction using one of the example apps? https://github.com/karafka/example-apps

**Comment by dimitriwoei** [comment]
I cloned example-apps and ran v2.0-rails, you can find my updated karafka.rb here:

https://github.com/dimitriwoei/karafka-test

> example-apps/v2.0-rails$ bundle exec karafka server
> 
> @@@                                             @@@@@  @@@
> @@@                                            @@@     @@@
> @@@  @@@    @@@@@@@@@   @@@ @@@   @@@@@@@@@  @@@@@@@@  @@@  @@@@   @@@@@@@@@
> @@@@@@     @@@    @@@   @@@@@    @@@    @@@    @@@     @@@@@@@    @@@    @@@
> @@@@@@@    @@@    @@@   @@@     @@@@    @@@    @@@     @@@@@@@    @@@    @@@
> @@@  @@@@  @@@@@@@@@@   @@@      @@@@@@@@@@    @@@     @@@  @@@@   @@@@@@@@@@
> 
> 
> Upgrade to Karafka Pro for more features and support: https://karafka.io
> rdkafka: [thrd:localhost:9092/1]: localhost:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
> rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
> rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
> rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
> rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
> rdkafka: [thrd:localhost:9092/1]: localhost:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)

**Comment by mensfeld** [comment]
```
rdkafka: [thrd:dev.neodb.q-services.eu:9092/bootstrap]: Hinted cache of 1/1 topic(s) being queried
rdkafka: [thrd:dev.neodb.q-services.eu:9092/bootstrap]: Requesting metadata for 1/1 topics: connected
rdkafka: [thrd:dev.neodb.q-services.eu:9092/bootstrap]: dev.neodb.q-services.eu:9092/bootstrap: Request metadata for 1 topic(s): connected
rdkafka: [thrd:dev.neodb.q-services.eu:9092/bootstrap]: dev.neodb.q-services.eu:9092/bootstrap: Sent MetadataRequest (v4, 36 bytes @ 0, CorrId 2)
rdkafka: [thrd:dev.neodb.q-services.eu:9092/bootstrap]: dev.neodb.q-services.eu:9092/bootstrap: Received MetadataResponse (v4, 100 bytes, CorrId 2, rtt 44.19ms)
rdkafka: [thrd:main]: dev.neodb.q-services.eu:9092/bootstrap: ===== Received metadata (for 1 requested topics): connected =====
rdkafka: [thrd:main]: dev.neodb.q-services.eu:9092/bootstrap: ClusterId: e4LP4sJeSNK1NPr6IdGFvg, ControllerId: 1
rdkafka: [thrd:main]: dev.neodb.q-services.eu:9092/bootstrap: 1 brokers, 1 topics
rdkafka: [thrd:main]: dev.neodb.q-services.eu:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 1
```

its your cluster misconfiguration and not Karafka

**Comment by mensfeld** [comment]
it points during metadata discovery to a localhost:

```
redacted-host:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 1
```

**Comment by dimitriwoei** [comment]
Thank you very much! I'm new to kafka, and just followed some "getting started" instructions. I would not have found the problem without you. Trying to reconfigure it now.

**Comment by mensfeld** [comment]
@dimitriwoei no worries. We all started at some point ;) don't hesitate to reach out if you cannot solve it.
