### ISSUE TITLE
Timestamp based lookup in the Iterator API

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#1429]

**Comment by federicomoretti** [comment]
I believe we would need this merged first: https://github.com/appsignal/rdkafka-ruby/pull/229

**Comment by mensfeld** [comment]
@federicomoretti yes, I plan to merge it after 0.13.0 stable and probably 1.0.0. I don't want to add any extra functionalities to 0.13.0 since I've spent enough time on fighting with this release.
