### ISSUE TITLE
Deattach Karafka from Sidekiq by extracting Sidekiq backend

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#147]
A lot of people use Karafka without Sidekiq in an inline mode. We could remove sidekiq as a dependency and allow users to use (or even implement) any async adapter as long as they should follow a simple API. We would create one for Sidekiq ofc. That way people could use Sidekiq Pro easier or Resque or anything they want.

**Comment by mach-kernel** [comment]
I can take this @mensfeld 👍 

Sidekiq, Resque, and DelayedJob seem to be popular for this kind of thing. Can you think of any others?

**Comment by mensfeld** [comment]
@mach-kernel feel free. However I think that this one requires some planning. I will try to describe my initial idea and some things we need to consider in 2 days. Then we can process this further. Are you ok with that?

**Comment by mach-kernel** [comment]
@mensfeld sure thing!

**Comment by mensfeld** [comment]
Note: it is still a WIP:

1. We need to consider an inline mode just an adapter as well
2. We need to consider, the serialization (interchanger problem)
3. New engine needs to support current batch mode and future batch mode (mass batch mode for batch processing)
4. What about workers? Now they are tightly couples with Sidekiq
5. Can we differ adapters in between topics allowing to use different (one per topic?). I think so, as then we could have both async adapters and sync adapter and replace the inline mode with it.
6. What about the CLI - the worker job won't longer work. Should we drop that totally or should we implement worker per adapter? (I would be in favour of dropping - everyone can run sidekiq ;) ) . If we drop, we need to update readme.

**Comment by mensfeld** [comment]
@mach-kernel I think that we could do this step by step:
We could:
- remove worker-glass from dependencies (it's a really simple logic) and just maintain it as an additional feature for sidekiq adapter (adapter specific tool)
- remove karafka worker at all (this is also sidekiq specific) - it is not hooked up to the karafka-capistrano and should be fairly easy to migrate (as it is just alias for bundle exec sidekiq whatever)

**Comment by mach-kernel** [comment]
From `worker-glass`:

- #perform (do work)
- #after_failure (ensure clean state)

I think it might not be a bad idea to make a base class that does a `#before_perform` step with an array of actions. It'd be a bit cleaner than chaining super (e.g. multiple prepend) calls and maybe ordering them could be helpful? At the very least it would match the `before_enqueue` pattern found in controllers. Standardizing this would be a good first step I think, to do along with removing `worker-glass`.

Then, we could make that adapter layer under it that understands how to delegate the work to each different library. What are your thoughts?

**Comment by mensfeld** [comment]
@mach-kernel yeah but ```before_perform``` does not realize the after_failure logic of the worker glass. I totally agree that we need a before_perform that could throw as well (same way as before_enqueue).

> Then, we could make that adapter layer under it that understands how to delegate the work to each different library. What are your thoughts?

I think we should stop caring about that. We should provide Kafka specific solution with multiple background processing adapters (for now inline and sidekiq) and leave the sidekiq (or any other lib reentrancy) to programmers and their business logic.

**Comment by mensfeld** [comment]
Quick update to #162 - I thought about it and I think that ```before_process``` is a bad idea. Why?

1. Does not bring any additional functionalities (in Rails you can early break the flow and do something else (like redirect etc) or prepare some stuff which might save you from doing the logic but here you can just implement it in perform.
2. There's no longer the ```after_failure``` as it was a sidekiq specific option and we're removing that #163 
3. ```before_enqueue``` brings value as it can save you from scheduling stuff and doing heavy things if you don't need those, so it adds additional feature.

**Comment by mach-kernel** [comment]
I generally agree, but out of box re-entrancy is something that would be of real value to anyone that doesn't think of it in the first place or does so as an afterthought. IMO, I would use best practices as reference of how [Akka does it](http://doc.akka.io/docs/akka/snapshot/scala/fault-tolerance.html). Give it a look over and let me know what you think.
