### ISSUE TITLE
Rails.logger.tagged not tagging messages in staging environment

### ISSUE THREAD

**Issue by sarvesh-sankaranarayanan** [karafka/karafka#1477]
I'm trying to log the SQL queries & other logs that are printed during the processing of a message in a consumer class.
Below is an outline of my code

```
class ApplicationConsumer < Karafka::BaseConsumer

   def consume
     Rails.logger.tagged(UUID) do
        check_account
         ......
    end
end
```

Here are the logs from my development.log
```
[031740f0e324] Consume job for TicketConsumer on ticket-v2/1 started
[c40bfb1e05c111ee94f9f67154fdf30a]   Account Load (0.5ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`product_account_id` = 1 LIMIT 1
[c40bfb1e05c111ee94f9f67154fdf30a]   ↳ app/consumers/application_consumer.rb:35:in `check_account'
[c4703e6205c111ee94f9f67154fdf30a]   Account Load (1.2ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`product_account_id` = 1LIMIT 1
[c4703e6205c111ee94f9f67154fdf30a]   ↳ app/consumers/application_consumer.rb:35:in `check_account'
[c51be8ca05c111ee94f9f67154fdf30a]   Account Load (16.5ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`product_account_id` = 1 LIMIT 1
[031740f0e324] Consume job for TicketConsumer on ticket-v2/1 finished in 233.11300000548363ms
```

Here are the logs in staging environment
```
[eb4927a0b493] Polled 10 messages in 999.5926310122013ms
[5885b3e349d5] Consume job for TicketConsumer on ticket-v2/3 started
[b919652cd181] Consume job for TicketConsumer on ticket-v2/4 started
[576e3a097afb] Consume job for TicketConsumer on ticket-v2/1 started
[3c96b43cc76b] Consume job for TicketConsumer on ticket-v2/2 started
[a7d13961e10e] Consume job for TicketConsumer on ticket-v2/0 started
[b919652cd181] Consume job for TicketConsumer on ticket-v2/4 finished in 6.308680027723312ms
```

Why is the behaviour different?
What am I missing here?

**Comment by mensfeld** [comment]
https://github.com/karafka/karafka/blob/master/lib/karafka/railtie.rb#L35

Karafka by default prints this only for development. You can just set it up in similar way for staging based on the code after `next`

**Comment by mensfeld** [comment]
basically this:

```ruby
        logger = ActiveSupport::Logger.new($stdout)
        # Inherit the logger level from Rails, otherwise would always run with the debug level
        logger.level = Rails.logger.level

        Rails.logger.extend(
          ActiveSupport::Logger.broadcast(
            logger
          )
        )
```

**Comment by sarvesh-sankaranarayanan** [comment]
Thanks for the quick support. Will try this out.

**Comment by mensfeld** [comment]
@sarvesh-sankaranarayanan please close this if that works so I can expand the FAQ :)

**Comment by mensfeld** [comment]
@sarvesh-sankaranarayanan can you prepare a repro using https://github.com/karafka/example-apps v2.1-rails app? I need to be able to see it myself

**Comment by sarvesh-sankaranarayanan** [comment]
@mensfeld I don't need to log to STDOUT, I need to log only to the file. I'll prepare an example app as requested.

**Comment by mensfeld** [comment]
@sarvesh-sankaranarayanan that is ok. Please prepare a PR with the illustration of your problem and then I can look at it and solve it :) thanks!

**Comment by sarvesh-sankaranarayanan** [comment]
@mensfeld It seems I don't have write access to the example-apps repo for me to simulate the issue. Can you please provide me with the right access?

**Comment by sarvesh-sankaranarayanan** [comment]
@mensfeld Please find the PR that reproduces the issue.

https://github.com/karafka/example-apps/pull/289
