### ISSUE TITLE
Web-UI does not work on staging environment

### ISSUE THREAD

**Issue by GuilhermeMaia91** [karafka/karafka#1479]
Hi.

I configured the karafka web ui in the staging environment and all the necessary topics are being created, when I access the status page I notice that I am asked to execute the command `bundle exec karafka-web install` and when I run, i get the error below

--------

## Expected behavior

This is behavior in development environment
![image](https://github.com/karafka/karafka/assets/8620918/52a29402-21f4-46fe-9299-78e37ee5ed5e)

## Actual behavior

This is behavior in staging environment
![image](https://github.com/karafka/karafka/assets/8620918/01d496db-0901-4ff5-9792-00c8214efe2f)

But when I try to run the command in the terminal I get this error
![image](https://github.com/karafka/karafka/assets/8620918/325cd760-fa9e-407e-b5d8-48ad4d37650f)

## Steps to reproduce the problem

I just installed the gem as the doc says and uploaded it to my server 

## Your setup details

```
2023-06-13 15:00:47.420777 I [7689:3880] Rails --
@@@                                             @@@@@  @@@
@@@                                            @@@     @@@
@@@  @@@    @@@@@@@@@   @@@ @@@   @@@@@@@@@  @@@@@@@@  @@@  @@@@   @@@@@@@@@
@@@@@@     @@@    @@@   @@@@@    @@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@@@@@    @@@    @@@   @@@     @@@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@  @@@@  @@@@@@@@@@   @@@      @@@@@@@@@@    @@@     @@@  @@@@   @@@@@@@@@@


2023-06-13 15:00:47.421011 I [7689:3880] Rails -- Karafka version: 2.1.3
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
Rdkafka version: 0.12.3
Consumer groups count: 3
Subscription groups count: 3
Workers count: 2
Application client id: test_karafka
Boot file: /var/www/app/current/karafka.rb
Environment: staging
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
You may want to run karafka with following setting:

```ruby
class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = {
      # other settings...
      debug: 'all'
    }
  end
end
```

debug all will print extensive info about the information flow

**Comment by mensfeld** [comment]
@GuilhermeMaia91 debug all won't fix the issue but it may highlight the nature of the problem. Likely it's either extreme latency or permission problems. I would bet on the latter since the cluster seams reachable. Can you share some insights on your cluster and infra around staging?

**Comment by mensfeld** [comment]
potentially ref: https://github.com/karafka/karafka/issues/1454 (that's a note for myself - please ignore ;) )

**Comment by GuilhermeMaia91** [comment]
> ```ruby
> debug: 'all'
> ```

I don't have access to the cluster settings, because it's managed by the sec team, I'll analyze the settings with the team... But the strange thing is that I can produce and consume messages, only the web-ui that doesn't go online

**Comment by mensfeld** [comment]
@GuilhermeMaia91 well based on your logs it does not seem so. WaterDrop is unable to produce to one of the web topics. If the setup is managed by a sec team, then again: probably you don't have correct settings to be able to write to some of the topics. My assumption is, that you have explicit access to the topics you work with but you were not granted permissions to operate on the web topics.

Here you can find the web UI topics default names and settings: https://karafka.io/docs/Web-UI-Getting-Started/ (browse to the table)
