### ISSUE TITLE
Move docs to wiki

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#149]
Dosc are growing. We should make a wiki out of them.

**Comment by nowakov** [comment]
@mensfeld hey, I've moved docs to wiki. Check if that's what you're looking for and then I'll proceed with README update.

**Comment by mensfeld** [comment]
Woooooooooooooooo! Thank you sooooooooo much! :1st_place_medal:  that was astonishing :)

**Comment by mensfeld** [comment]
@nowakov - you can totally update the README ofc! :heart:

**Comment by mensfeld** [comment]
@nowakov are you still willing to update the README? :)

**Comment by mensfeld** [comment]
@nowakov - done. Thank you so much for your work and moving everything to wiki. That was awesome!
