### ISSUE TITLE
Add support for start_from_beginning on a per topic basis

### ISSUE THREAD

**Issue by kwestein** [karafka/karafka#150]
This would be very helpful for us so that we can replay events on one topic at a time in the case when we make mistakes processing the events. Having to replay every topic from the beginning would consume way too many of our resources.

@mensfeld

**Comment by mensfeld** [comment]
Related to #151

**Comment by mensfeld** [comment]
@kwestein  calling you just in case calling in update don't work.

**Comment by kwestein** [comment]
This doesn't actually work @mensfeld. I am getting test failures with `NoMethodError: undefined method `start_from_beginning' for []:Karafka::Routing::Builder` when attempting to set it per topic

**Comment by mensfeld** [comment]
@kwestein  ok. I will look at it soon.

**Comment by mensfeld** [comment]
@kwestein  could you tell me what version of karafka do you use?

**Comment by mensfeld** [comment]
@kwestein fixed. Sorry for the delay.

**Comment by Papipo** [comment]
Can this be done dynamically? Let's say that I have a consumer that projects the topic as a local read model and I need to update it from scratch after a deploy, but not always.

Thanks

**Comment by mensfeld** [comment]
It can. You need to move the offset to 0 upon start.

**Comment by mensfeld** [comment]
https://github.com/karafka/karafka/wiki/Callbacks#before_fetch_loop :)

**Comment by Papipo** [comment]
I was reading this https://github.com/karafka/karafka/wiki/FAQ#can-i-use-seek-to-start-processing-topics-partition-from-a-certain-point

Thanks!

**Comment by mensfeld** [comment]
Any time :) good luck!
