### ISSUE TITLE
Throttle or pause consumer if redis memory is filling up

### ISSUE THREAD

**Issue by lardcanoe** [karafka/karafka#152]
The Kafka client has support for pausing/resuming consumers, so hopefully this isn't too hard.

We had an issue when one set of workers died, so kafka filled up with many hours worth of jobs, and when we finally got things working again karafka dumped the entire backlog of jobs into redis which threw an OutOfMemory (OOM) error and things didn't go well from there.

So it would be great to enabled throttling. If redis mem is over some threshold then pause.

We need this functionality, so I am happy to do the coding if you can give guidance and thoughts.

Thanks!

**Comment by mensfeld** [comment]
Thank you for reporting that. I'm well aware of that issue. I will came up with an idea on how to implement that in 2-3 days and update this issue.

**Comment by lardcanoe** [comment]
In the meantime, we implemented a better strategy as well. Kafka payloads simply contain a pointer to the real payload in S3. This works really well, so not as much of a rush on this one anymore. The Sidekiq jobs download from S3 when they start.

**Comment by mensfeld** [comment]
@lardcanoe good to know however you're not the first guy to ping me about that issue. I will take care of it (but luckily we don't have to rush now).

**Comment by mensfeld** [comment]
Note for myself: because of #147  this needs to be a general throttler

**Comment by mensfeld** [comment]
@lardcanoe  still fancy to help? ;)

**Comment by mensfeld** [comment]
I'm moving it to 1.0 as it will be quite a big feature in terms of making sure that it works as expected. It could also be added with an option to generally pause consumers on some partitions in case of an error (idea).

**Comment by mensfeld** [comment]
I've already implemented pausing, so this should be fairly simple as long as we pass block for evaluation upon each messages batch receive so we can get control over consumers

**Comment by mensfeld** [comment]
@lardcanoe for now, if anything goes wrong withing kafka main server, it will back off for a proper time (configurable). I think, this should cover your case :-)
