### ISSUE TITLE
What does the batch mode actually do?

### ISSUE THREAD

**Issue by zhoplocal** [karafka/karafka#153]
Is it possible to consume messages in a batch of 1000 messages at a time? 

I've got a requirement where I want to buffer 1000 events using kafka and once the threshold reaches 1000 messages I should be able to consume the messages. 

Is this possible with karafka?

**Comment by mensfeld** [comment]
Hello @zhoplocal. Thank you for taking interest in Karafka.

Ruby-Kafka (the driver behind Karafka) provides batch message consuming that is based on the overall message size, not their amount. You probably want to implement a leaky bucket based on number of messages. This is indeed impossible in Karafka (and Ruby-Kafka).

Reference to how each_batch works: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L243

However, if you have a consistent data size, you could easily (more or less) estimate the size and then, when we resolve this: #154, you should be ready to go :)
