### ISSUE TITLE
RdkafkaError while trying to boot consumer app

### ISSUE THREAD

**Issue by romeufcrosa** [karafka/karafka#1563]
We are trying to migrate from ruby-kafka to karafka in our ruby Kafka consumer app, however we are facing an error everytime we try to start the app consuming from a topic that uses zstd, we've tried booting it from a different topic that uses no compression and it works fine.
We _believe_ we have all the dependencies installed and are unsure what the error means, we've tried searching for it and all recommendations point towards installing several libs that we have already installed, such as:
```
    libc6 \
    zlib1g-dev \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    librdkafka-dev \
```

However, we keep getting the same error
`<Rdkafka::RdkafkaError: Local: Not implemented (not_implemented)> of type: connection.listener.fetch_loop.error occurred!` and are at a loss on how to get this to work, so any help is much appreciated.

--------

## Expected behavior

The app should launch and start consuming from the Kafka topic/partition without any issues.

## Actual behavior

When the app launches the following errors are thrown:
```
<Rdkafka::RdkafkaError: Local: Not implemented (not_implemented)> of type: connection.listener.fetch_loop.error occurred!

<Rdkafka::RdkafkaError: Local: Not implemented (not_implemented)> of type: connection.client.poll.error occurred!

<Rdkafka::RdkafkaError: Local: Not implemented (not_implemented)> of type: connection.listener.fetch_loop.error occurred!
```

## Steps to reproduce the problem

-> Producer app is setup with `compression.type=zstd`.
-> Consumer app was implemented with the straightforward consumer example found in the [docs](https://karafka.io/docs/Consuming-messages/#consuming-messages).
-> Docker image of consumer app has `libzstd-dev` installed as well as `librdkafka-dev`
-> Started the app

## Your setup details

Karafka info
```
Karafka version: 2.1.7
Ruby version: ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-darwin22]
Rdkafka version: 0.13.2
Consumer groups count: 1
Subscription groups count: 1
Workers count: 40
Application client id: eintegrations
Boot file: ./bin/karafka.rb
Environment: staging
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
After you have installed missing deps did you recompile the karafka-rdkafka? Just installing missing deps is not enough if it was missing during the compilation of native extension.

**Comment by romeufcrosa** [comment]
> After you have installed missing deps did you recompile the karafka-rdkafka? Just installing missing deps is not enough if it was missing during the compilation of native extension.

Probably missed an important bit in my description, sorry for that.
We are installing karafka via bundle, so we added it in the Gemfile -> bundle install -> bundle exec karafka install

In this scenario I don't see why recompiling karafka-rdkafka should apply, since we are not compiling from source?
To that you might ask, "then why the dev libs?"... yeah we're just following suggestions.

**Comment by mensfeld** [comment]
> In this scenario I don't see why recompiling karafka-rdkafka should apply, since we are not compiling from source?

This is not how bundler works.

If your flow was as followed:
- add karafka
- run bundle install
- run bundle exec karafka install
- configure
- run karafka
- get the error
- install dev deps
- how it is going to work (hehe)

it is **not** going to work.

Karafka uses karafka-rdkafka which is compiled from the sources because karafka-rdkafka uses librdkafka compiled from the sources (2.2.0). Taking into consideration the above flow, bundler already cached the karafka-rdkafka and it will not  recompile it even if you remove karafka from the gemfile and add it and install again. This is how bundler cache works.

You need to remove ALL versions of karafka-rdkafka from your system (or at least the used one) by running (I think) `gem uninstall karafka-rdkafka`  and then bundle again.

Optionally I think there is a `--force` option to trigger recompilation but I will not give you 100% warranties on that.

> In this scenario I don't see why recompiling karafka-rdkafka should apply, since we are not compiling from source?

You are because I am ;)

**Comment by romeufcrosa** [comment]
> > In this scenario I don't see why recompiling karafka-rdkafka should apply, since we are not compiling from source?
> 
> This is not how bundler works.
> 
> If your flow was as followed:
> 
> * add karafka
> * run bundle install
> * run bundle exec karafka install
> * configure
> * run karafka
> * get the error
> * install dev deps
> * how it is going to work (hehe)
> 
> it is **not** going to work.
> 
> Karafka uses karafka-rdkafka which is compiled from the sources because karafka-rdkafka uses librdkafka compiled from the sources (2.2.0). Taking into consideration the above flow, bundler already cached the karafka-rdkafka and it will not recompile it even if you remove karafka from the gemfile and add it and install again. This is how bundler cache works.
> 
> You need to remove ALL versions of karafka-rdkafka from your system (or at least the used one) by running (I think) `gem uninstall karafka-rdkafka` and then bundle again.
> 
> Optionally I think there is a `--force` option to trigger recompilation but I will not give you 100% warranties on that.
> 
> > In this scenario I don't see why recompiling karafka-rdkafka should apply, since we are not compiling from source?
> 
> You are because I am ;)

Yes, that would not work.
We're doing it in a different order, however:
- Install overall container dependencies (including the ones listed)
- run bundle install
- run kafka

The bundle exec karafka install and configure steps are done locally, when we build the docker image those are already taken care of.

Even with this order, we were getting the error. Probably with this information my comment would have made more sense when I mentioned that recompiling from source was not relevant in this particular situation.
> You are because I am ;)
Oh, that's just great :) I just ❤️  that type of reasoning :)

Anyway, we figured the issue, was a fairly basic mistake, we were installing the dependencies on an intermediate stage of Docker instead of the actual run/final stage.

Thank you for your help, I'll close this.

**Comment by mensfeld** [comment]
@romeufcrosa glad you solved that. Would you mind helping me and reformatting this into a FAQ question and answer that I could include here: https://karafka.io/docs/FAQ/  - I try to document things for the benefit of the community and such a case with a solution would be a great addition :pray:
