### ISSUE TITLE
Clarification on setting :max_messages, default: 100

### ISSUE THREAD

**Issue by kasinathanveera** [karafka/karafka#1577]
is the config max_messages representing messages batch fetched from kafka **entirely** and then sent to kafka jobs scheduler to segregate accordingly based on concurrency as mentioned in the below image or is it the count on the messages of each individual partition which is used to process the message in application consumer
<img width="1525" alt="image" src="https://github.com/karafka/karafka/assets/109208889/47a3947d-8b9b-4bcb-bd36-ae32482cd9a0">

**Comment by kasinathanveera** [comment]
@mensfeld can you help me out here on the clarification

**Comment by mensfeld** [comment]
> entirely

What do you mean by saying "entirely"? Each message is independent and while their processing obeys some collective warranties in the moment of fetching they are independent. They are fetched in batches in a round-robin fashion governed by several librdkafka settings from Kafka but this setting governs not that but fetching them from internal C buffer. This image is not exact representation of the full process but aims to visualize how the operations work. There are few more layers there ;)

It is neither of those. It is max messages that are fetched in one go from the internal C buffer that usually is prefilled. If data is available (any) this is max that you will get. The messages there are fetched as said in a round-robin fashion. You get at most (max) 100 messages in one go that are then divided into separate batches according to their topic and partition and dispatched for execution. It may be 100 messages from one topic partition or 1 message from each of 100 partitions. Depends on other setting and particular situation in which your consumer groups are (lag).
