### ISSUE TITLE
SemanticLogger integration

### ISSUE THREAD

**Issue by paneq** [karafka/karafka#1585]
## Is your feature request related to a problem? Please describe.

Would you be interested in receiving a pull request with support for [semantic_logger](https://github.com/reidmorrison/semantic_logger) integration? There is already [logger_listener available](https://github.com/karafka/karafka/blob/master/lib/karafka/instrumentation/logger_listener.rb), however the outputted logs are not structured. Having structured logs allows for easy integration with ELK stack and easily finding logs related to certain Message Types etc.

## Describe the solution you'd like

We already have SemanticLogger integration implemented and I guess we could contribute it back to Karafka. Below is a small comparison of a implementations for a single method.

In Karafka with regular logger:

```
      # Prints info about the fact that a given job has finished
      #
      # @param event [Karafka::Core::Monitoring::Event] event details including payload
      def on_worker_processed(event)
        job = event[:job]
        time = event[:time]
        job_type = job.class.to_s.split('::').last
        consumer = job.executor.topic.consumer
        topic = job.executor.topic.name
        partition = job.executor.partition
        info <<~MSG.tr("\n", ' ').strip!
          [#{job.id}] #{job_type} job for #{consumer}
          on #{topic}/#{partition} finished in #{time}ms
        MSG
      end
```

vs using our codebase semantic logger:

```
    def on_worker_processed(event)
      job = event[:job]
      time = event[:time]
      job_type = job.class.to_s.split('::').last
      consumer = job.executor.topic.consumer
      topic = job.executor.topic.name
      partition = job.executor.partition

      info(
        'Job finished',
        job_id: job.id,
        job_type:,
        consumer:,
        topic:,
        partition:,
        time:
      )
    end
```

## Describe alternatives you've considered

* I am not sure if there is an alternative to having a dedicated class that could automatically work with regular logs as well as structured ones.
* I wonder if the existing `LoggerListener` should inherit from the proposed `StructuredLoggerListener`. Then the code of extract topic/partition and other attributes from `event` would be localized in `StructuredLoggerListener` and `LoggerListener` only responsibility would be to format the message based on the received attributes.

**Comment by paneq** [comment]
> We have versioning for semantic reporting that we could bump if anything changes 

Interesting idea. I like it, I just don't know how to make sure this would be bumped correctly. Meaning how anyone contributing/changing would not forget to bump it. Also do you imagine it just as a single integer or semver?

> We do not change in any way the current LoggerListener output.

Absolutely.

**Comment by paneq** [comment]
I have a question related to something that would go a bit out of scope of the existing implementation.

In https://karafka.io/docs/Consuming-messages/ we have this example:

```
class SingleMessageBaseConsumer < Karafka::BaseConsumer
  attr_reader :message

  def consume
    messages.each do |message|
      @message = message
      consume_one

      mark_as_consumed(message)
    end
  end
end

class Consumer < SingleMessageBaseConsumer
  def consume_one
    puts "I received following message: #{message.payload}"
  end
end
```

Processing messages in batches makes perfect sense in some use-cases (i.e. synchronizing data, streaming etc) but it's not trivial in case of: https://www.confluent.io/blog/put-several-event-types-kafka-topic/ so in case of using Kafka for domain events. In such case handlers are usually event type specific and messages need to be processed one by one.

Would you be OK with introducing additional api method looking like (details to be figured out):

```
def on_worker_message_processed(message)
end
```

which could be invoked by SingleMessageBaseConsumer like this `Karafka.monitor.instrument('worker.message_processed', message)` and which would log that a single msg was processed. Ideally with the ability to pass additional app-specific arguments.

If you believe that this is outside of scope of what should be built-in to karafka, then I understand. I would like to know your opinion before I start implementing so that I know how to split the codebase and what to put in karafka and what should stay in my company's internal tooling.

**Comment by mensfeld** [comment]
> Interesting idea. I like it, I just don't know how to make sure this would be bumped correctly. Meaning how anyone contributing/changing would not forget to bump it. 

Specs ;)

> Also do you imagine it just as a single integer or semver?

Semver. We could use x.y.z where x is for breaking, y is for compatible and z is for fixes (compatible)

> If you believe that this is outside of scope of what should be built-in to karafka, then I understand. 

Outside of the scope. We can provide docs how to utilize this and document examples but I do not want to introduce "entity processing" as first class citizen in Karafka.

**Comment by mensfeld** [comment]
@paneq I don't see any activity with this one so I will close it for now. Feel free to reopen with a PR or followup
