### ISSUE TITLE
Add support for AWS_MSK_IAM SASL mechanism to karafka

### ISSUE THREAD

**Issue by JulienDefrance** [karafka/karafka#1588]
## Is your feature request related to a problem? Please describe.

Add support for AWS_MSK_IAM SASL mechanism to karafka

## Describe the solution you'd like

AWS recently [introduced](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) a SASL mechanism for AWS_[MSK](https://aws.amazon.com/msk/)_IAM that allows Kafka clients to handle authentication and authorization with MSK clusters through [AWS IAM](https://aws.amazon.com/iam/).

## Describe alternatives you've considered

SASL/SCRAM with user/password authentication

**Comment by mensfeld** [comment]
Of course if there is an alternative way to offer it within the boundaries of librdkafka, happy to do it.
