### ISSUE TITLE
Karafka::Admin consumer group is not configurable nor well-documented

### ISSUE THREAD

**Issue by ziggythehamster** [karafka/karafka#1589]
## Is your feature request related to a problem? Please describe.

`Karafka::Admin` uses a default consumer group of `karafka_admin`, which is not well-documented and can't really be configured since lots of methods wrap the consumer and `.config` is private. If you are using restrictive ACLs, you need to know to allow access to the `karafka_admin` consumer group.

## Describe the solution you'd like

1. Document that this consumer group needs to be permitted (ideally, there's a page that goes over all of the ACL permissions needed and why)
2. Make the consumer group configurable in a way that all of the things that fetch a consumer from here inherit the group ID.

## Describe alternatives you've considered

`Karafka::Admin.config(:consumer, { "group.id" => "foo" })`

This does not work because many of the wrapping methods pass their own settings or `{}`, and this method is private anyways.

## Additional context

Not having this permitted via ACL results in the error `Rdkafka::RdkafkaError: Broker: Group authorization failed (group_authorization_failed)` at regular intervals, and it is not apparent why this is happening unless you look deep into the stack trace to see it originates from karafka/admin.rb.

**Comment by mensfeld** [comment]
Hey @ziggythehamster you are **absolutely** right!

I would propose a generic base for admin config in a similar fashion as we have the default Kafka cluster settings (plus its own details):

```ruby
class KarafkaApp < Karafka::App
  setup do |config|
    config.client_id = 'my_application'
    # librdkafka configuration options need to be set as symbol values
    config.kafka = {
      'bootstrap.servers': '127.0.0.1:9092'
    }
    
    # 
    config.admin.kafka = { 'group.id': 'whatever' }
  end
end
```

however I would def. merge the above into this:

```ruby
    CONFIG_DEFAULTS = {
      'group.id': 'karafka_admin',
      # We want to know when there is no more data not to end up with an endless loop
      'enable.partition.eof': true,
      'statistics.interval.ms': 0,
      # Fetch at most 5 MBs when using admin
      'fetch.message.max.bytes': 5 * 1_048_576,
      # Do not commit offset automatically, this prevents offset tracking for operations involving
      # a consumer instance
      'enable.auto.commit': false,
      # Make sure that topic metadata lookups do not create topics accidentally
      'allow.auto.create.topics': false
    }.freeze
```

So we would:

```ruby
Karafka::App.config.kafka.dup.merge(CONFIG_DEFAULTS).merge(Karafka::App.config.admin.kafka).merge!(settings)
```

this should allow for full customization but would also prevent from a scenario where user has to define ALL the settings again. Especially since many of the settings (presented above) are really specific to admin and should not be altered with.

I also **fully** agree that docs on that should be much better and explicit. This is going to be fixed and I am sorry for the confusion.

**Comment by mensfeld** [comment]
TODO:
- [ ] Introduce ability to configure admin as other components via config
- [ ] Update docs and reflect the need for the default CG name of admin
- [ ] Add this into FAQ as well
- [ ] Craft a new release with the updates

**Comment by ziggythehamster** [comment]
> This is going to be fixed and I am sorry for the confusion.

No problem at all! Once we realized this was the permissions issue, we pushed out an ACL change and it started working beautifully :). We did have to monkeypatch the web UI since there is an a bug that's fixed in the unreleased version with the breadcrumbs (`delete_prefix` vs `gsub`), and now as far as I can tell, we're up and processing nicely.

As far as the API is concerned for this - I'd be happy with it being configurable like you shared, but I'd also be happy with it just automatically applying the same logic as consumer group names - `"#{client_id}_karafka_admin"` for example. Then our `Prefixed` ACL rule would have applied no problem. The only other thing I could conceivably see myself setting is `compression.type=snappy` (IIRC librdkafka supports this out of the box but if I'm wrong assume I provided one supported out of the box ;)).

I also am a fan of the direction Flink started going, where the actual properties can be set if you want, but there are now specific methods/settings that are more explicit and can be statically validated if used incorrectly (e.g., setting up transactional producers but forgetting to configure one of the required properties). Here, that might be something like `config.compression_type = :snappy` and Karafka could check librdkafka to see if that's available, and you the end user don't need to care where that gets carried to later, but an exception could be thrown if librdkafka doesn't support that. Or you could make it take a list of compression types in preference order in addition to a single one. Stuff like that.

That said, I am probably in the minority in that I want every Karafka cluster we run to be separate with separate web UIs, but (potentially) share a Kafka, so that things can be isolated (application A cannot read data that application B is supposed to read, and the web UI for application A has no knowledge of the data with a different classification that application B reads... boring corporate stuff, I know). More normal people will probably be happy with all of the default consumer group names.

**Comment by mensfeld** [comment]
updated docs for the current state:

- https://karafka.io/docs/FAQ/#why-am-i-getting-broker-group-authorization-failed-group_authorization_failed-when-using-admin-api-or-the-web-ui
- https://karafka.io/docs/Topics-management-and-administration/#configuration
- https://karafka.io/docs/Web-UI-Getting-Started/#troubleshooting
