### ISSUE TITLE
Consume single message at given topic, partition and offset

### ISSUE THREAD

**Issue by jesseduffield** [karafka/karafka#1653]
## Is your feature request related to a problem? Please describe.

I'd like a way to obtain a message at a given topic/partition/offset. Alternatively I'd like a way to get a consumer to consume a single message at a given topic/partition/offset.

## Describe the solution you'd like

I'm thinking something like:

```ruby
MyConsumer.consume_message_at(topic: 'my-topic', partition: 1, offset: 2)
```

Or:

```ruby
message = Karafka.message_at(topic: 'my-topic', partition: 1, offset: 2)
# `process_message` is my own method defined on MyConsumer
MyConsumer.process_message(message)
```

**Comment by mensfeld** [comment]
There is such a way already and it supports both offset location as well as time based location:

ref: https://karafka.io/docs/Topics-management-and-administration/#reading-topic-messages

```ruby
topic = 'my_topic'
partition = 0
how_many = 1
first_offset = 50

message = Karafka::Admin.read_topic(topic, partition, how_many, first_offset).first
```

**Comment by mensfeld** [comment]
moving via consumer is also supported as karafka consumers support `#seek`.

Admin API understands the routing so deserialization works as expected.

**Comment by jesseduffield** [comment]
Thanks for the fast response! My bad for not reading the docs thoroughly

**Comment by mensfeld** [comment]
@jesseduffield who does :laughing: 

Karafka is a big ecosystem of gems, sometimes things slip.

P.S. If you enjoy my work, please don't forget to :star:  this repo. It helps me grow the community :pray: 

P.S2: Please note that when using admin with ACL, you need to setup proper access (documented).

P.S3: Please note, that admin API does NOT subscribe, hence you won't have logs about it's usage in Kafka as it does not run subscription and consumer group balance. This also means you can use it from anywhere.

**Comment by jesseduffield** [comment]
Starred, and noted :)
