### ISSUE TITLE
Params and route reorganization

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#166]
Due to dynamic character of controllers, we should have:

- access to route instance to be able to figure out stuff (instead of from params) on an instance level
- params should not contain route information

**Comment by mensfeld** [comment]
Once it is done we need to (in wiki):

- grep for any controller.something = stuff and update
- update https://github.com/karafka/karafka/wiki/Important-components and self.worker assignment

**Comment by mensfeld** [comment]
Ok I think I have a concept on that:

1. The current api (except the naming changes for options) can stay the same and will behave as followed: single route 1:1 with a single background thread
2. Higher level concept to allow of a multiple subscriptions per topic handling. Now (as in 0.5) we map 1:1 and it is good for most of the cases, but there are cases when we want to have a really small and slim system that handles multiple topics with a single consumer. In a case like that we could use following setup:

```ruby
  routes.draw do
    # This would handle both topics with a single consumer group
    consumer 'group-name' do
      batch_mode true
      start_from_beginning true
      group 'custom_group_name'

      topic :commit_builds_scheduled do
        controller CommitBuildsCreateController
      end

      topic :commit_builds_processed do
        controller CommitBuildsProcessedController
      end
    end

    # Those two would be equivalent
    topic :commit_builds_copied do
      controller CommitBuildsCopyController
    end

    consumer 'commit_builds_copied' do
      topic :commit_builds_copied do
        controller CommitBuildsCopyController
      end
    end
  end
```

Of course this will require a more complex validation engine for routes as there will be options that by default are set on the consumer level and some per topic, but in general I don't see a problem with that as we could just allow setting them on both levels and just picking this settings (if present) from the last topic description in a consumer or using failover to a consumer level and if non using defaults from the config.

@agwozdowski  @mach-kernel  @pavlo-vavruk what do you think?

**Comment by mach-kernel** [comment]
@mensfeld this looks good, why the second `group 'custom_group_name'` though? They could just name the consumer with that same string / less to keep track of unless I'm missing something?

**Comment by mensfeld** [comment]
@mach-kernel group is optional but it can be used to rename a given consumer group when for example you migrate from a different system that had group names already defined and you want to preserve the offset.

**Comment by mensfeld** [comment]
Quick update: we will drop consumer options overwrite from topic level - if needed, will require a consumer wrapper. Why? Because consistency is better than semi-feature.
