### ISSUE TITLE
Explicit workers

### ISSUE THREAD

**Issue by 90yukke** [karafka/karafka#17]
There should be an abillity to use explicit sidekiq workers, since current implicit creates more problems that it solves:
- it's impossible to use sidekiq plugins
- what if I want to use enterprise version of sidekiq
- there's not option to prioritise sidekiq workers

and so on. It'd be 100 times better to be able to use user-defined workers.

**Comment by mensfeld** [comment]
```ruby
class TestController < Karafka::BaseController
  # This can be any type of worker that provides a perform_async method
  self.worker = MyDifferentWorker
end
```
