### ISSUE TITLE
Seeing 0 consumer_groups in Karafka::App

### ISSUE THREAD

**Issue by torreypayne** [karafka/karafka#1718]
While upgrading Karafka from 1.4 to 2.0, I tried to validate that the consumer_group names were (or were not) changed. Following the instructions in the Upgrade guide for 1.4 -> 2.0, I opened up the Rails console (in development and production), and Karafka::App.consumer_groups.count is equal to 0, even though we have 6 defined in karafka.rb. Not sure what's happening here but we are not seeing _any_ consumer_groups listed. I made sure to check the rails console locally, in production, for our kafka queue instance as well as non-queue instance.

--------

## Expected behavior

`Karafka::App.consumer_groups.count == 6`.

## Actual behavior

`Karafka::App.consumer_groups.count == 0`

## Steps to reproduce the problem

Add consumer_groups to your karafka.rb file, open up the console, and run `Karafka::App.consumer_groups.count`. Our file is defined like so:

`KarafkaApp < Karafka::App
    setup do |config|
      ...
    end
  
    consumer_groups.draw do
      consumer_group :enum_1 do
        ...
      end   
      consumer_group :enum_2 do
        ...
      end
      ...
      consumer_group :enum_6 do
        ...
      end
    end
`

## Your setup details

I, [2023-11-01T09:48:50.269012 #9174]  INFO -- : Initializing Karafka framework 9174
I, [2023-11-01T09:48:50.332660 #9174]  INFO -- : Karafka version: 1.4.6
Ruby version: 2.7.6
Ruby-kafka version: 1.3.0
Application client id: {app}-development
Backend: inline
Batch fetching: false
Batch consuming: false
Boot file: {root}/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://localhost:9092"]
```

**Comment by mensfeld** [comment]
1.4 is EOL since February: https://karafka.io/docs/Versions-Lifecycle-and-EOL/ and I no longer provide extended support for it.

Are you seeing no CGs in 2.0 or 1.4 because this is not clear to me. Can you provide me with your FULL karafka.rb?

**Comment by mensfeld** [comment]
Since I do not see any responses, I assume it's fixed.
