### ISSUE TITLE
Redis namespace

### ISSUE THREAD

**Issue by 90yukke** [karafka/karafka#18]
In default sidekiq config there's a possibility to specify redis namespace:

```ruby
  config.redis = { url: 'redis://redis.example.com:7372/12', namespace: 'mynamespace' }
```

And karafka configuration lack this parameter. 

I'm not sure how it should be resolved, since it really adds maintainability cost to support every sidekiq's option. That's why I think that explicit workers are great choice.

**Comment by agwozdowski** [comment]
Done - example app will be updated in few minutes
