### ISSUE TITLE
Karafka should respond to SIGHUP

### ISSUE THREAD

**Issue by mach-kernel** [karafka/karafka#183]
As devops, when I send `karafka` [SIGHUP](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGHUP), it should cleanly bring down and restart both server and worker (depending on what was notified). For worker, I know that `sidekiq --daemon` will reload/restart when invoking `SIGHUP` -- and we already track our PIDs in `tmp`, so this change should be fairly easy to implement.

**Comment by mensfeld** [comment]
I don't thing we should restart sidekiq. #147 will isolate those two totally.

**Comment by mach-kernel** [comment]
Yes I agree, I mention `sidekiq` to illustrate that it already does this behavior so we don't have to actually make any changes on our end 😸

**Comment by mensfeld** [comment]
@mach-kernel how do you think this should work? should we fork and reload the code, leave the same process, just teardown and reload or shutdown and create new one?

Also I think, sidekiq should totally not be related with this one as we will drop the worker code in favor managing that on user side normally.

**Comment by mach-kernel** [comment]
I would do fork + reload.

**Comment by mensfeld** [comment]
@mach-kernel i don't think so. You're going to be the one to roll out the deattachment of Karafka and sidekiq so we can have adapters (sidekiq, threads, celluloid, whatever) and then what? Should we focus on supporting each of them? I think that apart from the base server any other execution environment handling should be up to users. Let's take puma as example, even when you  schedule some stuff to sidekiq from it, you don't expect puma to restart it.

**Comment by mensfeld** [comment]
@mach-kernel any activity on this one?

**Comment by mach-kernel** [comment]
@mensfeld I have been drowning under work but will hopefully PR this sometime this weekend!

**Comment by mensfeld** [comment]
@mach-kernel ping ;)

**Comment by mensfeld** [comment]
Rejected due to inactivity
