### ISSUE TITLE
Seek to

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#184]
ruby-kafka now provides an option to seek back to reprocess some stuff. I think we should add an api for that as well on our level.

**Comment by mensfeld** [comment]
New callbacks allow this to happen in a pre_fetching hook

**Comment by aemadrid** [comment]
@mensfeld could you please expand more on this? I'm looking at https://github.com/karafka/karafka/wiki/Manual-offset-management-(checkpointing) but I'm not seeing where seeking could be implemented. Could you please elaborate more?

**Comment by mensfeld** [comment]
Ah the link that points to a proper callback do not work. I will fix that soon.

Since there is no controller instance prior to fetching (as they are lazy initialized per topic partition) you need to use the client directly to seek before fetching:

https://github.com/karafka/karafka/blob/master/lib/karafka/connection/listener.rb#L19
