### ISSUE TITLE
[CLI] option --include-consumer-groups not working as intended after removal of "thor"

### ISSUE THREAD

**Issue by lucaslsl** [karafka/karafka#1843]
With the removal of `thor` in version [v2.2.8](https://github.com/karafka/karafka/releases/tag/v2.2.8),
passing server options like below no longer works:
`bundle exec karafka server --include-consumer-groups group_name1 group_name3`

Instead, we need to pass them as:
`bundle exec karafka server --include-consumer-groups group_name1,group_name3`
(with comma separated strings, as documented by ruby's OptionParser).

This most likely applies to all other array options (`--include-subscription-groups`, `--include-topics`) and makes the [documentation outdated/wrong](https://karafka.io/docs/CLI/#karafka-server).  In theory, this update also introduced a breaking change if we consider CLI  under semver.

This is not a deal breaker for me, and I fully support the idea of getting rid of dependencies whenever possible, just thought I should report this since it took me a while to figure out why my consumers werent working after I updated karafka.
Maybe updating the Docs should be enough for now.

--------

## Expected behavior

`karafka server --include-consumer-groups group_name1 group_name3` should start 2 consumer groups, `group_name1` and `group_name3`

## Actual behavior

`karafka server --include-consumer-groups group_name1 group_name3` picks up only the first name (`group_name1`), starting a single consumer group.

## Steps to reproduce the problem

Running karafka version 2.2.8 or latest, declare two or more consumer groups (e.g: name1, name2, name3), and start the server with the option to run specific groups:
`karafka server --include-consumer-groups group_name1 group_name3`.
The server will start, but only the first group declared will be picked up.

## Your setup details

Please provide kafka version and the output of `karafka info` or `bundle exec karafka info` if using Bundler.

Here's an example:

```
Karafka version: 2.2.14
Ruby version: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
Rdkafka version: 0.14.7
Consumer groups count: 10
Subscription groups count: 10
Workers count: 5
Application client id: karafka
Boot file: /app/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
Thanks. It is surprising my specs did not catch it. Sorry for the trouble. It will be fixed in the upcoming 2.3.0.

**Comment by mensfeld** [comment]
Ok I know why. Let me fix this...

**Comment by mensfeld** [comment]
Ok, won't fix. I would have to rewrite whole optparser engine. I will update docs and add an upgrade note in 2.3.0 to notify the end users. Sorry for the trouble :pray: 

I will add specs to cover the comma case nonetheless.

**Comment by mensfeld** [comment]
@lucaslsl PR with spec has been added to cover the comma case. Docs have been updated and released. Thanks.
