### ISSUE TITLE
Support ruby-kafka `ssl_ca_cert_file_path` config

### ISSUE THREAD

**Issue by webandtech** [karafka/karafka#186]
I was looking at the 0.6.0 changes and I noticed that the `ssl_ca_cert_file_path` option from ruby-kafka isn't included in the updated configs. Could we add that? It is now required to use karafka with Heroku Kafka. See: https://devcenter.heroku.com/articles/ca-cert-rotation-kafka#ruby-kafka

Simply allowing `config.kafka.ssl_ca_cert_file_path` to be set would allow the proper configuration.

**Comment by mensfeld** [comment]
@webandtech thank you for your contribution! I will review the changes max in 2 days (probably will do it faster)

**Comment by webandtech** [comment]
@mensfeld it will have to be changed for 0.6.0. When are you planning to release it?

**Comment by mensfeld** [comment]
@webandtech that is a tricky question. 0.6 has been running on production for me for a while so I consider it stable BUT the docs aren't. I need to update them and due to the number of changes, I need to go thought all of them :( So I expect to make a rubygems release of 0.6 in 2-3 weeks.

**Comment by webandtech** [comment]
@mensfeld no problem. You could consider publishing RC versions of this and the updated waterdrop gem. See: http://guides.rubygems.org/patterns/#prerelease-gems i.e you could release `0.6.0.rc1`

**Comment by mensfeld** [comment]
@webandtech  will do. Waterdrop is already bumped and released as 0.4 > https://rubygems.org/gems/waterdrop

**Comment by mensfeld** [comment]
@webandtech  will do an RC after the weekend.
