### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by konalegi** [karafka/karafka#1876]
I have a question rather than reporting a bug. We've observed an issue with the errors reported by Karafka to Sentry, specifically regarding invalid breadcrumbs. These errors seem to include breadcrumbs for all processed events, lacking a proper set of transaction start and end. I've noticed that Sidekiq does everything properly and it turns out Sentry has a gem called sentry-sidekiq for Sidekiq, which successfully enables proper breadcrumbs through its middleware ([source](https://github.com/getsentry/sentry-ruby/blob/master/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L8-L36)).
I've attempted to find a similar solution for Karafka but haven't been successful. Is there no equivalent solution for Karafka, or am I overlooking something obvious?

Thanks!

**Comment by mensfeld** [comment]
Karafka has no sentry integration or rather sentry has no karafka integration. Whatever you get comes probably from your custom integration.

**Comment by konalegi** [comment]
Thanks for a quick reply!
