### ISSUE TITLE
Can't run karafka install (uninitialized constant Rdkafka::Bindings::RD_KAFKA_RESOURCE_ANY)

### ISSUE THREAD

**Issue by JorgeGarciaxyz** [karafka/karafka#1917]
## Expected behavior

Running `bundle exec karafka install` should create the initial files. 

## Actual behavior

It crashes with the next error:

```ruby
bundler: failed to load command: karafka (/Users/my-username/.asdf/installs/ruby/3.2.2/bin/karafka)
/Users/my-username/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-2.3.2/lib/karafka/admin/acl.rb:24:in `<class:Acl>': uninitialized constant Rdkafka::Bindings::RD_KAFKA_RESOURCE_ANY (NameError)

        any: Rdkafka::Bindings::RD_KAFKA_RESOURCE_ANY,
                              ^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  Rdkafka::Bindings::RD_KAFKA_VTYPE_RKT
```

## Steps to reproduce the problem

I just ran the command `bundle exec karafka install` (after installing the gem) on two different apps with the same result.

I tried all 2.3.x versions, and had the exact result. Running on 2.2.14 works. As expected as [the change only affected 2.3](https://github.com/karafka/karafka/commit/37e17de6c68d1fcd3efeaa0679ee53a95f45032d) versions. 

## Your setup details

I can't run the command, I have the same error. Here's some info:

Ruby version: 3.2.2 & 3.3.0
Karafka versions: 2.3.2 -> 2.3.0alpha
OS: MacOs 14.3 

Note: a teammate has the same problem using `rbenv` instead of `asdf`

**Comment by mensfeld** [comment]
@JorgeGarciaxyz what is your karafka-rdkafka version? are you using karafka-rdkafka and rdkafka-ruby in the same app? what is your gemfile?

**Comment by JorgeGarciaxyz** [comment]
@mensfeld thanks for the answer 👌  I found I have an incompatibility due to Racecar declaring `rdkafka (~> 0.13.0)`, removing Racecar solves the issue. 

Im closing this for now.

**Comment by mensfeld** [comment]
Yes, you cannot use both. They are not compatible.

FYI you can get more help on our slack: https://karafka.io/slack - I encourage you to join :)
