### ISSUE TITLE
Simpler Installation steps For Standalone app

### ISSUE THREAD

**Issue by divyesh2506** [karafka/karafka#192]
There are installation steps here -> [rubydoc link](http://www.rubydoc.info/github/karafka/karafka#Installation)

But this does not work. One necessity I see there is a Rakefile to run the rake karafka:install command.

I tried copying the same from example [app](https://github.com/karafka/karafka-example-app/blob/master/rakefile.rb), but that shows a rake error :

> Don't know how to build task 'karafka:install'

**Comment by agwozdowski** [comment]
If you use `karafka example app`, you don't have to run `karafka:install`. You should only run `bundle install` and follow the instructions from the [example app Wiki](https://github.com/karafka/karafka-example-app/blob/master/README.md) how to run server, worker and how to send messages.

You can also run karafka with CLI.
```
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'karafka'" >> Gemfile
bundle install
karafka install
```

**Comment by divyesh2506** [comment]
Hey @agwozdowski, that did work . Thanks.

**Comment by agwozdowski** [comment]
You're welcome. I'll close issue
