### ISSUE TITLE
Topic mapper does not map topics when subscribing

### ISSUE THREAD

**Issue by webandtech** [karafka/karafka#196]
We are attempting to use a topic mapper to allow us to transparently add a prefix to the topics without having to explicitly add it when drawing routes or configuring responders, however we found that even with a topic mapper defined in setup, Karafka would still subscribe to the bare topics (unprefixed).

In this situation:

```
# topic_mapper.rb
module StagingTopicMapper
    PREFIX = 'staging_'

    def self.incoming(topic)
      topic.to_s.gsub(PREFIX, '')
    end

    def self.outgoing(topic)
      "#{PREFIX}#{topic}"
    end
  end
```

```
  # app.rb
  consumer_groups.draw do
      topic :my_topic
    end
```

Karafka should subscribe to the topic `staging_my_topic` but it instead subscribes to `my_topic` as if there was no topic mapper registered.

PR to follow!

**Comment by mensfeld** [comment]
Works on my side. Feel free to reopen if you have any more problems with it. I will also add an issue to create more specs to cover that. That way, we won't lose this case never again.
