### ISSUE TITLE
Proper way to use independent option for DLQ

### ISSUE THREAD

**Issue by fusion2004** [karafka/karafka#2058]
Hi! It was unclear to me exactly how to use the independent error counting feature for dead letter queues after reading https://karafka.io/docs/Dead-Letter-Queue/#independent-error-counting

After looking over https://github.com/karafka/karafka/pull/1790 I believe I need to use `mark_as_consumed` on each message as the consumer iterates?

If that's correct, maybe we should update that doc with a code example of how a consumer should work to take advantage of the feature?

**Comment by mensfeld** [comment]
@fusion2004 you fancy a PR? https://github.com/karafka/wiki :)

**Comment by fusion2004** [comment]
submitted (although it is very basic 😅): https://github.com/karafka/wiki/pull/30
