### ISSUE TITLE
Karafka ignores `client_id` setting

### ISSUE THREAD

**Issue by Lianowar** [karafka/karafka#2156]
After upgrade to 2.4.3 version from 2.3.4 we saw the weird behavior

## Expected behavior

When we pass `client_id` setting

```ruby
setup do |config|
   config.client_id = 'my_client_id'
end
```
it should be named as `my_client_id_app` in the kafka as by [documentation](https://karafka.io/docs/Upgrades-2.4/#consumer-mapper-concept-removal)

## Actual behavior

In the kafka i saw that it named as just `app` and do not respect any `client_id` setting

## Your setup details

```
$ [bundle exec] karafka info
Karafka version: 2.4.3
Ruby version: ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux-musl]
Rdkafka version: 0.16.0
Consumer groups count: 6
Subscription groups count: 6
Workers count: 5
Application client id: my_client_id
Boot file: /home/app/karafka.rb
Environment: production
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
What do you mean by:

> In the kafka i saw that it named as just app and do not respect any client_id setting

What did you saw? Is the client_id missing or are you referring to group naming?

**Comment by Lianowar** [comment]
Yes, i see that `client_id` setting missed, all services called just `app`
Where we use the `consumer_group` - there is naming changed to consumer_group name
e.g we have

```ruby
    consumer_group :moderation do
      topic :profile_moderation do
        consumer ModerationConsumer
      end
    end
```
and in the kafka it called just `moderation`

**Comment by mensfeld** [comment]
its exactly as the docs say:

>  Below, you can find how Karafka pre 2.4 would remap the following routing:

This refers to pre 2.4. The client id reference mapping to consumer groups has been retired.

**Comment by Lianowar** [comment]
```ruby
class KarafkaApp < Karafka::App
  setup do |config|
    config.client_id = 'push_service'
  end

  routes.draw do
    topic :push_notification do
      consumer PushNotificationConsumer
    end
  end
end
```

and there `app` name in kafka

**Comment by mensfeld** [comment]
Yes. This is exactly as expected. You use implicit consumer group that is a subject to the same behaviours as explicit consumer groups. There is no error in the docs, nor in how Karafka behaves.

**Comment by Lianowar** [comment]
So, for save old name we need to pass `group_id='push_service'`?

**Comment by mensfeld** [comment]
You may do that or you may materialize your consumer group in an explicit way.

**Comment by Lianowar** [comment]
thank you very much
But what purpose of `client_id` for now?

**Comment by mensfeld** [comment]
https://github.com/karafka/karafka/blob/563a43548459bc606dad3e182f967724bd075b7f/lib/karafka/setup/config.rb#L389

**Comment by Lianowar** [comment]
I was confused by documentation
because as I understood it says that when we pass `client_id` we got `my-app_app`
I found it on [that page](https://karafka.io/docs/Upgrades-2.4/#consumer-mapper-concept-removal)
![Screenshot from 2024-06-24 18-17-23](https://github.com/karafka/karafka/assets/5867875/ba993fc0-94c2-48d5-b171-50b9fb68111a)
