### ISSUE TITLE
Docs request: more details on configuration tuning

### ISSUE THREAD

**Issue by rsanheim** [karafka/karafka#2178]
## Is your feature request related to a problem? Please describe.

Not a problem, just a docs request:

* please add the defaults that Karafka sets in https://karafka.io/docs/Latency-and-Throughput/#configuration-tuning_1. These are important settings, and it isn't clear what Karafka ships with without consulting the code.
* Also, are these settings also available to be set scoped? It isn't clear from the docs, but from the code it looks like things like `max_messages` can be set at multiple levels:

```
~/src/oss/karafka/karafka (master)] (2.459s) > ag max_messages lib
lib/karafka/connection/client.rb
89:          break if @buffer.size >= @subscription_group.max_messages

lib/karafka/contracts/topic.rb
18:      required(:max_messages) { |val| val.is_a?(Integer) && val >= 1 }

lib/karafka/setup/config.rb
73:      # options max_messages [Integer] how many messages do we want to fetch from Kafka in one go
74:      setting :max_messages, default: 100

lib/karafka/routing/topic.rb
21:        max_messages

lib/karafka/routing/subscription_group.rb
65:      def max_messages
66:        @topics.first.max_messages

lib/karafka/routing/subscription_groups_builder.rb
19:        max_messages
```

## Describe the solution you'd like

More explicitness on https://karafka.io/docs/Latency-and-Throughput/#configuration-tuning_1

## Describe alternatives you've considered

reading the code 😁 

## Additional context

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/d11f57b8-5404-4c5a-9b9b-ec7bbdd48f29">

**Comment by rsanheim** [comment]
Another thought - it may be helpful to provide a couple examples of config settings to start with for two contexts:

1) reduced latency / as close to realtime as possible / etc
2) high throughput / processing large batches fast

I realize the settings will be very different for every use case, and of course the docs should stress 'do you own benchmarking'.  But setting something reasonable to start with would be helpful as a baseline.

**Comment by mensfeld** [comment]
> Also, are these settings also available to be set scoped? It isn't clear from the docs, but from the code it looks like things like max_messages can be set at multiple levels:

explained

**Comment by mensfeld** [comment]
> I realize the settings will be very different for every use case, and of course the docs should stress 'do you own benchmarking'. But setting something reasonable to start with would be helpful as a baseline.

I don't want to do it. It's so per-case specific that I don't have any "great" defaults. This depends on factors like OSS/Pro, type of traffic, nature of topics, number of topics and more. I can promise that if I come up with good defaults, I will add them there :)
