### ISSUE TITLE
1.0 release date?

### ISSUE THREAD

**Issue by undergroundwebdesigns** [karafka/karafka#222]
Hello!

I see a lot of work has gone into the master over the past couple months but the latest release is still 0.5, would it be possible to get an estimate of when 1.0 will be ready for release?

**Comment by mensfeld** [comment]
Hey there. It has been released: https://rubygems.org/gems/karafka/versions/1.0.0 and here are the release notes: https://medium.com/@maciejmensfeld/karafka-ruby-kafka-framework-1-0-0-release-notes-1b0933d47e88

**Comment by mensfeld** [comment]
We will release 1.0.1 in max 2 weeks as it covers some new features and fixed some bugs
