### ISSUE TITLE
Error with consuming messages in array format

### ISSUE THREAD

**Issue by victorphamdeveloper** [karafka/karafka#223]
Hi guys, I am currently experiencing issue with message that are sent in array format . Seems like it was doing a merge and expect the message to be a hash type. Is this a bug of karafka ?

<img width="728" alt="screen shot 2017-09-26 at 4 55 57 pm" src="https://user-images.githubusercontent.com/2957401/30851604-a9122b5c-a2db-11e7-9604-93d432ef88ba.png">

Thanks in advance

**Comment by mensfeld** [comment]
It expects a hash by default BUT just use a custom parser as described here: 

https://github.com/karafka/karafka/wiki/Parsers

Parse your message and return inside a hash key (like data or anything) and then it will merge with the rest of the params. I will keep this open as I will make readme updates to cover that case.

**Comment by victorphamdeveloper** [comment]
I wrote a custom parser according to the wiki to consume the array.  Will close this ticket.

**Comment by mensfeld** [comment]
I reopened it so I won't forget to apply readme updates later today.

**Comment by mensfeld** [comment]
I've updated the parsers section of the wiki to cover that case: https://github.com/karafka/karafka/wiki/Parsers
