### ISSUE TITLE
Deprecation warning in AppSignal instrumentation

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#2238]
We need to update the instrumentation

**Comment by tombruijn** [comment]
Hi @mensfeld, Tom here from AppSignal. I was linked to this issue and PR #2242. AppSignal for Ruby gem 4 has some backwards compatible changes. I don't see a dependency on the AppSignal gem so it should probably continue to work with both v3 and v4 (for a while)? I can make a PR.

**Comment by mensfeld** [comment]
Hey @tombruijn Karafka is not dependent on AppSignal gem. It's up to the user to define the version that (can) use.

I am ok with having a conditional statement with version differentiation or a change that would make this work with older and never appsignal gem.

**Comment by mensfeld** [comment]
solved here: https://github.com/karafka/karafka/issues/2238
