### ISSUE TITLE
Unable to override WaterDrop settings

### ISSUE THREAD

**Issue by ankitagupta12** [karafka/karafka#225]
`Karafka::Setup::Configurators::WaterDrop` hardcodes the value for `send_messages` and `raise_on_failure` to true. This makes it difficult to override the settings inside an app to `false` for development environment.

```
::WaterDrop.setup do |water_config|
            water_config.send_messages = true
            water_config.raise_on_failure = true
            water_config.connection_pool = config.connection_pool
            .
            .
end
```

The values should ideally we configurable similar to `connection_pool` settings so that they can be defined in the config and overridden as necessary

**Comment by ankitagupta12** [comment]
@mensfeld here's a PR for this issue: https://github.com/karafka/karafka/pull/226. let me know if this looks okay

**Comment by mensfeld** [comment]
@ankitagupta12 as a temp workaround you could just overwrite it with your own settings after the ```App.boot!```

**Comment by mensfeld** [comment]
@ankitagupta12 this is how it will work in 1.1:
```ruby
class App < Karafka::App
  setup do |config|
    config.kafka.seed_brokers = ::Settings.kafka.seed_brokers
    config.kafka.offset_commit_threshold = 30
    config.client_id = ::Settings.name
    config.monitor = KarafkaMonitor.instance
    config.backend = :inline
  end

  consumer_groups.draw do
    consumer_group 'a' do

      topic :a do
        backend :inline
        controller CountersController
        batch_processing true
        persistent true
        interchanger nil
        responder CountersResponder
      end
    end
  end
end

App.boot!

WaterDrop.setup do |water_config|
  # overwrite here any defaults or things from karafka settings
end

```

**Comment by mensfeld** [comment]
Overwritable as mentioned above with better integration from 1.1
