### ISSUE TITLE
Add expandability to current liveness probe structure.

### ISSUE THREAD

**Issue by hbontempo-cw** [karafka/karafka#2302]
## Is your feature request related to a problem? Please describe.

Checking if Kafka is behavior is as expected is not the only requisite to make sure the application is live.
Applications usually require databases, blob storage, cache and other external resources to work and would be great to be able to take all of them into account in k8s liveness_check. 
I want to be able to inject my custom liveness check to `Karafka::Instrumentation::Vendors::Kubernetes::LivenessListener`

## Describe the solution you'd like

Accept a block to `::Karafka::Instrumentation::Vendors::Kubernetes::LivenessListener#initialize` where user could add it's code to make sure application is live.

```ruby
require 'karafka/instrumentation/vendors/kubernetes/liveness_listener'

listener = ::Karafka::Instrumentation::Vendors::Kubernetes::LivenessListener.new(
  port: 3000,
  polling_ttl: 300_000,
  consuming_ttl: 60_000
) do |liveness_listener|
  # Execute checks to make sure the application is live and ready to process messages
  #   - Is DB live?
  #   - Is Redis responding?
  # Example:
  liveness_listener.failed('Redis not responding') unless redis_alive?
end

Karafka.monitor.subscribe(listener)
```

## Describe alternatives you've considered

A builder api could could offer a clean way of making the same thing as well:
```ruby
require 'karafka/instrumentation/vendors/kubernetes/liveness_listener'

listener = ::Karafka::Instrumentation::Vendors::Kubernetes::LivenessListener.new(
  port: 3000,
  polling_ttl: 300_000,
  consuming_ttl: 60_000
) 

# Add checks to be validated one by one
listener.add_check do |check|
  check.failed('Redis not responding') unless redis_alive?
end
listener.add_check do |check|
  check.failed('Postgres not responding') unless pg_alive?
end

Karafka.monitor.subscribe(listener)
```

## Additional context

A better log on why the liveness check is failing would be great as well.
Currently if it fails it's not clear if it's because of the `polling_ttl` or the `consuming_ttl`

**Comment by mensfeld** [comment]
Why can't you just subclass and overwrite `#healthy?` with the super call?

```ruby
MyListener < ::Karafka::Instrumentation::Vendors::Kubernetes::LivenessListener
  def healthy?
    return false unless super
    return false unless redis_alive?
    return false unless whateverchecksyouwant
    
    true
  end
end
```

**Comment by hbontempo-cw** [comment]
Sure, I can, but I'm not very confortable overriding an undocumented private method (I have no guarantees that this internal implementation is not going to change).
I was looking for an official/supported way of extending the Listener.

**Comment by mensfeld** [comment]
Yeah I think it wouldn't harm to add it actually.

**Comment by mensfeld** [comment]
@hbontempo-cw would me promoting `#healthy?` as an official API satisfy you? then you could just inherit and `super`. I can make it an official API for users to expand. I do not want to add complex builders mostly because this layer aims to be fairly simple
