### ISSUE TITLE
Command line arguments are not used when running in swarm mode

### ISSUE THREAD

**Issue by roelbondoc** [karafka/karafka#2305]
I am starting a consumer with the following command:

```
bundle exec karafka swarm --include-consumer-groups group1
```

This group should only be subscribed to a single topic (ie `topic1`). However, from what I am observing, the consumer ignores any command line option and will start all consumer groups. I've tried all `--include*` and `--exclude*` variations and nothing seems to pass to the actual consumers.

--------

## Expected behavior

I expect any option I use with `karafka server` to also work with `karafka swarm` as [specified in the docs](https://karafka.io/docs/Swarm-Multi-Process/#cli-configuration-options).

## Actual behavior

Any option passed to `karafka swarm` does not work.

## Steps to reproduce the problem

1. Define karafka routes with multiple consumers subscribed to different topics.
2. Start a karafka swarm and specify to include a single consumer group only.
3. Observer that your karafka swarm consumer starts all consumer groups.

## Your setup details

```
$ bundle exec karafka info
Karafka version: 2.4.13 + Pro
Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [aarch64-linux]
Rdkafka version: 0.17.6
Consumer groups count: 7
Subscription groups count: 7
Workers count: 1
Application client id: honeybadger
Boot file: /app/karafka.rb
Environment: development
License: Commercial
License entity: Honeybadger
```

**Comment by roelbondoc** [comment]
I believe that when `parse!` [is called](https://github.com/karafka/karafka/blob/master/lib/karafka/cli/base.rb#L99) to parse the command line arguments, they are no longer available when swarm tries to [instantiate a new server](https://github.com/karafka/karafka/blob/master/lib/karafka/cli/swarm.rb#L22).

**Comment by mensfeld** [comment]
I can confirm that this indeed is a bug.
