### ISSUE TITLE
Karafka logs appearing from time to time

### ISSUE THREAD

**Issue by eduardoconviso** [karafka/karafka#2321]
I use Karafka in my production environment and the logs just come occasionally, making me think nothing is happening.
Is there a way to make it produce logs in real-time?

I am using Karafka 2.2.10 (I know it is old, we are taking care of it)

**Comment by mensfeld** [comment]
3 things here:

1. Your version is beyond EOL: https://karafka.io/docs/Versions-Lifecycle-and-EOL/
2. Your report does not provide the needed details: https://karafka.io/docs/Support/#issue-reporting-guide
3. https://karafka.io/docs/FAQ/#why-karafka-prints-some-of-the-logs-with-a-time-delay

If you believe it is not the stdout sync issue feel free to reopen it with the **required** information.
