### ISSUE TITLE
Karafka::Errors::InvalidConfigurationError kafka.bootstrap.servers and metadata.broker.list

### ISSUE THREAD

**Issue by Peredery** [karafka/karafka#2333]
Bug Report Details
===========
```
Karafka::Errors::InvalidConfigurationError:
  {:"kafka.bootstrap.servers"=>"needs to be present"}
```

bootstrap.servers options is listed as "Alias for metadata.broker.list". But if I only set metadata.broker.list (and keep afka.bootstrap.servers empty) it will give me error. 

===========

https://karafka.io/docs/Librdkafka-Configuration/#global-configuration-properties [Alias for metadata.broker.list]

**Comment by mensfeld** [comment]
Well the aliasing that way is librdkafka convention. Karafka requires it via boostrap servers.
