### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by filiptepper** [karafka/karafka#241]
Per discussion in Gitter.

I'd love to be able to track some kind of performance metrics for controllers, eg. how long does it take to execute `perform`.

**Comment by mensfeld** [comment]
@filiptepper  do you have an idea on how you would like it to work?

**Comment by filiptepper** [comment]
@mensfeld Perhaps a wrapper with `yield` in https://github.com/karafka/karafka/blob/master/lib/karafka/monitor.rb?

**Comment by mensfeld** [comment]
won't release until https://github.com/dry-rb/dry-monitor/issues/6 - but workable so in progress...

**Comment by mensfeld** [comment]
@filiptepper  I will mark it as resolved. For now the code is in monitor branch, but will be merged to master and released soon.
