### ISSUE TITLE
Error in the monitor code for NewRelic

### ISSUE THREAD

**Issue by ankitagupta12** [karafka/karafka#262]
https://github.com/karafka/karafka/wiki/Monitoring-and-logging#example-monitor-with-newrelic-support 
```
 def consume(topic)
    record_count metric_key(topic, __method__)
 end
```
is not invoked because the `caller_label` is `process` or `process_batch`

In `notice`, we do `send(caller_label, options[:topic])`. Since options is an array or a ParamsBatch object, we can't get the topic information by doing `options[:topic]`. As a result, this line is errors out as well

**Comment by mensfeld** [comment]
We will go with dry-monitor, working on that one...

**Comment by mensfeld** [comment]
Related with #241

**Comment by mensfeld** [comment]
Update on this one and #241 - there has been a dry-monitor release so I'm working on it ;)

**Comment by mensfeld** [comment]
@ankitagupta12 would you be willing to build up a new newrelic plugin based on a new monitor?

**Comment by mensfeld** [comment]
I've pinged NewRelic for an account that will support custom keys, if they won't provide one I will just remove the newrelic code. If they will, will update it myself (really simple).
