### ISSUE TITLE
Why is Karafka so slow? / Invalid benchmarking

### ISSUE THREAD

**Issue by imanel** [karafka/karafka#280]
While working on benchmark of [Kafka frameworks for Ruby](https://github.com/imanel/kafka-ruby-benchmark) I've discovered that Karafka is really slow. Since there is barely any configuration (only autogenerated one) I thought that I might be missing something. Is that [configuration problem](https://github.com/imanel/kafka-ruby-benchmark/blob/master/karafka_json/karafka.rb) or it's that Karafka is simply slower than other frameworks?

**Comment by mensfeld** [comment]
@imanel it must be a configuration problem as few days ago I did some benchmarking and I could say it is the opposite.

 I see, that you don't benchmark Karafka itself but rather JSON parser that it provides. Keep in mind, that we use multijson as Karafka supports jruby.

It means, that we explicitly don't use faster JSON parsers. Also, please use:

```
config.backend = :inline
config.batch_fetching = true
config.batch_consuming = true
config.persistent = true
```

Note that due to the logging we do for non-prod envs, printing to stdout can have a serious impact as well. I will try to play with your code this week to see what exactly is the bottleneck there.

**Comment by mensfeld** [comment]
@imanel  Although your benchmarks aren't good (they don't benchmark things they should and include things they shouldn't) I found some bottlenecks. Here are my results (will push updates today):

```bash
Time taken: 1.630755032
Time taken: 1.884534825
Time taken: 1.793302858
Time taken: 1.799568337
Time taken: 1.858707786
Time taken: 2.094316796
Time taken: 1.858558676
Time taken: 1.827588745
Time taken: 2.102556779
```

**Comment by imanel** [comment]
If I'm reading correctly `delivery: batch` for Phobos is equal to `batch_fetching = true` in Karafka, which I'm using.

I'm deliberately not using `batch_consuming` and `persistent`, and they are reusing controller, making bootstrap and teardown process much harder. And they are not available for other implementation, so that would be cheating (except of pure kafka-ruby use, but it was just reference point).

The flow I'm testing is fairly standard - consumer receives encoded message, parses it, does some logic (the same for every benchmarked framework), and counts how much time it takes to go through batch. May I ask what part should not be part of benchmark, and what should get added?

I will add explicit use of JSON parser to Karafka benchmark so the comparison will be fair, but I doubt it will change much as AVRO benchmark shows that there is some bottleneck unrelated to parser used.

**Comment by imanel** [comment]
Updated, switching to JSON gem natively boosted performance by ~8%. If you have more suggestions about how could I improve this benchmark then please let me know.

**Comment by mensfeld** [comment]
@imanel would be super cool if you could ping me via email (maciej@mensfeld.pl) so we could sort it out - maybe even with skype call as it would be much faster then writing looong messages that would just duplicate a lot of docs. I could fast explain to  you some of the engineering solutions and why having Karafka configured in certain way can slow it down (and after that maybe create a wiki page).

**Comment by mensfeld** [comment]
Since we're already in touch and the monitor branch is as expected, I will close this one for now.
