### ISSUE TITLE
drop activesupport callbacks in favor of notifications

### ISSUE THREAD

**Issue by nijikon** [karafka/karafka#288]
- [x] use internal callbacks instead of `activesupport` ones
- [x] drop `activesupport` gem from dependencies list, add to development for specs

**Comment by mensfeld** [comment]
We could easily switch from callbacks in general to notifications using dry-notifications

**Comment by mensfeld** [comment]
We could do this easily by switching to  dry-events and removing the callbacks completely BUT the only problem I can see is with controllers callbacks. We can easily drop the sidekiq enqueuing rejection (from the sidekiq backend) as this can be easily done with a custom engine. What worries me is the ability to bind to given controller lifecycle events from within controller in the same way as we do now - this is super clear and understandable. So I would imagine that for example:
```
after_fetch do
  # Some business logic
end
```

would have to be implemented in a listener way (pseudo really):
```
def after_fetch(&block)
  monitor.subscribe "controllers.#{self.underscore}", &block
end
```

BUT the question is how we could trigger that for ruby-kafka patches location and how we could efficiently (no performance degradation) detect that listeners are there (no need to run them against empty array).

**Comment by mensfeld** [comment]
only one usage of AS left in Karafka!

**Comment by mensfeld** [comment]
Aaaaand were done :tada:
