### ISSUE TITLE
When I try `bundle exec karafka install`, error`NameError: uninitialized constant Karafka::BaseWorker Did you mean?  Karafka::BaseController`

### ISSUE THREAD

**Issue by cxk280** [karafka/karafka#290]
I'm following the `bundle exec karafka install` command as instructed in the Getting Started docs, but I receive the following error.

`NameError: uninitialized constant Karafka::BaseWorker
Did you mean?  Karafka::BaseController`

I have not otherwise altered the code yet except for the following, which is also in the Getting Started docs:

echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'karafka'" >> Gemfile

How do I fix this? I'd just change the relevant code (in `app/workers/application_worker.rb`) to `Karafka::BaseController`, but I want to make sure this doesn't mess something up irreparably since I'm installing something.

Thanks for your help.

**Comment by mensfeld** [comment]
@cxk280 for the time being you can jsut clone our example repo. I'm checking that as we speak :)

**Comment by cxk280** [comment]
@mensfeld Yes, this is the example repo clone.

**Comment by mensfeld** [comment]
Hmm wait. Which part did you do? "Starting with the example app" or "Starting with a clean installation"?

**Comment by cxk280** [comment]
The first, then the latter.

**Comment by mensfeld** [comment]
And you had problems with the clean install right? It works for me without any problems when I follow the instructions...

**Comment by cxk280** [comment]
I figured out my error. I erroneously thought the you did the clean install _after_ cloning the example app. But the clean install is to start it without using the example app. This is my fault for not reading entirely closely. Thank you for your help!

**Comment by mensfeld** [comment]
@cxk280 no worries :) you are welcome. I will close it since it is resolved.
