### ISSUE TITLE
Testing with Karafka?

### ISSUE THREAD

**Issue by ariieh** [karafka/karafka#291]
Hey there good folks -- I've been installing Karafka on our Rails app recently and have been trying to write some RSpec tests for a consumer class I've written that inherits from `Karafka::BaseController` and includes `Karafka::Controllers::Callbacks`. Unfortunately I've found writing unit tests near impossible (as `params` appears to get defined dynamically) and an integration test very difficult without (seemingly) an intimate understanding of Karafka's internals. I'm pretty new to the framework and I'm wondering if I'm missing some documentation or something -- just looking to feel confident that our consumer class will indeed receive the messages we send it.

I've been really loving how intuitive and flexible Karakfa is - everything's been working great! Would love some advice so we can continue to work with this great framework.

**Comment by mensfeld** [comment]
Yeah we lack guides for that - #248 but won't leave you without anything. Will need couple of h. to prepare smthing.

**Comment by mensfeld** [comment]
Hey,

Note, that it is for Karafka 1.2.0-beta2 release. I will be releasing the official 1.2 to rubygems in couple of days (need to finish release notes and other associated stuff) - so not really planning to do the same for 1.1 BUT you should be able to adapt this code to match the 1.1 controllers format.

Consumer:
```ruby
# frozen_string_literal: true

# Consumer that is ment to handle xml data
# @note It will process single messages one after another as the batch_consuming
#   is set to false
class XmlMessagesConsumer < ApplicationConsumer
  def consume
    Karafka.logger.info "Consumed following message: #{params}"
  end
end
```

```ruby
# frozen_string_literal: true

RSpec.describe XmlMessagesConsumer do
  subject(:consumer) { described_class.new }

  let(:message_content) { "home-#{rand}" }

  before do
    consumer.class.topic = OpenStruct.new(
      parser: XmlParser,
      backend: :inline
    )
    consumer.params_batch = [{ value: "<message><new>#{message_content}</new></message>" }]
  end

  let(:params) { consumer.send(:params) }

  before { allow(Karafka.logger).to receive(:info) }

  it 'expects to log a proper message' do
    expect(Karafka.logger).to receive(:info).with("Consumed following message: #{params}")
    consumer.call
  end

  it 'expects to unparse message' do
    expect(params['message']['new']).to eq message_content
  end
end
```

**Comment by ariieh** [comment]
Thanks. Getting an error `undefined method `parser' for nil:NilClass` when I try to set `params_batch` -- it appears `topic` is not being set on my consumer class. Should I be setting this within the test?

**Comment by mensfeld** [comment]
@ariieh  you need to have karafka.rb included with the routes. If it doesn't help, you can always set it manually (it is fixed in 1.2 beta):

```ruby
      consumer.class.topic = OpenStruct.new(
        parser: Karafka::Parsers::Json,
        backend: :inline
      )
```

**Comment by mensfeld** [comment]
Man I really need to make this release official as there are so many things fixed and/or better...

**Comment by ariieh** [comment]
I just switched over to 1.2 actually

**Comment by ariieh** [comment]
sent ;-)

**Comment by mensfeld** [comment]
answered ;)

**Comment by mensfeld** [comment]
Testing wiki page for 1.2.0.beta2+: https://github.com/karafka/karafka/wiki/Testing
