### ISSUE TITLE
Is KARAFKA_ENV used anywhere?

### ISSUE THREAD

**Issue by ariieh** [karafka/karafka#293]
Hey there,

The `KARAFKA_ENV` environment variable gets set here:
`lib/karafka/templates/karafka.rb.example`

and here:
`spec/spec_helper.rb`

But it doesn't actually appear to be used anywhere. Can this be removed?

**Comment by mensfeld** [comment]
It is being used via https://github.com/karafka/envlogic and acts in a similar way as ```Rails.env.test?``` etc. It does not do anything in the karafka itself but provides a slim api for non-integrated apps.

**Comment by ariieh** [comment]
ok, thanks!
