### ISSUE TITLE
Why does the parsed value get written top-level onto params?

### ISSUE THREAD

**Issue by ariieh** [karafka/karafka#299]
Hey there,

Been playing around with Karafka some more today and ran into some difficulty with consumer `params` I have a potential solution for. Right now serialized messages get written onto consumer `params` at the top level, like so:

```ruby
{:parser=>Karafka::Parsers::Json, :partition=>2, :offset=>130, :key=>"1735",
:create_time=>2018-03-12 16:28:46 -0400, :receive_time=>2018-03-12 16:28:48 -0400,
:topic=>"menus", :parsed=>true, "name"=>"bob"}
```

Where "name" is a key of the hash we're sending. This works well enough, but it introduces several problems:

1. Other than by hackily searching the hash for all `String` keys, there's no way to pull out just the data that was sent from the producer, ignoring the metadata. This is an issue for us, for example, because we would like to log separately just the data that we received from Kafka.
2. Currently we are rescuing exceptions and alerting Bugsnag if there's a problem reading from `params`. If the parsing breaks, we lose data because of how the value field gets deleted.
https://github.com/karafka/karafka/blob/1b0bb640d6e21ed9b54efe3dc328a8e78c1be049/lib/karafka/params/dsl.rb#L96 
3. There's the potential for name collisions with data being sent -- if I sent over a message with a key of `topic`, for instance, I'd get a params hash that looks like this:
```ruby
{:parser=>Karafka::Parsers::Json, :partition=>2, :offset=>130, :key=>"1735",
:create_time=>2018-03-12 16:28:46 -0400, :receive_time=>2018-03-12 16:28:48 -0400, 
:topic=>"menus", :parsed=>true, "topic"=>"my-cool-cars"}
```
This will work, but beyond being a confusing and unlovely data structure, Ruby will treat `:topic` and `"topic"` the same when it comes to serialization, meaning you lose data. So `{"topic"=>"menus",:topic=>"joe"}.to_json` (which you might want to do for logging purposes, for instance) will result in `"{\"topic\":\"my-cars\",\"topic\":\"joe\"}`, and reparsing this will result in `{"topic"=>"joe"}`.

Suggested solution: Store the raw unserialized data on the hash on a nested key and the parsed data on a separate nested key, so maybe something like `{:topic => "menus", :raw_value => "{\"topic\":\"joe\"}", :value => {"topic"=>"joe"}}`. For backwards compatibility you could keep writing the original message key values directly onto the params hash, but given the high potential for name collision I would personally vote in favor of phasing this out.

**Comment by mensfeld** [comment]
Thank you for such a comprehensive description and interest in Karafka. Mine will be short as from mobile: did you try looking into custom parsers? It is surprising easy to implement your own. The reason why it is being merged into root by default is just because most of the time for cases in which I work my json is namespaced. If should  not take you longer than 5 minutes to implement a custom parser based on the parsers wiki section. The you will have the value inside for example a "value" key :)

**Comment by mensfeld** [comment]
https://github.com/karafka/karafka/wiki/Parsers

**Comment by mensfeld** [comment]
As mentioned above - I (maybe not exactly as expected) made the json root "namespace assumption" BUT as mentioned above custom parser won't take more than 5 minutes :) there's always a compromise and exactly that's the reason why we provide possibilities to change parser and many other things (including params base class in 1.2.beta4). If this answer is enough please close this issue :) I will put this question in the FAQ and will make this s behaviour more visible in the wiki. Will also reconsider namespacing during the work towards 1.3. have a nice evening

**Comment by mensfeld** [comment]
FYI this can be achieved also in a separate way (although I recommend using custom parser):

```ruby
params_batch.to_a.each do |unparsed_params|
  unparsed_params['value'] #=> raw value, not merged or anything - do with it whatever you want ;)
end
```

**Comment by mensfeld** [comment]
In case you would struggle, here's a custom parser with a usage example (not tested but should work, if not - will need a small tunning):

```ruby
class JsonNamespacedParser
  def self.parse(content)
    { 'value' => Karafka::Parsers::Json.parse(content) }
  end

  def self.generate(content)
    Karafka::Parsers::Json.generate(content)
  end
end
```

```
class App < Karafka::App
  setup do |config|
    config.parser = JsonNamespacedParser
  end
end
```

**Comment by ariieh** [comment]
This makes sense, and it seems like it would solve some of the issues, but if we're just overriding the `parse` method, wouldn't the following line still delete `value`, which in the case of an exception being thrown leave us with missing data?

https://github.com/karafka/karafka/blob/1b0bb640d6e21ed9b54efe3dc328a8e78c1be049/lib/karafka/params/dsl.rb#L96

**Comment by mensfeld** [comment]
In case of an exception thrown it would throw an exception and karafka will stop processing :) you can always do it like that:

```ruby
class JsonNamespacedParserWithFallback
  def self.parse(content)
    { 'value' => Karafka::Parsers::Json.parse(content) }
  rescue
    { 'value' => content }
  end

  def self.generate(content)
    Karafka::Parsers::Json.generate(content)
  end
end
```

**Comment by mensfeld** [comment]
also if you would go with the ```params_batch.to_a``` approach it does not parse anything so it does not brake anything as the data is always in the unparsed state.

We had to make some assumptions to make it easily accessable for a typical case and custom parsers are exactly for tacking more complex cases. But as I said: I will reconsider that in the 1.3 release and definitely will try to make things easier for cases like yours (although with custom parsers they are almost not complex at all ;) )

**Comment by ariieh** [comment]
Well, I guess what I'm saying is: in the above custom parser example, `content` is `delete('value')`, correct? In which case it's already missing the raw data. (Unless you parse out `params_batch`)

**Comment by mensfeld** [comment]
Yes and no. If you return a hash with a value and it will merged it back, you get the raw value back. The funny thing is that we used to have this type of behavior in 0.5 but it was problematic as well ;)

**Comment by mensfeld** [comment]
This will delete the original value and restore it, but doing a reassing instead of deleting is a good point. I will check if it can be backported to 1.2.0 :)


```ruby
class JsonNamespacedParserWithFallback
  def self.parse(content)
    { 'value' => Karafka::Parsers::Json.parse(content) }
  rescue
    { 'value' => content }
  end

  def self.generate(content)
    Karafka::Parsers::Json.generate(content)
  end
end
```

**Comment by mensfeld** [comment]
If this answer satisfies you and everything works, please don't forget to close the issue :)

**Comment by ariieh** [comment]
@mensfeld I will be sure to, I haven't had time to test it yet, will get to it today

**Comment by mensfeld** [comment]
Great. Once you tackle this problem please update the status of this issue as I will use it for further development and update of our wiki. Thank you in advance for you contribution.

**Comment by mensfeld** [comment]
@ariieh quick  benchmark shows that it is around 6% slower to parse your data into a temp variable, then delete the value upon success and merge:

```ruby
require 'benchmark/ips'

Benchmark.ips do |x|
  x.config(time: 5, warmup: 2)


  x.report('Delete') do
    hash1 = { 'value' => { 'value' => 1 } }
    hash1.merge!(hash1.delete('value'))
  end

  x.report('Reassign') do
    hash2 = { 'value' => { 'value' => 2} }
    value = hash2['value']
    hash2.delete('value')
    hash2.merge!(value)
  end

  x.compare!
end
```

```
Warming up --------------------------------------
              Delete   102.593k i/100ms
            Reassign   101.149k i/100ms
Calculating -------------------------------------
              Delete      1.305M (± 1.8%) i/s -      6.566M in   5.032722s
            Reassign      1.234M (± 1.7%) i/s -      6.170M in   5.002502s

Comparison:
              Delete:  1305083.2 i/s
            Reassign:  1233758.0 i/s - 1.06x  slower
```

Didn't include parsing ofc. Just the process itself.

**Comment by mensfeld** [comment]
On the other hand - not merging at all and assigning directly gives us at around a 15% boost! This will definitely go into 1.3. Feeling lucky to implement? :)

**Comment by mensfeld** [comment]
```ruby
require 'benchmark/ips'

Benchmark.ips do |x|
  x.config(time: 5, warmup: 2)

  x.report('Delete') do
    hash1 = { 'value' => { 'value' => 1 } }
    hash1.merge!(hash1.delete('value'))
  end

  x.report('Without merge!') do
    hash2 = { 'value' => { 'value' => 2} }
    hash2['value'] = hash2['value']
  end

  x.compare!
end
```

**Comment by mensfeld** [comment]
@ariieh FYI research is done. Won't go with 1.2 as there are already bigger changes there but re-targeted to 1.3.

**Comment by ariieh** [comment]
ok, thanks @mensfeld , I'll wait for 1.3 then to do anything about this

**Comment by ariieh** [comment]
The one thing I might ask is that whenever you are ready to go with this I'd love to look at a PR ;-)

**Comment by mensfeld** [comment]
Sounds great! You'll definitely be notified about a PR to tackle this one!

**Comment by mensfeld** [comment]
Hey @ariieh just wanted to let you know that I've gave it a though during my holiday and your approach with ```params[:value]``` will be the default one from Karafka 1.3 :) Thank you!

**Comment by ariieh** [comment]
awesome, thanks!

**Comment by mensfeld** [comment]
Hey @ariieh just wanted to let you know that it's done: https://github.com/karafka/karafka/pull/336 :)
