### ISSUE TITLE
Provide the ability to pass params to custom parsers

### ISSUE THREAD

**Issue by madejejej** [karafka/karafka#314]
With the experimental version of the Avro parser there's a need to pass a schema name for each topic.

The current suggested approach is to do it the following way:

```ruby
Karafka::Parsers::Avro.schemas_path = 'app/schemas'

App.consumer_groups.draw do
  consumer_group :my_consumer_group do
    topic :my_topic do
      consumer AvroConsumer
      parser Karafka::Parsers::Avro.from_path('schema_name', codec: 'deflate')
    end
  end
end
```

However, that's a bit unhandy. It'd be great to have a nicer option, eg.

```ruby
App.consumer_groups.draw do
  consumer_group :my_consumer_group do
    topic :my_topic do
      consumer AvroConsumer
      parser Karafka::Parsers::Avro, schema_name: 'schema_name', codec: 'deflate'
    end
  end
end
```

or even:

```ruby
# somewhere around the custom parser code:
Karafka.register_parser(Karafka::Parsers::Avro, :avro)

App.consumer_groups.draw do
  consumer_group :my_consumer_group do
    topic :my_topic do
      consumer AvroConsumer
      parser :avro, schema_name: 'schema_name', codec: 'deflate'
    end
  end
end
```

With such a DSL we could also later introduce a JSON parser with dry-struct. The benefits would be:

1. You would have stronger validation code for your Kafka topic schemas

2. You could automatically parse incoming messages into a dry-struct

**Comment by madejejej** [comment]
Another thought. If parser had access to the topic we could use convention over configuration and default the schema name to the topic name.

**Comment by mensfeld** [comment]
Can't we somehow keep parsers and controllers completely isolated? This is how it works now and thanks to that, many things can be tested in isolation. Something like having 1 parser per schema? Or ```schemas/schema_name_schema.rb```, etc?

**Comment by madejejej** [comment]
That's the thing - because they are isolated you have to explicitly pass the schema name.

If we could do it like this:

```ruby
parser Karafka::Parsers::Avro, schema_name: 'schema_name', codec: 'deflate'
```

they would still be isolated. The `parser` macro could pack the additional params into a hash and pass it to the schema's constructor. But it's impossible to provide CoC defaults with this approach

**Comment by mensfeld** [comment]
Yes and no because I could not use just the ```Karafka::Parsers::Avro``` itself and test it in isolation. It will have many cases and require some details.

Can't we instead provide a builder like (idea - not a requirement):

```ruby
MyAvroParserSchemaNameOrWhatever = Karafka::Parsers::Avro.build('schema_name', codec: 'deflate')
```

and then we could just:

```ruby
App.consumer_groups.draw do
  consumer_group :my_consumer_group do
    topic :my_topic do
      consumer AvroConsumer
      parser MyAvroParserSchemaNameOrWhatever
    end
  end
end
```

and it would contain all the details by itself so it could be speced in complete isolatioin?

**Comment by madejejej** [comment]
Well, that's how it works now 😄 

If we enhance the parser macro the tests won't change. You still pass the same arguments down to the parser. We'd just need all parsers to keep the same interface:

```ruby
# this could be another method, eg. build
def initialize(**params); end
```

The question is where we want to keep the complexity. There are always two options and each has pros and cons:

* Karafka clients would have to specify a schema name for every topic - more complex client code, simpler Karafka code
* Karafka provide some nice defaults - more complex Karafka code, simpler client code

**Comment by mensfeld** [comment]
> Well, that's how it works now

Exactly. Isn't that good enough? It provides a complete isolation and does not bound parsers to karafka. I can imagine (and I actually use it that way) that parsers can be shared as a gem and used by some componeents that aren't karafka based.

**Comment by mensfeld** [comment]
@madejejej any update on this one?

**Comment by mensfeld** [comment]
I will close this one. I still don't like breakking the isolation of particular components.
