### ISSUE TITLE
 Persistent offline cache?

### ISSUE THREAD

**Issue by rgaufman** [karafka/karafka#315]
This is more of a question than an issue. If the device is offline for an extended period of time, is there some strategy in karafka to store the messages locally until the connection is restored?What about if the process is killed, is there any way to have a persistent store of these pending messages to be sent when the connection is restored?

**Comment by mensfeld** [comment]
There is no such strategy. You can easily implement something like that usyng waterdrop sync producer. Ping me if you need more info or help with that.

**Comment by rgaufman** [comment]
yes please, I tried googling for "usyng waterdrop sync producer" but there are no results. Any information you can share would be helpful :)

**Comment by mensfeld** [comment]
Please visit: https://github.com/karafka/waterdrop - WaterDrop provides a sync producer that will raise an error in the current thread if it is unable to deliver. You can catch this error and provide a backoff with an additional retry.

**Comment by mensfeld** [comment]
Just keep in mind that it would be much better to do it the other way around. First persist, then deliver. That way you can easily protect your system against `kill -9` BUT it still doesn't cover the case of double delivery.
