### ISSUE TITLE
Manual offset committing doesn't work with custom topic mappers

### ISSUE THREAD

**Issue by dcrodman** [karafka/karafka#317]
I've implemented a pretty simple topic mapper for remapping names to the prefixed versions that Heroku Kafka expects. It's very similar to the example in the wiki, but here's the implementation:
```ruby
class HerokuTopicMapper
  def initialize(prefix)
    @prefix = prefix.end_with?(".") ? prefix.freeze : prefix.freeze + "."
  end

  def incoming(topic)
    topic.to_s.gsub(@prefix, "")
  end

  def outgoing(topic)
    @prefix + topic
  end
end
```
I'm attempting to use manual offset management in a consumer for various reasons, so in my _karafka.rb_ the consumer group definition looks something like this:
```ruby
consumer_groups.draw do
    consumer_group :my_consumer_group do
      automatically_mark_as_consumed false
      topic :sometopic do
        consumer MyConsumer
      end
    end
  end
```
I know this is working since fetching messages always starts from the beginning when karakfa boots up. Now the problem appears in the consumer when I try to mark the message as consumed:

```ruby
def consume
    # some business logic
    mark_as_consumed params if mark_consumed?
end
```

Whenever this method is called, the `mark_as_consumed` call throws `Kafka::UnknownTopicOrPartition` with the following trace:
```Error committing offsets: Kafka::UnknownTopicOrPartition
Exception raised when processing porcupine-20740.listings/4 in offset range 105..105 -- Kafka::OffsetCommitError: Kafka::UnknownTopicOrPartition
/Users/arodman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.5/lib/kafka/consumer_group.rb:91:in `rescue in commit_offsets'
/Users/arodman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.5/lib/kafka/consumer_group.rb:76:in `commit_offsets'
/Users/arodman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.5/lib/kafka/offset_manager.rb:120:in `commit_offsets'
/Users/arodman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.5/lib/kafka/consumer.rb:356:in `commit_offsets'
/Users/arodman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/karafka-1.2.2/lib/karafka/connection/client.rb:83:in `mark_as_consumed'
...
```
A little digging revealed that in this block in `Kafka::ConsumerGroup` (kafka/consumer_group.rb), there's a difference in keys in `response.topics`. With automatic offset committing, the topic keys are prefixed correctly with the topic name. When doing it manually, the topic name appears as the topic name as defined in _karafka.rb_ (i.e. `HerokuTopicMapper.incoming(topic)`).
```ruby
def commit_offsets(offsets)
  response = coordinator.commit_offsets(
      group_id: @group_id,
      member_id: @member_id,
      generation_id: @generation_id,
      offsets: offsets,
      retention_time: @retention_time
  )

  response.topics.each do |topic, partitions|
     partitions.each do |partition, error_code|
        Protocol.handle_error(error_code)
      end
  end
  # ...
```
In the second case, I think the response keys should also be defined with the topic prefix (or more generally the result of applying the mapper function).  Please let me know if there's any additional information I can provide or if I'm just doing something wrong.

**Comment by mensfeld** [comment]
Hey. Thank you for the report. It is really extensive. I will take a more detailed look tomorrow but it indeed looks like an error.

**Comment by mensfeld** [comment]
Jup: error. Expect fix in 24h :)

**Comment by mensfeld** [comment]
@dcrodman this error will also occur for pausing partitions. Fix is being created ;)

**Comment by dcrodman** [comment]
Awesome, I’ll keep an eye out

**Comment by mensfeld** [comment]
Hey @dcrodman just wanted to let you know, that the first part of the fix is already merged and we're working on the second part. Sorry for the delay :(

**Comment by dcrodman** [comment]
No problem @mensfeld, thanks for the quick turnaround!

**Comment by mensfeld** [comment]
Hey @dcrodman. First of all really sorry that it took so long. Could you please try patch from this PR please: https://github.com/karafka/karafka/pull/324

**Comment by mensfeld** [comment]
@dcrodman great :) will merge it once it is reviewed by other team members and shortly after that I will release a new version for you and others affected.

**Comment by dcrodman** [comment]
Hey @mensfeld, any word on when we might be able to expect a stable version release?

**Comment by mensfeld** [comment]
Hey @dcrodman released. It should be available on rubygems in 10-15 minutes. Sorry for the inconvenience!

**Comment by dcrodman** [comment]
Thanks @mensfeld!
