### ISSUE TITLE
How can i setup redis url for Karafka Sidekiq Backend?

### ISSUE THREAD

**Issue by shuiiiiiimu** [karafka/karafka#368]
Run Sidekiq worker using `Karafka Sidekiq Backend`.

but here ara redis url `redis://127.0.0.1:56379/2`

how can i setup redis url in karafka app?

**Comment by mensfeld** [comment]
This is a question related to an optional backend: https://github.com/karafka/sidekiq-backend

Where did you find this description?

You can specify redis url in a sidekiq standard way. That is using sidekiq config:

```ruby
# frozen_string_literal: true

Sidekiq.configure_server do |config|
  config.redis = Settings.redis.to_h
end

Sidekiq.configure_client do |config|
  config.redis = Settings.redis.to_h
end
```

**Comment by mensfeld** [comment]
If this answer satisfies you, please close the issue.

**Comment by shuiiiiiimu** [comment]
look goo to me.
