### ISSUE TITLE
Rails integration issue when consuming message

### ISSUE THREAD

**Issue by rsaphala** [karafka/karafka#372]
I followed everything in the wiki, however when i started my rails app i cannot receive any messages. Nothing is printed in my console. Sending messages is fine though. Any ideas?

I started my consumer app by running `rails s` which starts a rails server

I'm using rails 5.0.6, with jruby 9.1.13.0 - ruby 2.3.3

This is my karafka.rb file content
[karafka.rb](https://gist.github.com/rsaphala/31ad15040eeec3b8a3c2089c43a0aa0e)

My consumer : 
[booking_consumer.rb](https://gist.github.com/rsaphala/bb95291966915db6a953dc85eba558b5)

any ideas?

**Comment by mensfeld** [comment]
Hey @rsaphala, thank you for taking interest in Karafka and sorry for such a late response. Could you tell me how do you run Karafka? I mean wha happens when you run `bundle exec karafka server`

**Comment by rsaphala** [comment]
This is the error that i got when running that command

``
NameError: undefined method `namespace' for class `Object'
  block in (root) at /Users/ronald/.rvm/gems/jruby-9.1.13.0@global/gems/thor-0.20.0/lib/thor/rake_compat.rb:38
    instance_eval at org/jruby/RubyBasicObject.java:1691
           <main> at /Users/ronald/.rvm/gems/jruby-9.1.13.0@global/gems/thor-0.20.0/lib/thor/rake_compat.rb:37
        const_get at org/jruby/RubyModule.java:3288
  block in (root) at /Users/ronald/.rvm/gems/jruby-9.1.13.0/gems/karafka-1.2.4/lib/karafka/cli.rb:1
             map! at org/jruby/RubyArray.java:2518
     cli_commands at /Users/ronald/.rvm/gems/jruby-9.1.13.0/gems/karafka-1.2.4/lib/karafka/cli.rb:28
     cli_commands at /Users/ronald/.rvm/gems/jruby-9.1.13.0/gems/karafka-1.2.4/lib/karafka/cli.rb:27
           <main> at /Users/ronald/.rvm/gems/jruby-9.1.13.0/gems/karafka-1.2.4/lib/karafka/cli.rb:18
             load at org/jruby/RubyKernel.java:973
           <eval> at /Users/ronald/.rvm/gems/jruby-9.1.13.0/gems/karafka-1.2.4/bin/karafka:18
             eval at org/jruby/RubyKernel.java:994
           <main> at /Users/ronald/.rvm/gems/jruby-9.1.13.0/bin/jruby_executable_hooks:15
``

**Comment by mensfeld** [comment]
It sems like a bug. Could you create (or commit) your example app and try out with the MRI ruby? It may be something Ruby specific and I will have to have a way to reproduce it to fix it.

**Comment by mensfeld** [comment]
Closing due to the lack of activity. Please reopen if you are willing to add a debug case as I cannot reproduce it.
