### ISSUE TITLE
Exactly once delivery and transactional messages support

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#387]

**Comment by kowalskey** [comment]
:+1: this is a great feature to have!  Is there any ETA? Thanks in advance!

**Comment by mensfeld** [comment]
@kowalskey hard to say really. We first need to add it to WaterDrop and only then to Karafka. I would say 1-2 months as we're still working on some other improvements for 1.3 release.

**Comment by kowalskey** [comment]
@mensfeld Great, thanks!

**Comment by mensfeld** [comment]
This will have to wait till: https://github.com/karafka/karafka/issues/431

**Comment by mensfeld** [comment]
Closing this one in favour of Karafka 2.0 and https://github.com/karafka/waterdrop/tree/2.0
