### ISSUE TITLE
Allow specifying topics at runtime

### ISSUE THREAD

**Issue by robsoncastilho** [karafka/karafka#396]
In a "Request-Reply" scenario, where a requester sends a message in a channel (topic) and expects a reply message in another channel, the requester may include a "reply-to" address in the message, specifying where the replier should put the message. In this case, we decouple the replier service from all the possible reply topics.

To make this possible, Karafka should allow defining topics at runtime, so that we could make something like `respond_to request_message.reply_to, reply_message` ("reply_to" informs the destination topic name).

**Comment by mensfeld** [comment]
That's a really good example and will be included in the #266.

For now, feel free to use WaterDrop (https://github.com/karafka/waterdrop/) that is included in the Karafka as it works under the hood of responders. With WaterDrop you can send any type of messages to any topic (also defined during runtime).

**Comment by robsoncastilho** [comment]
Thanks, @mensfeld .
I'll take a look at Waterdrop for now.

**Comment by mensfeld** [comment]
It falls out of the scope of responders due to the fact, that runtime topics would break the flow cli command. As stated: please use waterdrop (https://github.com/karafka/waterdrop/) for that.
