### ISSUE TITLE
Validate certs strings format upon entry

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#398]
If there is a way to detect, that the cert string is not valid (missing chars, etc) we should catch it and handle.

**Comment by robsoncastilho** [comment]
Hi, @mensfeld . In our case, the problem was in the linebreak (`\n`) present on the certificate. Our deploy environment was saving the values with an escape char before the `\n`. So the value read by the application had `\\n` characters instead a real linebreak.

**Comment by mensfeld** [comment]
@robsoncastilho thank you. We will make improvements to verify that and have a better error reporting for something like that!

**Comment by mensfeld** [comment]
@robsoncastilho delivered: https://github.com/karafka/karafka/pull/444
