### ISSUE TITLE
Setup config does not accept hash

### ISSUE THREAD

**Issue by lewispb** [karafka/karafka#403]
We currently load our kafka config from a yaml file like this:

```rb
class KarafkaApp < Karafka::App
  setup do |config|
    karafka_config = Rails.application.config_for(:kafka).deep_symbolize_keys

    config.kafka = karafka_config
```

We get an error:

```
NoMethodError:
  undefined method `max_bytes_per_partition' for #<Hash:0x00007ffbf6174ec8>
```

**Comment by mensfeld** [comment]
@GustavoCaso would it be possible to incorporate mass assignment for dry-configurable?

**Comment by mensfeld** [comment]
After giving it a second though and since @GustavoCaso is busy, this is rather the dry-config responsibility.
