### ISSUE TITLE
Enable newer versions of dependencies

### ISSUE THREAD

**Issue by vlatkapavisic** [karafka/karafka#410]
In karafka.gemspec a lot of gem versions are locked which makes karafka hard to integrate. For example, my app's using `dry-validation` version 0.12 while karafka requires it to be 0.11.

**Comment by mensfeld** [comment]
This shouldn't be a problem. I will incorporate it to the next release of 1.2. Sorry for the inconvenience.

**Comment by mensfeld** [comment]
But @vlatkapavisic actually, 'dry-validation', '~> 0.11' should allow. 0.12:

```ruby
    karafka (1.2.6)
      activesupport (>= 4.0)
      dry-configurable (~> 0.7)
      dry-inflector (~> 0.1.1)
      dry-monitor (~> 0.1)
      dry-validation (~> 0.11)
# other things...
    dry-validation (0.12.2)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-core (~> 0.2, >= 0.2.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      dry-types (~> 0.13.1)
```

Could you please provide an example gemfile in which Karafka is causing you problems?

**Comment by vlatkapavisic** [comment]
@mensfeld I don't know if I can share the Gemfile of my company, but here's are the error messages upon adding `gem 'karafka'` and running `bundle install`:

> Bundler could not find compatible versions for gem "dry-validation":
  In snapshot (Gemfile.lock):
    dry-validation (= 0.12.0)

  In Gemfile:
    dry-validation

    karafka was resolved to 0.5.0.3, which depends on
      dry-validation (~> 0.10.6)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "rake":
  In snapshot (Gemfile.lock):
    rake (= 10.5.0)

  In Gemfile:
    karafka was resolved to 1.2.8, which depends on
      rake (>= 11.3)

    scss_lint was resolved to 0.44.0, which depends on
      rake (~> 10.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "sidekiq":
  In snapshot (Gemfile.lock):
    sidekiq (= 5.1.3)

  In Gemfile:
    sidekiq (~> 5.1)

    karafka was resolved to 0.5.0.2, which depends on
      sidekiq (~> 4.2)

I followed this guide https://github.com/karafka/karafka/wiki/Getting-started. As you can see, it's suggesting to downgrade Sidekiq. 

But then I specified the newest version in the gemfile: `gem 'karafka', '1.2.8'` and I had to just do `bundle update scss_lint` and it worked.

**Comment by mensfeld** [comment]
@vlatkapavisic Based on your message it seems you were using a much older version of karafka: `0.5.0.3`. This happened due to the fact, that `scss_lint` was outdated and bundler locked it to satisfy rather `scss_lint` than `karafka`.

If everything works fine, please close the issue.

**Comment by vlatkapavisic** [comment]
Ok, thank you for your time :)
