### ISSUE TITLE
Support for exponential backoff + dead letter queues

### ISSUE THREAD

**Issue by aaronFranssell** [karafka/karafka#413]
Hello,

In my project we are using this excellent gem to start integrating with Kafka.

We are looking into implementing dead letter queues/exponential backoff as described in this article:
https://eng.uber.com/reliable-reprocessing/
In summary, the article suggests creating separate retry topics and a dead letter topic to handle transitory message processing failures.

If we implemented this, we would like to have different polling times for the retry queues (so that we don't immediately retry a failed message). My question is, is this possible? Can we customize how often a consumer polls a given topic for messages?

Thank you!

**Comment by aaronFranssell** [comment]
Thank you, I will try out your suggestions!

**Comment by mensfeld** [comment]
If the answer satisfies you and you end up implementing this with Karafka, please close the issue. If not, please ask and I will do my best to help you.
