### ISSUE TITLE
Subscribe to pattern of topics

### ISSUE THREAD

**Issue by bulutmf** [karafka/karafka#417]
In Karafka, would it be possible to subscribe to regex topic pattern like below:

```Ruby
topic "^customer.*" do
  consumer RecommendationConsumer
  batch_consuming false
end
```

So that `RecommendationConsumer` can receive messages from topics like `customer.a` or `customer.b`.

Kafka-python provides such capability illustrated in [here](https://kafka-python.readthedocs.io/en/master/usage.html), as shown below.

```Python
# Subscribe to a regex topic pattern
consumer = KafkaConsumer()
consumer.subscribe(pattern='^awesome.*')
```

**Comment by mensfeld** [comment]
Not at the moment. We're working (cc @GustavoCaso) on the topic management API that would allow you to fetch cluster details so you could do a semi-automatic matching.

Full implementation of a dynamic regexp / pattern matching is really, really complex, especially when you include topic changes (deletion, partition change, etc).

I'm really interested in the use-case you're having that requires that feature. Would you be willing to share it with me?
