### ISSUE TITLE
Include mutant for the upcoming release

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#418]
@mbj https://github.com/mbj/mutant

**Comment by mensfeld** [comment]
@nijikon could you look into this and incorporate it into the CI flow?

**Comment by mbj** [comment]
@nijikon If you run into blockers, hit me up. Either here or in the mutation testing slack channel you'll find behind the invite bot linked in the mutant readme.

**Comment by mensfeld** [comment]
Mutant is not OSS anymore, thus we need a license as far as I know, right @mbj?

**Comment by mbj** [comment]
@madejejej Yes, and I'll happily make one for you. Can you ping me on DM / mail so I get to it when I do my evening cycle on these inboxes?

Mutant is free to use by OSS projects, these just need a license key.

**Comment by mensfeld** [comment]
Closing as no time prior 2.0. I will re-open once 2.0 is available and will revisit (or once all the things related to 2.0 are done)

**Comment by mbj** [comment]
@mensfeld I'm offended :P (and I hope you know I'm not)

**Comment by mensfeld** [comment]
I know @mbj  :) I will get back to this this year but much much closer to 2.0 or 2.1 :pray:
