### ISSUE TITLE
Drop support for JRuby

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#433]
Due to future migration to `rdkafka-ruby`, there is no point in investing time into `jruby` maintenance. Please drop if from all the gems that we have in the Karafka organization and update the CI.

**Comment by thijsc** [comment]
Actually rdkafka should support jRuby since it uses `ffi`. It would make more sense to use a Java based client though I guess.

**Comment by mensfeld** [comment]
It would :) I may try playing with it in future releases but for now I don't want to add extra overhead on switching and maintaining all of it for an area in which I don't operate in this context. I am however open to bringing it back upon finding a maintainer that would have cases over which we could test and develop it out.
