### ISSUE TITLE
Code Example for Single Constant Consumer as Proxy

### ISSUE THREAD

**Issue by bparanj** [karafka/karafka#439]
It seems like the name of the consumer class is tied to the topic by specifying the topic ahead of time. Is there any flexibility on what topic a certain consumer can consume from during runtime?

> No but you can use a single "constant" consumer to act as a proxy and pass it wherever you want.

Do you have any code sample illustrating this technique?

**Comment by mensfeld** [comment]
Hey,
First of all, sorry for such a late response. Xmass :)

What I meant there is that you could just use consumer to proxy code into running your logic that is context aware.

For example (based on Karafka `1.2.9`) assuming your consumer has some internal data that can be used to route the flow:

```ruby
# frozen_string_literal: true

class DataConsumer < ApplicationConsumer
  def consume
    params_batch.each do |params|
      case params[:type]
      when 'users'
        User.import!(params[:user])
      when 'events'
        User.import!(params[:events])
      else
        raise RuntimeError, 'Invalid type'
      end
    end
  end
end
```

There is no option to "dynamically" route consumers as there are too many cases, especially if you include batch and non batch consuming, different data types, parsers, etc. It is much better to route within Karafka consumer to yout appropriate logic.

Although in `1.3` release that is coming soon, you will be able to use same consumer class for multiple topics consumption.
