### ISSUE TITLE
ProcessingError pauses consumer indefinetely (even with pause_timeout being set up)

### ISSUE THREAD

**Issue by yashke** [karafka/karafka#446]
Karafka version: 1.2.9
ruby-kafka version: 0.7.4

I discovered this error while working with a bug caused by flaky Redis connection, with Sidekiq as a backend. So reproducing steps will assume Redis server availability and Sidekiq as a backend, but probably bug affects other use-cases as well.

Steps to reproduce:
1. Make sure Redis server is running
2. Run karafka server with at least one consumer and worker (and Sidekiq as backend)
3. Turn off Redis server
4. Send message to subscribed topic.
5. Wait few seconds
6. Turn on Redis server

Expected behavior: another attempt to consume message from the topic (after `reset_timeout`).
Actual behavior: nothing happens, no other messages are consumed by the consumer

It looks like it's ruby-kafka's bug, as it seems to fail to resume paused consumption - I didn't dig to deep to find the root cause though.

Ps. It seems like Karafka is changing Kafka's client, so it may be resolved this way.

**Comment by mensfeld** [comment]
Hey @yashke thank you for reporting this issue. Could you try with ruby-kafka `0.7.2` or `0.7.5.beta1`?

**Comment by yashke** [comment]
Oh, wow, both seems to work actually. So it seems only `0.7.4` is affected (not sure about 0.7.3). I also checked older version of karafka (0.2.4) and ruby-kafka (0.6.8), as one of my apps uses it and it also seems not to be affected.

**Comment by mensfeld** [comment]
Yes. It seems to be a bug in this particular kafka version. I would recommend sticking with `0.7.2` for now ;). Please close if that resolved your problem.

**Comment by yashke** [comment]
Closing then. Thanks!
