### ISSUE TITLE
Make consumer testing a bit easier

### ISSUE THREAD

**Issue by hammerdr** [karafka/karafka#448]
The idea is to have these be similar to controller tests, so it would end up looking something like

```
it 'should do stuff' do
  publish :some_event, { a: 1 }
  expect(Karafka.logger).to receive(:info)
end
```

We could execute the routing (or not), but the idea here being that consumers should parallel controllers in Rails (they should also be really thin and the real work done in a model or service layer).

**Comment by mensfeld** [comment]
Hey @hammerdr does API like that satisfy you:

```ruby
RSpec.describe InlineBatchConsumer do
  subject(:consumer) { karafka_consumer_for(:inline_batch_data) }

  before do
    publish({ 'number' => nr1_value }.to_json)
    publish({ 'number' => nr2_value }.to_json)
  end

  it 'whatever' do
    consumer.consume
  end
```

**Comment by mensfeld** [comment]
Closing due to: https://github.com/karafka/testing
