### ISSUE TITLE
Make pry-byebug debugging tool breakpoint working correctly

### ISSUE THREAD

**Issue by dawlib** [karafka/karafka#457]
For some reason, while using `pry-byebug` breakpoint (`binding.pry`), Karafka keeps printing information from different threads on the standard output. There is a need to fix that, so it will behave the same way as while using `byebug`. You can simply reproduce that by putting a breakpoint (`binding.pry`) in any place in the code that is running by Karafka and see what happens.

**Comment by mensfeld** [comment]
Rejecting. It's a pry-byubug problem not Karafka. Karafka is multi threaded thus, the break won't stop other threads from producing to IO.

**Comment by Mehonoshin** [comment]
Makes sense, but anyway it is quite inconvenient that it's not possible to debug Karafka apps with pry.

**Comment by mensfeld** [comment]
@Mehonoshin that is true however I do not personally use it and I don't have enough knowledge to figure out how to "mute" certain things and keep the console at the foreground. I would be willing to work on that one though, if I would get help from someone more experienced with pry.
