### ISSUE TITLE
Provide threaded / ractor backend per single topic partition

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#458]
I'm currently working on a multithreaded framework for batching and enqueueing data into a background ruby thread. This could be used to leverage the Karafka framework and provide multi threaded flow with having a single consumer group.

**Comment by ttanay** [comment]
Hey @mensfeld 
I'd like to help with this if needed :)

**Comment by mensfeld** [comment]
hey @ttanay. Thank you for the offer. While the card is really old, the concept is already a WIP on my laptop. We're switching to librdkafka and part of the switch is to provide ActiveJob backend as well as threaded backend for Karafka. I will ping you once I have something more advanced so we can co-op on that!

**Comment by ttanay** [comment]
Oh cool!
Is there any other issue I can work on to get started in the meantime?

**Comment by mensfeld** [comment]
TBH not really :) the current `1.x` is stable without any further development and the `2.0` work is an extreme WIP that is not ready to be exposed.

One thing that I would love to have someone onboarded to is the new `2.0` WaterDrop architecture: https://github.com/karafka/waterdrop/pull/106 :) someone else understanding that would definitely be helpful for the upcoming Karafka 2.0 work.

**Comment by ttanay** [comment]
Thanks! I'll go through it and let you know if I have any questions :)

**Comment by mensfeld** [comment]
Closing. 2.0-wip has it
