### ISSUE TITLE
Decouple responder "parser" (generator?) from topic.parser

### ISSUE THREAD

**Issue by benissimo** [karafka/karafka#460]
Add an option to override the (built-in, currently hard-coded) logic that assumes a responder uses the same "parser" as the consumer. (That was already a questionable assumption even if you're just dealing with JSON and XML. With Avro, hard-coding a parser won't work as the responder typically writes to a different topic, and even if consumer and responder topics both use Avro, it's unlikely they use the same schema.)

Add support for the following cases:

1)
Consumer uses one parser, responder uses another (consumer parses JSON, responder generates XML, etc.). Allow a consumer to specify its own default format.

2)
Responder generates messages with different formats depending on the topic it responds to.
A single responder can respond to multiple topics. They might not all share the same format. So allow `respond_to` to pass in an optional parser.

**Comment by mensfeld** [comment]
I again agree it was a bad assumption on our (primarily mine) side.

**Comment by mensfeld** [comment]
@benissimo would you mind looking at this as well? https://github.com/karafka/karafka/pull/464 once this is merged, I will close this issue. Thank you for your help! This is a really good change that makes things much cleaner!

**Comment by mensfeld** [comment]
Thank you for your contribution! The idea of splitting that was awesome and the more I think about it, the more the previous approach feels bad!
