### ISSUE TITLE
Update responder configuration documentation

### ISSUE THREAD

**Issue by diogoleitao** [karafka/karafka#476]
There is no documentation regarding `multiple_usage` on the responders.
I discovered that I could use this parameter to send multiple messages from the same responder, but I don't know if this is the only use case or if this is an accurate interpretation of what `multiple_usage` does.

While `respond`ing to a message from the corresponding consumer, `validate_usage!` threw the following error:
```
E, [2019-03-13T16:24:54.646492 #89424] ERROR -- : Exception raised when processing HISTORICAL_DATA/0 in offset range 17..17 -- Karafka::Errors::InvalidResponderUsage: {:multiple_usage_permission=>["must be true", "must be true"], :multiple_usage_block=>["must be less than or equal to 1", "must be less than or equal to 1"]}
```
Message duplication aside, there's not documentation regarding this part of the responders' configuration.

**Comment by mensfeld** [comment]
Hey. There are no docs in `1.3`. There are docs for `1.2`: https://github.com/karafka/wiki/blob/1.2/Responders.md#registering-topics

Sorry for the confusion. We're preparing the `1.3` release.

**Comment by diogoleitao** [comment]
@mensfeld thanks for letting me know!

**Comment by mensfeld** [comment]
Sorry for such a late response and confusion around that.
