### ISSUE TITLE
Rspec using development environment instead of test when testing with karafka

### ISSUE THREAD

**Issue by mnj93** [karafka/karafka#489]
I was trying to test karafka responder in rails app by following testing guide provided in [https://github.com/karafka/karafka/wiki/Testing#responders](url) and when i ran the tests then it was using development environment instead of test environment.
I added following code in `spec/spec_helper.rb` file :

```
require './karafka.rb'

# Don't send messages in the test env
WaterDrop.setup do |config|
  config.deliver = false
end
```
When i printed value of `ENV["RAILS_ENV"]` in rails console while running tests then it printed `development` instead of `test`

I was able to solve this issue by moving `ENV['RAILS_ENV'] ||= 'test'` this line from `spec/rails_helper.rb` to `spec/spec_helper.rb`.

But it should work without moving that code as everything was working fine before requiring `karafka.rb` in `spec/spec_helper.rb`.

**Comment by mensfeld** [comment]
Sorry for the delay. This description refers to running a **standalone** Karafka without Rails. I've fixed the description and provided a rails case as well: https://github.com/karafka/karafka/wiki/Testing

Works for me and prints proper env details. Feel free to ping me if that doesn't fix the problem.
