### ISSUE TITLE
ssl_verify_hostname sync

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#506]
https://github.com/zendesk/ruby-kafka/pull/733/files

**Comment by chaadow** [comment]
Hi, can you release this sync in an upcoming release. is it safe to use the master branch? thx

**Comment by mensfeld** [comment]
Yes. It's in 1.3. It is safe to use master. It is yet unreleased as I'm fighting with Rails autoload + Zeitwerk + karafka development code reload + dry auto inject reload (complex)

**Comment by chaadow** [comment]
@mensfeld Could you please update Waterdrop, My async producer crashes, because it's missing this option in the [config file](https://github.com/karafka/waterdrop/blob/master/lib/water_drop/config.rb). ( i'm bundle opening the gem as i'm writing this, i'll keep you updated if it actually fixes)

**Comment by mensfeld** [comment]
@chaadow can you create an issue in waterdrop? Please describe the problem and please describe the target version.

**Comment by chaadow** [comment]
Sure @mensfeld I found the issue and solved it. I'll explain it further in waterdrop
