### ISSUE TITLE
bundle update karafka on master branch

### ISSUE THREAD

**Issue by lewispb** [karafka/karafka#516]
I was just going to try out master, but get the following error when `bundle`ing:

```Resolving dependencies.......
Bundler could not find compatible versions for gem "waterdrop":
  In Gemfile:
    karafka was resolved to 1.3.0, which depends on
      waterdrop (~> 1.3)

Could not find gem 'waterdrop (~> 1.3)', which is required by gem 'karafka', in any of the sources.```

**Comment by lewispb** [comment]
Pointing waterdrop to github master fixes this.

**Comment by mensfeld** [comment]
Yup. We cannot lock karafka to point to waterdrop master, unfortunately. The release is closer and closer, so we will have to live with that for now.

**Comment by lewispb** [comment]
Thanks @mensfeld
