### ISSUE TITLE
undefined method `parser'

### ISSUE THREAD

**Issue by lewispb** [karafka/karafka#517]
Testing out master, I see this error:

```
NoMethodError:
  undefined method `parser' for #<Karafka::Routing::Proxy:0x00007f8f679cb758>
```

Example route:

```rb
    topic "my_avro_topic" do
      start_from_beginning false
      batch_consuming true
      consumer MyConsumer
      parser Karafka::Parsers::Avro.from_registry
    end
```

**Comment by mensfeld** [comment]
https://github.com/karafka/karafka/issues/463
https://github.com/karafka/karafka/pull/464

:)

Sorry. Will include this in the changelog. Rename `parser` to `deserializer` and all should work.

**Comment by lewispb** [comment]
Great thanks @mensfeld

**Comment by mensfeld** [comment]
Please close the issue if that helps. I dunno why I didn't include this in the upgrade article 0_o, will fix that soon. ref https://github.com/karafka/karafka/issues/519

**Comment by mensfeld** [comment]
Works for me. Closing.
