### ISSUE TITLE
Add a health check signal support (TTIN)

### ISSUE THREAD

**Issue by diogoleitao** [karafka/karafka#527]
In order to query the app's status, instead of subscribing to the app's events and storing or sending them, an endpoint like `/health.json` could provide a simple JSON with the app's status, reason (in case of error) and some other useful information.

**Comment by mensfeld** [comment]
Just to clarify: we can add a SIGTTIN to print the backtrace. By any means we won't add anything http related to Karafka.

**Comment by mensfeld** [comment]
Closing this now since 2.0 has a statistics callback that periodically can send statistical data.
