### ISSUE TITLE
Consumer not working after having the error Kafka::NotCoordinatorForGroup

### ISSUE THREAD

**Issue by anhtuanluu36** [karafka/karafka#529]
I'm using Karafka 1.2.8 and I have an issue:
- The Consumer stop after having the error Kafka::NotCoordinatorForGroup.

**Comment by mensfeld** [comment]
Please provide more details. Topics structure, kafka version, ruby-kafka version, ruby version, etc. Ideally a script for reproduction.

**Comment by nijikon** [comment]
Stale, lack of feedback.
