### ISSUE TITLE
Deciding on karafka process count

### ISSUE THREAD

**Issue by icecold21** [karafka/karafka#537]
hi @mensfeld, thanks for Karafka, Great software btw!

My question is: it is very common in Kafka to have a big number of partitions, say 500, for a particular topic. does it means to have all these topic consumed in a truly parallel manner, it is better to spawn 500 processes of Karafka server? since every Karafka process will only have one thread to process a specific topic? 

or

We can have more than 2 threads to process 2 partitions of a topic in a single process.
To clarify the question.

If we have 2 partitions, and 1 single Karafka process, how many thread will be running dedicatedly to run business logic on this 2 partitions?

Thanks before.

**Comment by mensfeld** [comment]
Hey @icecold21 

>  thanks for Karafka, Great software btw!

You are welcome. Just you wait for 2.0 that we're working on :)

> since every Karafka process will only have one thread to process a specific topic?

There is a hidden feature of Karafka for that ;)

>  If we have 2 partitions, and 1 single Karafka process, how many threads will be running dedicatedly to run business logic on this 2 partitions?

By default 1. This is how ruby-kafka is designed BUT we are working on version 2.0 that won't have this limitation.

There are however several ways to bypass that ;) (actually only two :( ):

- write your own concurrent backend, similar to how `sidekiq-backend` is done (the hard way)
- Screw the one below and just multiply the consumer group definition like so:

```ruby
  consumer_groups.draw do
    3.times do
      consumer_group :events do
        topic 'analyzed_events' do
          consumer RequestsConsumer
        end
      end
    end
  end
```

This code will operate within 3 threads (actually 4, as there is one that is a coordinator), running them concurrently. However, each of them will have its own Kafka connection (that should not be a problem, I run it like that). The only thing you need to keep in mind is fine-tuning the settings not to have extensive memory usage.

**Comment by mensfeld** [comment]
I'm closing as I don't see any activity here.

**Comment by ferydjzz** [comment]
I am interested in this workaround @mensfeld 
```ruby
  consumer_groups.draw do
    3.times do
      consumer_group :events do
        topic 'analyzed_events' do
          consumer RequestsConsumer
        end
      end
    end
  end
```
But I have a concern about the ordering guarantee, is there a possibility these 3 threads process the same partition with the same partition key?

Thanks.

**Comment by mensfeld** [comment]
> But I have a concern about the ordering guarantee, is there a possibility these 3 threads process the same partition with the same partition key?

Never.

**Comment by ferydjzz** [comment]
Thanks for the clarification @mensfeld
