### ISSUE TITLE
Karafka-rails consumer setup (with docker)

### ISSUE THREAD

**Issue by ArtemAlagizov** [karafka/karafka#541]
hello,

i have a problem with consuming messages from a topic (posting messages works fine).
i have set up a simple project to demonstrate: https://github.com/ArtemAlagizov/rails-karafka-docker (there is a README that tells how to run it and the karafka setup).
basically, i have a responder that posts a message to a topic and a consumer that is supposed to consume messages from this topic (topic name is **:jobs**).
there is an endpoint **/perform** where POST request can be sent to trigger responder to post a message to the topic.

if anybody could point me out what i am doing wrong - that would be highly appreciated!

**Comment by mensfeld** [comment]
I can give it a shot

**Comment by mensfeld** [comment]
Unless I don't understand something or your docker setup does not include `bundle exec karafka server` command. No consumption will happen without it...

**Comment by ArtemAlagizov** [comment]
hi @mensfeld, thanks man!
achieved it through 
`command: bash -c "bundle exec karafka server --daemon && bundle exec rails s -p 80 -b '0.0.0.0'"`
i can see in the logs that the message is consumed.

any idea on how to handle the following situation:

- i have websocket connection from my rails server to the browser
- when karafka server consumes a message - i want to broadcast this message from my rails server to the browser.

i can send a POST request from karafka server to rails server with the message and then broadcast it from rails server to the browser.
do you see any less mental way of of doing it?

**Comment by ArtemAlagizov** [comment]
closing the issue, though, as it is resolved

**Comment by mensfeld** [comment]
> when karafka server consumes a message - i want to broadcast this message from my rails server to the browser.

If you use actioncable, there is no problem. You can easily push it.
