### ISSUE TITLE
Multiple instances of Karafka apps

### ISSUE THREAD

**Issue by ka8725** [karafka/karafka#546]
Consider a modular monolithic app. For each of the modules we would like to have its own Karafka app instance. Naturally, the following code shows up:

```ruby
class App1 < Karafka::App
    # ...
    consumer_groups.draw do
      consumer_group :events do
        topic :topic1 do
           # ...
        end
      end
    end
end

class App2 < Karafka::App
    # ...
    consumer_groups.draw do
      consumer_group :events do
        topic :topic2 do
           # ...
        end
      end
    end
end
```
Then two boot files are created and the idea is to run:

```shell
$ KARAFKA_BOOT_FILE=app1.rb karafka server
$ KARAFKA_BOOT_FILE=app2.rb karafka server
```

Unfortunately this doesn't work, because app1 and app2 share the same config. What means that consuming topics are the same for the both apps:

```ruby
App1.consumer_groups.first.topics.map(&:id) # => ["topic1"]
App2.consumer_groups.first.topics.map(&:id) # => ["topic1"]
```

That brings to the conclusion that multiple instances for Karafka in a monolithic app is not possible.

Although, it could be possible with some code modification: the config instance could be moved from the global state to per App instance.

**Comment by mensfeld** [comment]
Yes. It sucks ;) I'm already working on `2.0`. Please see: https://github.com/karafka/waterdrop/pull/106 - that is the producer part. Consumer part is ongoing.

Also, there is a trick you can use. You can have multiple consumer groups within a single Karafka app and you can run processes with particular consumer groups running. This should allow you to achieve something like "multi app" awareness. 

Really sorry for the inconvenience. We're working hard on providing 2.0 that is:

a) instantiable
b) manageable within a single VM
c) will allow to run several apps within a single VM
d) multi-threaded

But it will take few more months to get it done.

**Comment by mensfeld** [comment]
Closing in favour of https://github.com/karafka/karafka/issues/431
