### ISSUE TITLE
uninitialized constant WaterDrop::Contracts::MessageOptions (NameError)

### ISSUE THREAD

**Issue by jainanda-k** [karafka/karafka#552]
Encountering the following error when trying to run the rails server.
uninitialized constant WaterDrop::Contracts::MessageOptions (NameError)

Note: Karafka server runs fine and messages are consumed successfully.

Karafka version: 1.3.0
Ruby version: 2.5.3
Ruby-kafka version: 0.7.10
Application client id: my_app
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /home/*****/my_application/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://localhost:9092"]

**Comment by mensfeld** [comment]
What waterdrop version are you using? Can you create a small repro script?

**Comment by jainanda-k** [comment]
> What waterdrop version are you using? Can you create a small repro script?

I did not manually install Waterdrop. It got installed with karafka.
Anyway the issue was with version mismatch of Rails and karafka. This issue is there in Rails 5 and Karafka 1.3. It got solved once I downgraded my Karafka version to 1.2.12. 
Similarly, Karafka 1.3 works fine with Rails 6.

**Comment by mensfeld** [comment]
I would still want to fix it for Rails 5 and Karafka 1.3. Could you create an example repro repo?

**Comment by shekhar098** [comment]
mark_as_consumed! method is not available in 1.2.12. Is there another method similar to this?

**Comment by mensfeld** [comment]
@shekhar098 `#mark_as_consumed`?

**Comment by mensfeld** [comment]
I see you're satisfied with the answer. Closing :)

**Comment by ojab** [comment]
It's bootsnap issue with ruby-2.5 and iseq compile cache enabled (at least it was in my case). 
See https://github.com/Shopify/bootsnap/pull/257.
