### ISSUE TITLE
Ability to validate successful responder call

### ISSUE THREAD

**Issue by nickoliver86** [karafka/karafka#556]
## Is your feature request related to a problem? Please describe.

I want the ability to confirm that a message was successfully produced to the topic on the broker. I don't care or want to rely on an acknowledgement from a downstream consumer. I simply wish to know if I successfully posted in the first place with some sort of return value or callback. It looks like neither responders nor WaterDrop::SyncProducer provide return values to validate the successful delivery of your message to the topic.

## Describe the solution you'd like

Consider the scenario where perhaps the topic does not exist or there's an ACL error, etc. 

**Topic does not exist:**
```
irb(main):001:0> WaterDrop::SyncProducer.call({'test' => 'test'}.to_json, topic: 'not.a.real.topic')
I, [2019-11-21T17:05:45.387698 #2436]  INFO -- : New topics added to target list: not.a.real.topic
I, [2019-11-21T17:05:45.388066 #2436]  INFO -- : Fetching cluster metadata from kafka://broker.kafka:9093
I, [2019-11-21T17:05:51.377430 #2436]  INFO -- : Discovered cluster metadata; nodes: broker2.kafka:9093 (node_id=218), broker3.kafka:9093 (node_id=254), broker1.kafka:9093 (node_id=175)
E, [2019-11-21T17:05:51.378117 #2436] ERROR -- : Failed to assign partitions to 1 messages in not.a.real.topic
W, [2019-11-21T17:05:51.378265 #2436]  WARN -- : Failed to send all messages to ; attempting retry 1 of 2 after 1s
I, [2019-11-21T17:05:52.380422 #2436]  INFO -- : Fetching cluster metadata from kafka://broker.kafka:9093
I, [2019-11-21T17:05:52.692198 #2436]  INFO -- : Discovered cluster metadata; nodes: broker3.kafka:9093 (node_id=254), broker2.kafka:9093 (node_id=218), broker1.kafka:9093 (node_id=175)
I, [2019-11-21T17:05:52.692766 #2436]  INFO -- : Sending 1 messages to broker1.kafka:9093 (node_id=175)
=> nil
```
We can see above that ruby kafka logs out some useful information denoting that the message fails to send. But functionality which should behave one way or another based on _if_ the message successfully sent, has no way to rollback if this is the case. Ideally I'd want something to the effect of: 

```
ActiveRecord::Base.transaction do
  # modify some local data

  # notify downstream services of this change
  responder_call = Responders::MyCoolResponder.call(message)
  
  # rollback i.e. do not commit local changes if unable to publish message for downstream 
  consumption
  raise ActiveRecord::Rollback unless responder_call.successful?
end
```

## Describe alternatives you've considered

I could in theory convert this to a fully async process which then waits for the consuming service to publish an acknowledgement message to a topic I consume from. But in a workflow like this I don't actually care or need to take action based on the downstream systems receiving it. I simply wish to know that I posted the original message to a topic for their consumption. The current error handling for responders as I understand it protects against responding to a topic which has not been registered or total broker failures but not whether or not you can successfully produce a message in an `acks=all` model.

**Comment by mensfeld** [comment]
This functionality is already implemented in Waterdrop 2.0: https://github.com/karafka/waterdrop/tree/2.0

Waterdrop 2.0 supports promises:

```ruby
producer = WaterDrop::Producer.new

producer.setup do |config|
  config.kafka = { 'bootstrap.servers': 'localhost:9092' }
end

promise = producer.produce_sync(topic: 'my-topic', payload: 'my message')
result = promise.wait
result.partition #=> 0
result.offset #=> 2065
result.error #=> nil

promise = producer.produce_sync(topic: 'invalid-topic', payload: 'my message')
# On the wait you might as well get a timeout error if the delivery takes a lot of time
result = promise.wait
result.partition #=> 2
result.offset #=> 100
# This is not yet merged to rdkafka due to some internals problems with CI that we're trying to fix
result.error #=> "Some sort of error from librdkafka"
```
