### ISSUE TITLE
Batch processing performance requirements

### ISSUE THREAD

**Issue by paneq** [karafka/karafka#573]
👋 

It's neither bug nor feature request. It's a few questions, which I could not find documented anywhere.

* Assuming `batch_fetching: true` and the fact that the [offset is commited after you're done consuming all messages from a batch](https://github.com/karafka/karafka/wiki/Manual-offset-management-(checkpointing) )
* What is the max amount of messages that will be received? Is that configured by `max_bytes_per_partition` (and avg msg size) or `fetcher_max_queue_size` or something else completely?
* Is there a maximum amount of time which can be spent processing a single batch, maybe `session_timeout`?

    https://github.com/zendesk/ruby-kafka/issues/561#issuecomment-392596630 suggests there might be, but maybe the fact that we send heartbeats offsets the problem, does it? I don't know if heartbeats are sent from a separate background thread or not.

    I am asking because in some situations we started seeing `Error committing offsets: Kafka::UnknownMemberId` 

Thank you for maintaining the project and the support.

**Comment by mensfeld** [comment]
:wave: 
First of all sorry for the delay. I had family matters that I had to take this week.

> What is the max amount of messages that will be received?

It is configured by both actually. So to answer that, you need to understand how data fetching works (from Kafka): we fetch data in batches, each batch contains data of a single partition of a single topic (that is gonna change in Karafka 2.0). This means, that the `max_bytes_per_partition` describes how much data we can request for a given partition of a given topic. 

`fetcher_max_queue_size` describes how many batches of a `max_bytes_per_partition` bytes size can we accumulate upfront (buffer). It's set to `10` by default in Karafka as bigger value (as a default) tends to create OOM exceptions for places like smaller AWS instances.

So to answer your question again:

>  What is the max amount of messages that will be received?

In a single fetch: `max_bytes_per_partition`, while you're doing other things (like processing): `max_bytes_per_partition` * `fetcher_max_queue_size`.

> Is there a maximum amount of time which can be spent processing a single batch

Yes. You should not exceed the `session_timeout` in general BUT if you have a `heartbeat_interval` that is less than the `session_timeout` AND no other things are happening in the fetcher thread (fetching a HUGE amount of data that would take longer than the `session_timeout`) you should be fine. 

>  I don't know if heartbeats are sent from a separate background thread or not.

They aren't. They have priority over the fetching process BUT if the fetching is in progress, then no other commands are processed, thus if you fetch (theoretically) 100GB over internet, that will always kick you out of the consumer group.

> I am asking because in some situations we started seeing Error committing offsets: `Kafka::UnknownMemberId`

That suggests that you're being kicked out. Either fetch smaller batches, increase the session timeout or commit the offset more frequently.

FYI: this issue will be completely gone in Karafka 2.0 that we will release in Q3 max.

**Comment by paneq** [comment]
Thank you for the explanation and especially for the suggestions. It somehow clarifies the situation but I am still not exactly certain that I have good internal representation of how Karafka works internally and thus where the issue came from.

This is how I imagine it. Please correct where assumptions are wrong.

* We have a fetcher thread (one or many, I don't know) which fetches the data as quickly as it can. So with `max_bytes_per_partition` being set to say `1MB` and `fetcher_max_queue_size` being `10`, it can fetch up to 10MB and then it waits for at least one batch to be finished before it can resume fetching. That batch is around 1MB of messages when we are lagging a lot.
* The fetcher process is also responsible for sending heartbeats.
* When the consumer is lagging a lot (i.e. it is a new app with a completely new consumer group which just joined and is processing from the beginning) the fetcher process will be stuck waiting for the whole batch to process. Once the batch is processed, the fetcher will check out how much time passed and if sufficiently enough then it will send a heartbeat. In the meantime nothing sends the heartbeat.
* And that's the reason why we are being kicked out. Kafka does not know we are processing our messages.

> AND no other things are happening in the fetcher thread

This part is not clear. What is happening in the fetcher thread when the queue (`fetcher_max_queue_size`) is full? Maybe the answer is "nothing" which suggests we should be good, but that's not what we observe. Maybe the answer is that it is "actively waiting for something" (i.e. batch to be finished) which would suggest something is happening and that's why it does not send a heartbeat and thus we observe our problems.

Regarding your proposed solutions:
* fetch smaller batches - I understand by setting `max_bytes_per_partition`. Then batches are smaller and we still need to finish our batch before `session_timeout`
* increase the session timeout - batch size remains the same but we have more seconds to finish processing.
* commit the offset more frequently - For that I think there are two possibilities:
  * Set `batch_fetching` to `false` - which would mean fetching and processing messages one by one
  * or set `automatically_mark_as_consumed` to `false` and implement manual offset management as documented.

Again, thank you for your time. I just want to make sure I understand how Karafka works internally to make sure I have a good understanding what triggered those problems so that we can avoid it in the future by providing better guidelines to our developers.

**Comment by paneq** [comment]
> FYI: this issue will be completely gone in Karafka 2.0 that we will release in Q3 max.

Is the architecture going to be different? Here is something I had in mind:

```
queue = Queue.new

consumer = Thread.new do
  loop do
    process_message
    queue << "processed"
  end
end

fetcher = Thread.new do
  loop do
    fetch_messages_if_any # timeout must be less than heartbeat_interval
    queue << "fetched"
  end
end

heartbeater = Thread.new do
  last_beat = Time.now - heartbeat_interval
  loop do
    queue.pop
    queue.clear
    time_passed = Time.now - last_beat
    diff = heartbeat_interval - time_passed
    if diff > 0
      sleep(heartbeat_interval)
    end
    send_heartbeat
    last_beat = Time.now
  end
end
```

This is just _an idea_ (and the pseudo code certainly has bugs) that I had in mind with the intent to send heartbeats only when the consuming (and/or fetching) seems to be working properly and processing messages.

**Comment by mensfeld** [comment]
> Is the architecture going to be different? Here is something I had in mind:

In librdkafkaa dedicated connection to the group coordinator is used for consumer joins, heartbeats, etc.

This means you won't have to do anything to keep processing data for as long as you want ;)

In general, the user API should not change a lot and any changes that will be required will be covered (as always) by an extensive migration guide.

**Comment by mensfeld** [comment]
@paneq is the answer sufficient enough? If so, please close the card :) I will then make docs out of that.

**Comment by paneq** [comment]
@mensfeld If you could comment on https://github.com/karafka/karafka/issues/573#issuecomment-583338539 or point me to the right parts of the code so that I have an understanding how things work right now and where the issues come from that would be great.

If you don't have a moment for that, please close :)

**Comment by mensfeld** [comment]
@paneq sorry. I've misread the comments :man_facepalming: 

> We have a fetcher thread (one or many, I don't know)
That is up to you :) (if you have more than 1 cons group defined then you have more than 1 fetcher thread)

> with `max_bytes_per_partition` being set to say 1MB and `fetcher_max_queue_size` being 10, it can fetch up to 10MB and then it waits for at least one batch to be finished

Yes. Fetcher technically speaking has 2 queues. One for commands and one for data but the settings refer to the data queue and the commands one is not configurable. If all the slots are full, no new data is being fetched but the commands are being processed.

> The fetcher process is also responsible for sending heartbeats.

I made a mistake here. Really sorry about that. The answer is **NO**. Heartbeat is being sent from the main thread and it was my mistake. I have code that does in a separate thread but this is not a default behavior of Karafka.

ref: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/heartbeat.rb#L16
ref: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer_group.rb#L108
ref: https://github.com/zendesk/ruby-kafka/blob/90fb527a3251ed1add2a0f755af5dbe886700ed9/lib/kafka/broker.rb#L113

There is also a non-blocking heart beating that will just trigger a heartbeat if needed (but it does not impact the explanation).

> When the consumer is lagging a lot (i.e. it is a new app with a completely new consumer group which just joined and is processing from the beginning) the fetcher process will be stuck waiting for the whole batch to process. Once the batch is processed, the fetcher will check out how much time passed and if sufficiently enough then it will send a heartbeat. In the meantime nothing sends the heartbeat.
And that's the reason why we are being kicked out. Kafka does not know we are processing our messages.

Your explanation is correct. Kafka is unaware as while you process data, heartbeating does not happen. Fetcher commands irrelevant to fetching will still happen but there will be no heartbeating. Kafka will kick you out of the group. Decreasing the batches size would help as the processing would be faster.

What I can recommend here is using Karafka `#trigger_heartbeat` while you're processing as it does not cause any delays when triggering is not needed.

> This part is not clear. What is happening in the fetcher thread when the queue 

Fetcher handles commands but not fetching new data (note again: heartbeat is not a fetcher command).

> that's why it does not send a heartbeat and thus we observe our problems.

Karafka (as well as ruby-kafka) sends hearbeat **after** processing each batch. Use `#trigger_heartbeat` periodically (after N messages within a batch, etc) if you process things from a single batch for a long period of time.

> fetch smaller batches - I understand by setting max_bytes_per_partition. Then batches are smaller and we still need to finish our batch before session_timeout
Yes.

> increase the session timeout - batch size remains the same but we have more seconds to finish processing.
Yes.

>commit the offset more frequently - For that I think there are two possibilities:
        Set batch_fetching to false - which would mean fetching and processing messages one by one
        or set automatically_mark_as_consumed to false and implement manual offset management as documented.

You can trigger heartbeat without doing manual offset management.

Reading all of that again, I would suggest you triggering the heartbeat within the time of the processing of the batch (as long as doable). If you have a really, really long running DB operation (like 5 minute long SQL query on a batch of elements), then you can go with spinning up a custom thread that will trigger the heartbeat.

> Again, thank you for your time. I just want to make sure I understand how Karafka works internally to make sure I have a good understanding what triggered those problems so that we can avoid it in the future by providing better guidelines to our developers.

Thank you for being patient :) and please don't be angry on some of my mistakes in regard to giving you an exact explanation. I deal now with 2 versions of both Karafka and WaterDrop backed up by a completely different Kafka driver and quite often what is true for `1.x` is not for `2.x`. Even I get confused sometimes.

**Comment by paneq** [comment]
> Thank you for being patient :) and please don't be angry on some of my mistakes in regard to giving you an exact explanation. I deal now with 2 versions of both Karafka and WaterDrop backed up by a completely different Kafka driver and quite often what is true for 1.x is not for 2.x. Even I get confused sometimes.

Don't worry. I know exactly what it is like to live in the present and future at the same time.

Thank you.

**Comment by mensfeld** [comment]
Thank you! I will move parts of this discussion into the wiki pages for future references.
