### ISSUE TITLE
Cannot only define seed brokers in consumer groups

### ISSUE THREAD

**Issue by matthewtoschi** [karafka/karafka#582]
I'm trying to configure seed brokers on consumer_groups rather than in the application's setup. As I understand, this is the suggested approach for connecting to multiple kafka clusters for different topics. But leaving it out of the root setup sets the default value of 127.0.0.1.

I assume that one solution is to take one of my seed brokers and just place it in the app setup but I'm wondering if that's necessary and intended. Alternatively, is the intention that consumer group seed brokers are subgroups and I should put all of my seed brokers in the app setup?

--------

## Expected behavior

Seed brokers are not required to be configured at the root level. If all consumer groups configure their own seed brokers, karafka connects to and subscribes from the clusters without issue.

## Actual behavior

Karafka always attempts to connect to the default seed broker, 127.0.0.1, if none are set in the App setup.

## Steps to reproduce the problem

Using example_app, I reconfigured karafka with seed brokers at the consumer_group level. No connection attempt is made for these hosts. Instead there is an error trying to connection to the default seed broker since none are defined in the App setup.
`ERROR -- : Failed to fetch metadata from kafka://127.0.0.1:9092: Connection refused - connect(2) for 127.0.0.1:9092`

```
diff --git a/karafka.rb b/karafka.rb
index fc8d05f..92840bf 100644
--- a/karafka.rb
+++ b/karafka.rb
@@ -30,9 +30,6 @@ APP_LOADER.eager_load
 #   a structure similar to rails config/routes.rb, etc.
 class App < Karafka::App
   setup do |config|
-    # Karafka will auto-discover kafka_hosts based on Zookeeper but we need it 
-    # to run tests without running kafka and zookeeper
-    config.kafka.seed_brokers = [ENV['KAFKA_HOST'] || 'kafka://127.0.0.1:9092']
     config.client_id = 'example_app'
   end
 
@@ -62,6 +59,7 @@ Karafka.monitor.subscribe(Karafka::Instrumentation::ProctitleL
 App.consumer_groups.draw do
   consumer_group :batched_group do
     batch_fetching true
+    seed_brokers = %w( kafka://myhost.com )
 
     topic :xml_data do
       consumer XmlMessagesConsumer
@@ -84,6 +82,8 @@ App.consumer_groups.draw do
   # @note The backend is totally optional, if you disable it, the game will
   # work as well
   consumer_group :async_pong do
+    seed_brokers = %w( kafka://myotherhost.com )
+
     topic :ping do
       consumer Pong::PingConsumer
       backend :sidekiq
```

## Your setup details

Karafka version: 1.3.5
Ruby version: 2.7.1
Ruby-kafka version: 1.0.0
Application client id: example_app
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /Users/toscm004/Desktop/example-app/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://127.0.0.1:9092"]

**Comment by mensfeld** [comment]
Looks like a bug.

**Comment by mensfeld** [comment]
@matthewtoschi I can confirm. It is a bug. Working on a fix...

**Comment by mensfeld** [comment]
@matthewtoschi it is not a bug. You assign settings to a local variable instead of setting seed brokers on a customer group level. You

```ruby
seed_brokers = %w( kafka://myotherhost.com )
```

correct:

```ruby
seed_brokers %w( kafka://myotherhost.com )
```

**Comment by mensfeld** [comment]
@matthewtoschi I'm sorry for the previous noise in this thread. You did provide invalid example (local variable assignment) BUT there was a problem indeed. It's already fixed in master. Would you mind checking it out? If it will work (should, tested) I will craft a release.

**Comment by matthewtoschi** [comment]
@mensfeld  can confirm it's working for me. Thank you much

**Comment by mensfeld** [comment]
Great. I will make a 1.3 release today.

**Comment by mensfeld** [comment]
@matthewtoschi released. Have a great weekend!
