### ISSUE TITLE
Use Karafka.logger for CLI messages

### ISSUE THREAD

**Issue by prikha** [karafka/karafka#583]
## Is your feature request related to a problem? Please describe.

Hi there! I have `karafka` service equipped with a JSON logger. Log events are pipelined to the Elastic cluster. Everything is fine, but the boot message is not formatted. Which makes me lose the restart message.

## Describe the solution you'd like

Boot message for example comes from here:

```rb
# /lib/karafka/cli/info.rb
...
puts(info.join("\n"))
```

What if we change it to use the logger?

```rb
# /lib/karafka/cli/info.rb
...
Karafka.logger(info.join("\n"))
```

So I consider swapping all `puts` with `Karafka.logger.info`

## Alternative solution

- Monkey-patching will solve it ad-hoc but I wish I could avoid it.
- We can have a separate logger instance for CLI

It's a small change that'd make the output format consistent. WDYT?

**Comment by mensfeld** [comment]
> It's a small change that'd make the output format consistent. WDYT?

Great idea and good catch. Are you willing to make the change and add the CLI logger or do you want me to do it?

**Comment by prikha** [comment]
I have opened a PR to use `Karafka.logger` because it was partly used there already. 

As for me having a CLI logger is an overkill. But if you feel like we can benefit from a separate logger for that - I can update the PR.

**Comment by mensfeld** [comment]
@prikha no need. I'll apply small styling updates and merge it after the weekend! Thank you!

**Comment by prikha** [comment]
🙇 👍
