### ISSUE TITLE
Deserialise the message are now wrapped with `payload` key

### ISSUE THREAD

**Issue by luizkowalski** [karafka/karafka#589]
Hi

At my company, we use Karafka and (de)serialize messages with Avro, using a set of schemas. Everything was working fine until we updated from karafka **1.2.10** to **1.3.6** because apparently, [this](https://github.com/karafka/karafka/pull/534/files#diff-9f24d93e5e317c44321b03a36f97bde4R51) changed how the messages are deserialized. If I understand it correctly, now messages are deserialized without being unwrapped.

This was our code for consuming and deserialize messages on 1.2.10:

```ruby
Karafka::Parsers::Avro.schemas_path = File.join(Rails.root, 'fixtures/avro_schemas')
default_parser = Karafka::Parsers::Avro.from_path(nil, codec: 'deflate')

  consumer_groups.draw do
    consumer_group :payments do
      topic :topic do
        consumer ConsumerClass
        parser default_parser
      end
    end
```

and this is our code with Karafka 1.3.6

```ruby
class AvroDeserializer
    attr_reader :avro

    def initialize(params)
      @avro = AvroTurf.new(params)
    end

    def call(message)
      avro.decode(message.payload)
    end
  end

default_deserializer = AvroDeserializer.new(schemas_path: File.join(Rails.root, 'fixtures/avro_schemas'), codec: 'deflate')

  consumer_groups.draw do
    consumer_group :payments do
      topic :topic do
        consumer ConsumerClass
        parser default_parser
      end
    end
```

Since then, we noticed that inside the consumer, the message is now wrapped with `payload`, like this:

```ruby
payload: {
 user_id: 123
}
```

A quick fix was changing the consumer from this:

```ruby
def message
  @message ||= params.deep_symbolize_keys
end
```

to this

```ruby
def message
  @message ||= params['payload'].deep_symbolize_keys
end
```

We also noticed that there are no issues opened related to this change so we were like "are we the only ones with this problem?"  but looking at the [commit](https://github.com/karafka/karafka/pull/534/files#diff-12d069f25e48d0273c670cbf1576f5acR20) if people are using the default JSON deserializer, they shouldn't have any issues so this raised a question on our team: are we using Karafka/Avro correctly? Is our (de)sereliazation broken? should we handle `payload` unwrapping on a lower level (not in the consumer, but on `karafka.rb` config file)?

```
[2020-06-18T10:59:29] INFO  Rails : Karafka version: 1.3.6
Ruby version: 2.7.1
Ruby-kafka version: 1.0.0
Application client id: finiata
Backend: inline
Batch fetching: false
Batch consuming: false
Boot file: /Users/luiz/rails_dev/finiata-core-mvp-2/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://localhost:9092"]
```

**Comment by mensfeld** [comment]
Hey @luizkowalski. First of all thanks for using Karafka! I hope, that beyond this issue other things operate smoothly on your side. Sorry for the inconvenience that occurred with this change.

We are using AVRO with Karafka all the time ;) so it's not just you.

Your solution is not a quick fix but a proper upgrade.

This was a breaking change, that was indicated here: https://mensfeld.pl/2019/09/karafka-framework-1-3-0-release-notes-ruby-kafka/#message-payload-now-available-under-the-8216payload8217-key-without-root-merge

Here's the justification of this change: https://github.com/karafka/karafka/issues/299

I hope that clarifies things for you. If not, please ask :)

**Comment by luizkowalski** [comment]
>  I hope, that beyond this issue other things operate smoothly on your side. Sorry for the inconvenience that occurred with this change.

It does 😄

I'm glad to know that this was documented and we just missed it, thanks for pointing it out.

One last question before closing this. I want to come back to the point I made: instead of "_should_ we handle payload unwrapping on a lower level" I want to ask "**can we** handle the payload unwrapping on a lower level?" We had to update our consumer's specs by wrapping the event with `payload`. While this is not a big of a deal to do it thanks to text editors and search functions, if we could just make `params` on the consumer get the message unwrapped already would be nice because I'm pretty sure I will forget to make the spec right on a next time and we wouldn't need to update multiple files (consumers and specs), just one.

was thinking about something like 

```
class AvroDeserializer
 def call(message)
   avro.decode(message.payload)['payload']
 end
end
```

on the `AvroDeserializer` class or is there a more elegant solution? I'm not very familiar with Karafka/Avro because once a team member set up a long time ago we pretty much didn't update as it was always running smoothly

**Comment by mensfeld** [comment]
@luizkowalski if you are using rspec - this would be handled by: https://github.com/karafka/testing
and it would raise an error on your side. You can use this code as an example for other test frameworks on how to design karafka functional tests.

> can we handle the payload unwrapping on a lower level?

You would have to monkey-patch this: https://github.com/karafka/karafka/blob/master/lib/karafka/params/params.rb#L51

**Comment by luizkowalski** [comment]
I'm gonna have a look at `testing` gem and drop the manual labor we are doing with testing as much as possible.

About the monkey-patch, I rather not do it, so I'm gonna leave as I implemented then.

Well, thanks a lot for your input, it was really helpful!
