### ISSUE TITLE
Support for zookeeper chroot

### ISSUE THREAD

**Issue by sokratisg** [karafka/karafka#59]
Hello,

Does consumer support chroot for zookeeper connections?
I am asking because on a multi-environment setup and each Kafka broker should running under a different "/<chroot>" node when all Kafka clusters are using the same Zookeeper cluster.

I've tried adding the chroot in config.zookeeper_hosts array but Karafka seems to ignore the setting.
`config.zookeeper_hosts =  %w( 10.0.0.1:2181/kafka_prd 10.0.0.2:2181/kafka_prd 10.0.0.3:2181/kafka_prd  )`

Thank you.

**Comment by mensfeld** [comment]
True - will fix that soon

**Comment by mensfeld** [comment]
@sokratisg  could you try to specify the chroot only for the last connection:

```
config.zookeeper_hosts = %w( 10.0.0.1:2181 10.0.0.2:2181 10.0.0.3:2181/kafka_prd )
```

and check if it will help

**Comment by mensfeld** [comment]
@sokratisg it works with format as above (at least for me). Closing this issue since no reply. Please reopen if it still occurs an provide more details.
