### ISSUE TITLE
Instrumentation code placement wiki correction

### ISSUE THREAD

**Issue by afhammad** [karafka/karafka#593]
> The best place to hook up your listener is in the karafka.rb file, right after the App.boot!. This will guarantee, that your custom listener will be already loaded into memory and visible for Karafka framework.
-- https://github.com/karafka/karafka/wiki/Events-monitoring-and-logging#subscribing-to-the-instrumentation-events

Shouldn't "right **after** the App.boot!" be "right **before** the App.boot!"?

**Comment by mensfeld** [comment]
Actually for majority of cases it will work both ways. The reason why I recommend the after instead of before is due to the fact that booting sets up certain external components and components from optional plugins. That way, I can be sure everything is loaded and initialized correctly.

**Comment by afhammad** [comment]
I see, the context helps, otherwise it’s counter-intuitive. Thanks for clarifying!

**Comment by mensfeld** [comment]
@afhammad anytime :) sorry for the inconvenience. I'll update the doc with this justification.
