### ISSUE TITLE
Message deserialization: should we allow/simplify metadata access without a deserialization attempt?

### ISSUE THREAD

**Issue by rabotyaga** [karafka/karafka#598]
It is impossible to fetch message metadata (headers, topic, partition, offset) without a deserialization attempt for non-batch consumers using the `params` method.
- for non batch consumers `params` is `params_batch.first`: https://github.com/karafka/karafka/blob/03cc0134ae/lib/karafka/consumers/single_params.rb#L11
- `ParamsBatch#first` calls `deserialize!`: https://github.com/karafka/karafka/blob/03cc0134ae/lib/karafka/params/params_batch.rb#L42
- after deserialization error payload left intact and the message is marked as deserialized: https://github.com/karafka/karafka/blob/03cc0134ae/lib/karafka/params/params.rb#L47

This leads to a probably inconsistent behavior: in case the message could not be properly deserialized, we receive `Karafka::Errors::DeserializationError` on the first attempt to access metadata (all subsequent attempts will finish successfully). Inconsistency is in fact that we tried to access metadata only.

We can work around this by using `params_batch.to_a.first` instead of `params`, then deserialization attempt would be skipped and we would be able to access message metadata.

But wouldn't it be more consistent to allow metadata access without a deserialization attempt?
Consumers could be interested in ability to save/track malformed messages.

--------

## Expected behavior

Probably we should make a deserialization attempt on payload access.

## Actual behavior

Deserialization attempt is made on metadata access.

## Steps to reproduce the problem

- Setup a simple karafka app with an inline consumer
- Insert `binding.pry` into Consumer's `consume` method
- Send `test` (without quotes) using the `kafka-console-producer`
- try to call `params.headers` / `params.topic` / `params.partition` / `params.offset` - you will get `Karafka::Errors::DeserializationError` on the first attempt
  - after each attempt press ^D to continue the consumer loop and reset message deserialization state
- try to call any of the methods above for the `params_batch.to_a.first` - you will be able to use metadata without raising `Karafka::Errors::DeserializationError`

## Your setup details

```
$ [bundle exec] karafka info
Karafka version: 1.3.6
Ruby version: 2.6.5
Ruby-kafka version: 1.1.0
Application client id: platform
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /lib/platform_karafka.rb
Environment: development
Kafka seed brokers: ["kafka://localhost:9092"]
```

**Comment by mensfeld** [comment]
Great report! We will fix that in the upcoming week. Thank you!

**Comment by paneq** [comment]
I believe lazy deserialization would be nice. Something along the lines of:

```
module Karafka
  module Consumers
    module SingleParams
      def params
        params_batch.to_a.first
      end
    end
  end

  module Params
    class Params < Hash
      def payload
        deserialize!
        self['payload']
      end
    end
  end
end
```

**Comment by mensfeld** [comment]
@paneq yes. @rabotyaga did a PR for that. Great work :)
