### ISSUE TITLE
`MultiJson.load` does not accept `nil` as a param compared to JSON ruby library

### ISSUE THREAD

**Issue by chaadow** [karafka/karafka#605]
@mensfeld I'm using MultiJson `1.15.0` along with `json` gem version `2.3.1` I believe these are the latest versions

But I believe this is not an adapter issue. from my screenshot above i went to inspect the line in the multijson gem:

https://github.com/intridea/multi_json/blob/master/lib/multi_json/adapter.rb#L20

and they raise an error if the string is blank, which is the case when you pass `nil` however if you deserialize directly with the JSON library there is no error

_Originally posted by @chaadow in https://github.com/karafka/karafka/pull/599#issuecomment-678687284_

**Comment by mensfeld** [comment]
I think that the inconsistency comes from the RFC update.

This bug actually aligns with my desire to remove multi-json as a "not needed" dependency, thus nice timing :)

ref: https://tools.ietf.org/html/rfc7159

Also: https://github.com/intridea/multi_json/pull/152

I will be removing MultiJson and anyone that needs it can easily add it by using custom serializer :) this should:

1. fix the inconsistency
2. fix your bug
3. remove the additional dependency

**Comment by mensfeld** [comment]
@chaadow as a temp bypass just use a custom serializer that references JSON directly.

**Comment by mensfeld** [comment]
@chaadow could you test it? https://github.com/karafka/karafka/pull/606

**Comment by mensfeld** [comment]
fixed here: https://github.com/karafka/karafka/pull/606

**Comment by chaadow** [comment]
> @chaadow could you test it? #606

Added my review in #606
