### ISSUE TITLE
PG::UnableToSend bug 

### ISSUE THREAD

**Issue by ksimmi** [karafka/karafka#617]
Hi there! 

I'm using karafka (v 1.3.6) about 4 months and today I got a problem with database connection **`PG::UnableToSend: SSL SYSCALL error: EOF detected`**. I can't reproduce this exception locally but I got it twice on my GCP host in different services in different time.

> PG::UnableToSend: SSL SYSCALL error: EOF detected
> SELECT  "connectors".* FROM "connectors" WHERE "connectors"."name" = 'ePay2' LIMIT 1 (ActiveRecord::StatementInvalid)

When I started using karafka different types of **`ActiveRecord::StatementInvalid`** was raising very often. But I found solution in [this](https://github.com/karafka/karafka/wiki/Problems-and-Troubleshooting#why-karafka-does-not-restart-dead-pg-connections.) article.

After advises from the article I thought that my services became stable because I had not problems about two months. 

Please help me to fix this bug. 

--------

## Expected behavior

I expected successful DB reconnection behavior.

## Actual behavior

raising an Exception `ActiveRecord::StatementInvalid` with message `PG::UnableToSend: SSL SYSCALL error: EOF detected`.
![image](https://user-images.githubusercontent.com/46914258/95206212-3bbdff00-0808-11eb-9c68-c05db9b3cef8.png)

## Steps to reproduce the problem

I did not succeed to reproduce the bug on dev environment.

## Your setup details

Problem on GCP host and I have no permissions to get configuration. 
```
Karafka version: 1.3.6
Ruby version: 2.7.0
Ruby-kafka version: 0.7.8
Application client id: karafka-local
Backend: inline
Batch fetching: false
Batch consuming: ?(default)
Environment: production

```

**Comment by mensfeld** [comment]
Hello @ksimmi. Thank you for taking interest in Karafka.

It does not look like a problem with Karafka itself but rather an underlying issue with your PG setup. 

This error is caused by your PG adapter trying to use a stale/dead connection from the ActiveRecord connection pool. There are two ways to address this issue:

- Size your connection pool to match the number of threads/process
- Lower connection reaping frequency (Reaper checks pool for dead connections, every N secs)

My guess here is, that you use Karafka with Rails and a setup with a lot of connections (big connection pool) and some of the connections that are being used are no longer valid but not yet ripped.

**Comment by ksimmi** [comment]
Hello @mensfeld. Thank you for your response.

> My guess here is, that you use Karafka with Rails

No, my app is pure karafka-app, I'm not using Rails.

> This error is caused by your PG adapter trying to use a stale/dead connection from the ActiveRecord connection pool. There are two ways to address this issue:
> 
>     Size your connection pool to match the number of threads/process
>     Lower connection reaping frequency (Reaper checks pool for dead connections, every N secs)

I understood that problem with number of my connection pool. But I don't understood how to configure correct connection pool. I read that connection pool number must be the same as threads number but I have problems with counting threads for my karafka apps. I read an article about [concurrency](https://github.com/karafka/karafka/wiki/Concurrency) but it steel difficult t understand because of my English level. The main misunderstanding is on consumer groups and topic. Should I calculate consumer groups or topics to calculate correct threads number?

Now I have sixteen karafka apps, each with different count of consumers. For example, one of my apps:

```
KafkaApp.consumer_groups.draw do

  consumer_group :contracts do
    topic :'finance.transactions.contract_identified' do
      consumer KafkaConsumers::ContractIdentified
    end

    topic :'finance.transactions.warm_up' do
      consumer KafkaConsumers::ContractWarmUp
    end
  end

  consumer_group :confirming_ops_cards do
    topic :'finance.transactions.acquiring_form_credentials_getted' do
      consumer KafkaConsumers::HandleAcquiringFormCredentials
    end

    topic :'finance.transactions.acquiring_new_card_authorized' do
      consumer KafkaConsumers::ContractDocumentCreatedByCards
    end

    topic :'finance.transactions.acquiring_new_card_confirmed' do
      consumer KafkaConsumers::ContractDocumentExecutedByCards
    end
  end

  consumer_group :confirming_ops_finsrv do
    topic :'finance.transactions.fin_service_payment_authorized' do
      consumer KafkaConsumers::ContractDocumentCreatedByServices
    end
  end

  consumer_group :confirming_ops_bank_credits do
    topic :'finance.bank_credits.status_changed' do
      consumer KafkaConsumers::BankCreditStatusChanged
    end
  end

  consumer_group :contract_documents do
    topic :'finance.bank_credits.document_created' do
      consumer KafkaConsumers::ContractDocumentCreatedByBankCredit
    end

    topic :'finance.transactions.bonuses_regulated' do
      consumer KafkaConsumers::BonusesRegulated
    end

    topic :'finance.transactions.bank_credit_decision' do
      consumer KafkaConsumers::BankCreditDecision
    end
  end
end
```

Is the threads count is 5 for this code because of 5 consumer_group? 
 
P.S. Also, could you give me some info why and when I should use separate consumer group? I suspect I am doing it wrong.

**Comment by mensfeld** [comment]
> Is the threads count is 5 for this code because of 5 consumer_group?

Yes. It's goin to change drastically in 2.0 but atm: https://github.com/karafka/karafka/blob/master/lib/karafka/fetcher.rb#L37 this corresponds to amount of threads.

> P.S. Also, could you give me some info why and when I should use separate consumer group? I suspect I am doing it wrong.

In majority of cases you should not. A consumer group is a group of related consumers that perform a task (quote from kafka docs) - thus if you have a single application that is performing related work, you should not divide this. The setup you have will generate 5 group ids which might make it more problematic for refactoring and updating (although easier for scaling in some cases as well ;)). 

I like to use a simplified definition of a consumer group and just think of it as a single application within a domain / bounded context.

> I understood that problem with number of my connection pool. But I don't understood how to configure correct connection pool.

You did not tell me what your setting is.

> The main misunderstanding is on consumer groups and topic. Should I calculate consumer groups or topics to calculate correct threads number?

Consumer groups.

**Comment by ksimmi** [comment]
> I like to use a simplified definition of a consumer group and just think of it as a single application within a domain / bounded context.

Ok, I going to join my consumer groups into one. If I do this is the correct size of connection pool must be 1?

**Comment by mensfeld** [comment]
> Ok, I going to join my consumer groups into one. If I do this is the correct size of connection pool must be 1?

Yes.

**Comment by ksimmi** [comment]
Thank you, I going to try it!

**Comment by mensfeld** [comment]
@ksimmi ping me in case of any issues. Good luck!
