### ISSUE TITLE
Connection error IO::EINPROGRESSWaitWritable

### ISSUE THREAD

**Issue by yonyossef** [karafka/karafka#636]
Hello,
I have followed the articles trying to setup karafka_example in a wsl/ubuntu rails env.

Running the server by "bundle exec karafka server" result in a failure to fetch metadata due to Connection error IO::EINPROGRESSWaitWritable

My setup:

gem "waterdrop", '~> 1.4.0', git: "https://github.com/karafka/waterdrop.git", branch: "1.4"
gem "karafka", git: "https://github.com/karafka/karafka.git", branch: "master"

```
# karafka.rb

# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'development'
ENV['KARAFKA_ENV'] = ENV['RAILS_ENV']
require ::File.expand_path('../config/environment', __FILE__)
Rails.application.eager_load!

# This lines will make Karafka print to stdout like puma or unicorn
if Rails.env.development?
  Rails.logger.extend(
    ActiveSupport::Logger.broadcast(
      ActiveSupport::Logger.new($stdout)
    )
  )
end

class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka.seed_brokers = %w[kafka://127.0.0.1:9092]
    config.client_id = "karafka_example"
    config.backend = :inline
    config.batch_fetching = false
    # Uncomment this for Rails app integration
    # config.logger = Rails.logger
  end

  # Comment out this part if you are not using instrumentation and/or you are not
  # interested in logging events for certain environments. Since instrumentation
  # notifications add extra boilerplate if you want to achieve max performance,
  # listen to only what you really need for a given environment.
  # Karafka.monitor.subscribe(Karafka::Instrumentation::StdoutListener)
  # Karafka.monitor.subscribe(Karafka::Instrumentation::ProctitleListener)

  consumer_groups.draw do
    consumer_group :example do
      batch_fetching false

      topic :users do
        consumer UsersConsumer
      end
    end
  end
end

Karafka.monitor.subscribe('app.initialized') do
  # Put here all the things you want to do after the Karafka framework
  # initialization
end

KarafkaApp.boot!
```

My classes:

```
class UsersConsumer < ApplicationConsumer
    def consume
        Karafka.logger.info "New [User] event: #{params}"
    end
end

class UsersResponder < ApplicationResponder
  # This method needs to be implemented in each of the responders
  topic :users

  def respond(event_payload)
    respond_to :users, event_payload
  end
end
```

Example:

**yonyossef@DEVPC:~/karafka_example$ bundle exec karafka server**
I, [2020-12-22T10:17:46.143494 #1743]  INFO -- : Karafka version: 1.4.1
Ruby version: 2.7.2
Ruby-kafka version: 1.3.0
Application client id: karafka_example
Backend: inline
Batch fetching: false
Batch consuming: false
Boot file: /home/yonyossef/karafka_example/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://127.0.0.1:9092"]
I, [2020-12-22T10:17:46.145822 #1743]  INFO -- : New topics added to target list: users
I, [2020-12-22T10:17:46.145906 #1743]  INFO -- : Fetching cluster metadata from kafka://127.0.0.1:9092
E, [2020-12-22T10:17:46.146820 #1743] ERROR -- : Failed to fetch metadata from kafka://127.0.0.1:9092: Connection error IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block

Please advise

**Comment by mensfeld** [comment]
Hello @yonyossef. First of all, thank you for trying out Karafka, and really sorry you're experiencing issues. It seems like something is off with your Kafka setup and we're unable to connect to it or maybe UWF is blocking the traffic (wild guess). It would be beneficial if you could provide a reproduction docker container, otherwise, it may be really hard to assess your setup.  

Also: what Kafka version are you using?
Sidenote: please use the rubygems versions, not the github master as github master sometimes (not often but it happens) may contain work that is not yet stable.

**Comment by yonyossef** [comment]
Hi @mensfeld , thank you for the quick response.

UMF is off on my Windows system.
About kafka version, do you mean this? > Ruby-kafka version: 1.3.0
Moved to rubygems versions, didn't solve the issue.

I'd love to learn how to provide a reproducion container, can you please link me to the right flow for doing that?

Thanks

**Comment by mensfeld** [comment]
Hmm. So you are running Windows (I actually meant UFW - the Ubuntu firewall ;) ).

I asked about Kafka, not Ruby-Kafka: https://dzone.com/articles/running-apache-kafka-on-windows-os

Based on your description, it seems you have some sort of connection issue between Karafka and Kafka. It's like having an issue between Rails and PostgreSQL. Unfortunately, I cannot give you strong advice as I do not own Windows and I do not even know if things will work there.

I would suggest switching to Docker: https://docs.docker.com/docker-for-windows/ and then actually running it under Linux. You are the first person to actually run it on Windows as far as I know, so once again really sorry for not being able to help you too much :(

**Comment by yonyossef** [comment]
Silly me, I had no kafka installed.

Followed this tutorial and everything works fine now:

https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-linux-wsl-2/#enable-windows-subsystem
