### ISSUE TITLE
Example of NewRelic monitor is outdated

### ISSUE THREAD

**Issue by 90yukke** [karafka/karafka#65]
NewRelic monitor have stopped to work after recent update of karafka.

**Comment by mensfeld** [comment]
That is true and it is because of the change what and when is logged in the Karafka logging engine (monitoring). Work in progress

**Comment by mensfeld** [comment]
@90yukke could you verify that it works?

**Comment by mensfeld** [comment]
@agwozdowski @pavlo-vavruk once you've merged #70 please close this issue

**Comment by mensfeld** [comment]
I'll close it since it works when I've tested it. If you'll have any issues with this, I will reopen and we can continue investigating.
