### ISSUE TITLE
"Mysql2::Error: MySQL client is not connected" after a running a while

### ISSUE THREAD

**Issue by vrodokanakis** [karafka/karafka#653]
Hi,

When running Karafka in production is seems that after a while I get the following error: 

`E, [2021-02-26T15:36:02.986305 #23993] ERROR -- : [[project_production] {pings: 0; requests: 0; topic 0, 2, 1}:] Exception raised when processing topic/1 in offset range 1943644..1947142 -- Mysql2::Error: MySQL client is not connected`

The issue of course is resolved by restarting Karafka server.

Is this something that can be resolved in another way? Right now Karafka doesn't use Rails active record connection pool to try and initialize a new MySQL connection? I am a bit puzzled.

Right now we keep restarting Karafka once per day to avoid this issue, but it seems to be a hack and not the proper way. 

Thanks

**Comment by mensfeld** [comment]
This? https://github.com/karafka/karafka/wiki/Problems-and-Troubleshooting#why-karafka-does-not-restart-dead-pg-connections

**Comment by vrodokanakis** [comment]
Ah sorry, my bad. I don't know why I didn't see this. 

We will implement a similar strategy for MySQL.

**Comment by mensfeld** [comment]
@vrodokanakis no probem, you are welcome and ping me in case of any problems. Have a great weekend!
