### ISSUE TITLE
Error when run karafka 1.4.2 with ruby 3.0.0

### ISSUE THREAD

**Issue by nvtanh** [karafka/karafka#665]
## Expected behavior

Karafka server is running correctly

## Actual behavior
I had an issue when using: Karafka version: 1.4.2, Ruby version: 3.0.0, Ruby-kafka version: 1.3.0.
When I run karafka server with the command: `RAILS_ENV=development bundle exec karafka server`
then it raises errors like that

```ruby
E, [2021-03-22T16:32:23.063078 #17024] ERROR -- : Listener fetch loop error: wrong number of arguments (given 2, expected 0..1)
E, [2021-03-22T16:32:28.084744 #17024] ERROR -- : Listener fetch loop error: wrong number of arguments (given 2, expected 0..1)
```

I create a Github repo here to reproduce https://github.com/nvtanh/karafka_errors

## My setup details

```
Karafka version: 1.4.2
Ruby version: 3.0.0
Ruby-kafka version: 1.3.0
Application client id: test-karafka-errors
Backend: inline
Batch fetching: false
Batch consuming: false
Boot file: karafka_errors/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://localhost:9092"]
```

**Comment by mensfeld** [comment]
Ok, was able to reproduce. Looking into it...

**Comment by mensfeld** [comment]
@nvtanh would you mind testing against this branch please? https://github.com/karafka/karafka/pull/666 :pray:

**Comment by nvtanh** [comment]
@mensfeld It's working now. Thanks for your support

**Comment by mensfeld** [comment]
crafting the release now..

**Comment by mensfeld** [comment]
ref https://rubygems.org/gems/karafka/versions/1.4.3
ref https://my.diffend.io/gems/karafka/1.4.2/1.4.3
