### ISSUE TITLE
How to decrease latency between producer and consumer?

### ISSUE THREAD

**Issue by dexhacker** [karafka/karafka#675]
Hello, 

I'm using Karafka in my microservices. I have latency about 1s between consumers and producers and I want to decrease it to 0.1s. 1s latensy is problem for me because of total latency in operations that involves many chained services. Sometimes total latency could be greater than 15s. For example flow of payment for some partner_1 services by card of partner_2 acquiring:

1 Checking the possibility of payment by card
  transaction-srv -> cards-srv -> acquiring-srv -> transaction-srv
2 Checking the possibility of providing the service by the partner
  transaction-srv -> parners-srv -> partner-gw-srv -> transaction-srv
3 Charging money
  transaction-srv -> acquiring-srv -> transaction-srv 
4 Confirming order
  transaction-srv -> partner-gw-srv -> transaction-srv

In this case total time of transaction is 11s of which delay 10s. 

How to decrease latency? I tried to change max_wait_time to 0.1s but it still 1s latency. Also I tried to low heartbeat.
  
Thank you.

**Comment by mensfeld** [comment]
Your description indicates you're building some sort of a microservices-based transactional flow. Please keep in mind, that with a chain like this, debugging and testing may become hell.

Kafka is not supposed to be real-time processing engine but we can give it a shot :)

set `kafka.min_bytes` to 1
make `kafka.max_bytes_per_partition` to a smaller then default value
set `kafka.max_bytes` to smaller value
set `kafka.max_wait_time` to 0.1 again

Hearbeat has nothing to do with anything.

If you need real time (or semi-real time) you might be better moving to sync.

**Comment by mensfeld** [comment]
@dexhacker that's probably better. Even if you are able to achieve 500ms in the pipeline overall I don't see it being "real, real" realtime.
