### ISSUE TITLE
Ability to extend routing table

### ISSUE THREAD

**Issue by ojab** [karafka/karafka#677]
Right now we can map only [consumer group, topic] pair to specific consumer class and if, for example, topic contains different message types — we're ought to implement custom router inside the consumer, which is not ideal because abstractions are broken.
Would be awesome to replace
```ruby
class MyTopicConsumer
  def consume
    message_type :ping do
      message_version 1 do
        PingProcessor::V1.process(params)
      end 
      message_version 2 do
        PingProcessor::V2.process(params)
      end 
    end
  end
end
``` 
with
```ruby
consumer_groups.draw do
  consumer_group 'my_group' do
    topic 'my_topic' do 
      message_type :ping do
        message_version 1 do
          consumer PingConsumer::V1
        end
        message_version 2 do
          consumer PingConsumer::V2
        end
      end
    end
  end
end
```

## Describe the solution you'd like

Right now it's
```ruby
topic = Persistence::Topics.fetch(group_id, kafka_message.topic)
consumer = Persistence::Consumers.fetch(topic, kafka_message.partition)
``` 
in `{Message,Batch}Delegator`, which is IMHO a bit confusing since we have `Karafka::Routing::Router` that is described as `Karafka framework Router for routing incoming messages to proper consumers`.

Essentially it's multilevel hash with `routing_table[consumer_group_id][topic_name][partition] = Consumer.new`, would be good to merge `Karafka::Persistence` with `Karafka::Routing` and generalize it to some kind of middleware that just filters messages
```ruby
Router.register_middleware(:topic, TopicMiddleware)

class TopicMiddleware
  attr_accessor :consumer

  # filter is `my_topic` in case of `topic 'my_topic'` in routing table
  def initialize(filter)
    @filter = ->(kafka_message) { kafka_message.topic == filter }
  end

  def call(kafka_message)
    @filter.call(kafka_message)
  end
end
``` 
and router that tries to find middleware chain that matches the message and gets consumer from it.

It's a rough idea, but if it's more or less good idea and could be accepted — I can try to make it more real-life.

Unanswered questions:
1. How batch consuming should be handled
2. Should we provide a way to replace middlewares with monolithic router or performance reasons?
3. Should we get consumer from first successful middleware chain or more elaborate rules should be available?
4. …

## Describe alternatives you've considered

Consumer as a router? Monkeypatching karafka?

**Comment by mensfeld** [comment]
Thanks for opening this issue. I will get back to you tops in 2 days!

**Comment by mensfeld** [comment]
Ok, let me elaborate on this one:

> in {Message,Batch}Delegator, which is IMHO a bit confusing since we have Karafka::Routing::Router that is described as Karafka framework Router for routing incoming messages to proper consumers.

You are right. The delegator no longer exists in `2.0`. Not that it was confusing as the routing is supposed to reflect the abstract concept of routing, not the exact implementation, but it was just not needed ;) Anyhow, I see the point and how it can be confusing. Sorry for that.

At the moment, I'm not sure if I want to do this in Karafka. Here's the reasoning (though I am fully open for a debate on this one):

- Karafka 2.0 works async. With multiple threads at the moment but Ractors and separate forks. While this is not a blocker by itself, there is one Karafka feature that is going to improve the CPU utilization: delayed deserialization. With routing reaching out to anything except the headers, this will trigger the deserialization in the main thread/process, slowing down the whole process.
- Consumers while from the framework users' perspective are just an execution layer, actually do more than that (especially in 2.0 but in 1.4 as well). They are used to handle checkpointing when manual offset management is off, provide some kafka client methods access, provide callbacks that get triggered during the consumer lifecycle
- In Karafka 2.0 consumers (https://github.com/karafka/karafka/blob/ad2691ca9828dbb29f952d81137b63952d23a47f/lib/karafka/base_consumer.rb) will be doing even more as there more async things that need to be tracked.
- On top of all of that, there are recovery scenarios for network failures, rebalancing, being kicked off from consumer group that will make things super complex without a single point of execution where the control is passed to the user.

Would you mind providing me with some code samples of how your "internal" router resolves what is of what version?

**Comment by ojab** [comment]
>Would you mind providing me with some code samples of how your "internal" router resolves what is of what version?

In the code it looks approx. as the example in the first message, implementation approx. matches current `Karafka::Routing[::Builder]`, but during routing it handles payload instead of metadata. Payload is something like:
```json
{
  "message_type": "ping",
  "message_version": 1,
  "message_payload": {
    …
  }
}
```
and only `message_payload` is used during actual processing.

I'll check `2.0-wip` and get back to you about other points.

**Comment by mensfeld** [comment]
@ojab thank you. So you deserialize data. Please be mindful of the processing corner cases and warranties Karafka needs to provide when considering any type of solution like the one you've suggested.

**Comment by mensfeld** [comment]
@ojab if you don't mind I will close it.

**Comment by ojab** [comment]
Yep, was thinking about closing this due to lack of time :(
Will try to return with something useful whenever I get back to this.

**Comment by mensfeld** [comment]
@ojab no rush :) I still think it is conceptually a bad idea but I am **always** open to a discussion.
