### ISSUE TITLE
Code snippet to run embedded Karafka on our Puma for Rails

### ISSUE THREAD

**Issue by sandipsubedi** [karafka/karafka#684]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

I am looking for a code snippet to run embedded Karafka on our Puma for Rails.

## Additional context

https://gitter.im/karafka/karafka?at=6076b185b9e6de24d63460b2

**Comment by mensfeld** [comment]
ref: https://github.com/karafka/karafka/issues/648

It seems I need to come up with a general description on how to do it with 1.4. In 2.0 there will be API for that but for now we will have to do some magic ;)

**Comment by mensfeld** [comment]
Ok, lets give it a shot :)

**Comment by sandipsubedi** [comment]
Thank you so much @mensfeld  I will play with it today.

**Comment by mensfeld** [comment]
@sandipsubedi please keep me posted. I'm super interested to hear about it.

**Comment by sandipsubedi** [comment]
@mensfeld  I had to change couple of things for this to work:

1. change:
```
require Rails.root.join(Karafka.boot_file)
```
to
```
require_relative Rails.root.join(Karafka.boot_file)
```

And, add this on `config/application.rb`
```
    config.autoloader = :classic
```

But I am seeing this message even when it's turned off, do you know why it's create Karafka server when when BOOT_KARAFKA is false?

```
➜  rails-service git:(embedded-karafka) ✗ bin/rails db:migrate
I, [2021-05-27T07:33:57.521896 #51293]  INFO -- : Initializing Karafka server 51293

➜  rails-service git:(embedded-karafka) ✗ bin/rails db:migrate
I, [2021-05-27T07:34:46.776111 #51417]  INFO -- : Initializing Karafka server 51417

➜  rails-service git:(embedded-karafka) ✗ rails c
I, [2021-05-27T07:35:08.361335 #51454]  INFO -- : Initializing Karafka server 51454
Running via Spring preloader in process 51463
Loading development environment (Rails 6.1.3.1)

```

**Comment by mensfeld** [comment]
> do you know why it's creating Karafka server even when BOOT_KARAFKA is false?

Because the message should be "initializing Karafka framework" not karafka server. If you do not see consumption logs, it means Karafka booted but it is not listening or anything. It just loaded the framework components.

**Comment by sandipsubedi** [comment]
I see. I don't see any process running with that pid, so I think we should be fine. 

ohhh. I can just put that line inside the if statement, Something like this:

```rb
if ENV['BOOT_KARAFKA'] == 'true'
  require_relative Rails.root.join(Karafka.boot_file)

  Thread.new do
    Karafka::App.run!
    Karafka::App.config.internal.fetcher.call
  end

  at_exit do
    Karafka::Server.send(:stop_supervised)
  end
end
```

**Comment by mensfeld** [comment]
Yup :) this should also work. Awesome. Once you confirm that all operates as expected, I will expose this API officially in Karafka 2.0.

**Comment by sandipsubedi** [comment]
hmm.. it's interesting that the consumer doesn't consume any message with that change, even though the producer produced fine. But it works if I move it outside of if statement:

```
irb(main):009:0> WaterDrop::SyncProducer.call( {test: "hello"}.to_json, topic: "users" )
I, [2021-05-27T08:43:51.789726 #54052]  INFO -- : Sending 1 messages to localhost:9092 (node_id=1001)
W, [2021-05-27T08:43:51.798596 #54052]  WARN -- : Connection has been unused for too long, re-connecting...
=> nil
```

**Comment by mensfeld** [comment]
I have no idea why it is like this. Would you be willing to make me a rails-based dummy app reproduction? I could tune it and make it solid for everyone's similar usecases.

**Comment by mensfeld** [comment]
@sandipsubedi ping :)

**Comment by sandipsubedi** [comment]
I was sidetracked with something else, I will create that dummy app in a couple of days.

**Comment by mensfeld** [comment]
@sandipsubedi thank you. This will be of a great help to me.

**Comment by mensfeld** [comment]
@sandipsubedi closing for two reasons:
- I decided not to support this in 2.0. Maybe in 2.1
- Stale

**Comment by mensfeld** [comment]
@sandipsubedi the API you were looking for is ready: https://karafka.io/docs/Embedding/ it will be part of the upcoming 2.0.14 release
