### ISSUE TITLE
Wiki: Broken link: Rails integration page: karafka.rb example

### ISSUE THREAD

**Issue by Durev** [karafka/karafka#685]
Hi,

There is a broken link on the wiki page for [Integrating with Ruby on Rails and other frameworks](https://github.com/karafka/karafka/wiki/Integrating-with-Ruby-on-Rails-and-other-frameworks).
When following the link for a `karafka.rb` example file in the [first section](https://github.com/karafka/karafka/wiki/Integrating-with-Ruby-on-Rails-and-other-frameworks#integrating-with-ruby-on-rails), we get a not found page.

--------

## Expected behavior

Should point to an example of `karafka.rb` configuration file for a Rails app ([this one](https://github.com/karafka/example-app/blob/master/karafka.rb) for instance).

## Actual behavior

404

**Comment by mensfeld** [comment]
Fixed. Thanks!
