### ISSUE TITLE
Setting WaterDrop configuration explicitly 

### ISSUE THREAD

**Issue by deskcoder** [karafka/karafka#694]
## Expected behavior

I tried to adjust  `:max_queue_size` and `:max_buffer_size`  to publish messages in bigger batches to avoid being rate limited by confluent-cloud. It turned out this config is not part of https://github.com/karafka/karafka/blob/master/lib/karafka/setup/config.rb so I tried to set it using `Waterdrop.setup {}` like so

```ruby
# karafka.rb
WaterDrop.setup do |config|
  config.kafka.max_queue_size = 5000
  config.kafka.max_buffer_size = 5000
  config.kafka.seed_brokers = ["kafka://0.0.0.0:9042"]
end

class KarafkaApp < Karafka::App
  setup do |config|
    config.client_id = ENV.fetch('KARAFKA_CLIENT_ID') { 'foobar' }
    config.logger = Rails.logger
  end
  ...
end
```

I would expect that Karafka would automatically use values I set using `WaterDrop.setup { }`

## Actual behavior

after running `karafka s` this is the output I got

```
Karafka version: 1.4.1
Ruby version: 2.6.5
Ruby-kafka version: 1.3.0
Application client id: foobar
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /Users/lewy/code/foobar/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://0.0.0.0:9092"]
```

As you see `seed_broker` url is wrong so  I assume the whole config set using  `WaterDrop.setup` is not visible to Karafka. 

## Steps to reproduce the problem

```ruby
# karafka.rb
WaterDrop.setup do |config|
  config.kafka.max_queue_size = 5000
  config.kafka.max_buffer_size = 5000
  config.kafka.seed_brokers = ["kafka://0.0.0.0:9042"]
end

class KarafkaApp < Karafka::App
  setup do |config|
    config.client_id = ENV.fetch('KARAFKA_CLIENT_ID') { 'foobar' }
    config.logger = Rails.logger
  end
  ...
end
```

run `bundle exec karafka  s`

and check if the reported `seed brokers` is using port `9042`

## Your setup details

Please provide kafka version and the output of `karafka info` or `bundle exec karafka info` if using Bundler.

Here's an example:

```
Karafka version: 1.4.1
Ruby version: 2.6.5
Ruby-kafka version: 1.3.0
Application client id: foobar
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /Users/lewy/code/foobar/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://0.0.0.0:9092"]
```

**Comment by mensfeld** [comment]
Put the WaterDrop configuration after the `App.boot!` in the `karafka.rb` file. Then you will overwrite whatever you want :)

This is what I did and here are the results:
```
(byebug) WaterDrop.config.kafka.seed_brokers
["kafka://0.0.0.0:9042"]
(byebug) Karafka::App.config.kafka.seed_brokers
["kafka://127.0.0.1:9092"]
```

**Comment by deskcoder** [comment]
> Put the WaterDrop configuration after the App.boot! in the karafka.rb file. Then you will overwrite whatever you want :)

I tried it before but `Karafka` is still not using the config I set for WaterDrop (just turn on `bundle exec karafka s` and you will notice it's using `9092` port and not `9042`. Your output shows the same thing but maybe I should assign the same `seed_brokers` to both Karafka.setup and WaterDrop.setup?

**Comment by mensfeld** [comment]
> Your output shows the same thing 

My output shows, that both Karafka and WaterDrop are using different settings. I think it would be much easier if you would drop me a line at maciej@mensfeld.pl and we can pair program on that. 

The alternative to this would be a full repro case not code snippets.

**Comment by mensfeld** [comment]
Also:

> I tried it before but Karafka is still not using the config I set for WaterDrop

I really don't understand this sentence in the context of the report you've created. WaterDrop does not propagate back to Karafka. Karafka propagates to WateDrop.

On top of that I do not quite understand WDYM by "not using".

**Comment by deskcoder** [comment]
I checked it again and you are right. Calling `WaterDrop.setup {}` after `KarafkaApp.boot!` will correctly set all values and `Karafka` won't overwrite anything.  Thank you for your help 👍
