### ISSUE TITLE
Wiki: Broken link: Error handling and back off policy page: Monitoring link

### ISSUE THREAD

**Issue by Durev** [karafka/karafka#697]
Hi,

There is a broken link on the [Error handling and back off policy](https://github.com/karafka/karafka/wiki/Error-handling-and-back-off-policy) wiki page.

The "Monitoring and logging" link in the [Exponential back off section](https://github.com/karafka/karafka/wiki/Error-handling-and-back-off-policy#exponential-back-off) redirects to the wiki's homepage.

--------

## Expected behavior

Should point to this page: https://github.com/karafka/karafka/wiki/Events-monitoring-and-logging.

## Actual behavior

302 with flash notice message: "You do not have permission to update this wiki."

**Comment by mensfeld** [comment]
Fixed. :bowing_man:
