### ISSUE TITLE
Ruby 3.0 compatibility, Client#pause

### ISSUE THREAD

**Issue by MmKolodziej** [karafka/karafka#699]
There seems to be an issue between `ruby-kafka` and `karafka`, using latest released versions (using latest commits from master, the issue would still occur).

Running in 2.7.4 with `RUBYOPT='-W:deprecated'`
```
ruby-kafka-1.3.0/lib/kafka/consumer.rb:152: warning: The called method `pause' is defined here
karafka-1.4.5/lib/karafka/connection/client.rb:67: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Karafka is calling pause passing hash as the options: https://github.com/karafka/karafka/blob/master/lib/karafka/connection/client.rb#L67
while ruby-kafka expects keyword arguments: https://github.com/zendesk/ruby-kafka/blob/v1.3.0/lib/kafka/consumer.rb#L152

Sorry from taking your attention away from Karafka 2. :upside_down_face:

**Comment by mensfeld** [comment]
@MmKolodziej would you be willing to submit a fix?

> Sorry from taking your attention away from Karafka 2.

No worries. I still plan to support 1.4 to at least a year after 2.0 is released.
