### ISSUE TITLE
Drop `irb` dependency

### ISSUE THREAD

**Issue by vbyno** [karafka/karafka#759]
## Is your feature request related to a problem? Please describe.

`karafka` [depends on](https://github.com/karafka/karafka/blob/master/karafka.gemspec#L25) `irb` gem, which brings some unpleasant experiences in the latest versions (like slow auto-complete).

## Describe the solution you'd like

Would it be possible to drop `irb` dependency? Is there any functionality `irb` is crucial for?

**Comment by mensfeld** [comment]
It is dropped already in 2.0. In 1.4, if you submit a PR, it will be merged :) : https://github.com/karafka/karafka/pull/749

**Comment by vbyno** [comment]
Thanks, @mensfeld! It will be a good place to start contributing to `karafka`)

**Comment by mensfeld** [comment]
@vbyno awesome! Feel free to base your solution on the mentioned PR. If you would have any questions, don't hesitate to ping me here or via our slack channel: https://slack.karafka.io/
