### ISSUE TITLE
Consider using static memberships by default in Karafka 2.0

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#774]

**Comment by mensfeld** [comment]
ref https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html

**Comment by grace0925** [comment]
On this topic, does karafka 1.4 currently support static membership? I couldn't figure out how to set `group.instance.id` on consumers from the doc/wiki. Thanks!

**Comment by mensfeld** [comment]
@grace0925 no way. This feature is only supported in 2.0. 2.0 is stable, I just didn't release it yet because updating the wiki (I want to have it prior to the official release).

**Comment by mensfeld** [comment]
Closing as I do not plan to make it a default but will document it.

**Comment by mensfeld** [comment]
@grace0925 I added integration spec illustrating this case for 2.0: https://github.com/karafka/karafka/pull/831
