### ISSUE TITLE
No pause after the error when custom topic mapper defined

### ISSUE THREAD

**Issue by Michanio** [karafka/karafka#812]
Karafka uses the wrong topic name when trying to pause the topics partition in case of a consumer error.

--------

## Expected behavior

The affected partition should be blocked.
Message "with error" should be reprocessed after the defined timeout.

## Actual behavior

It tries to reprocess the message with error without any timeout between.

## Steps to reproduce the problem

- define custom topic mapper
- send the message that triggers the error

## Your setup details

[Example app
](https://github.com/karafka/example-apps/pull/153)

```
$ [bundle exec] karafka info
Karafka version: 1.3.0
Ruby version: 3.0.1
Ruby-kafka version: 1.4.0
Application client id: example_app
Backend: inline
Batch fetching: true
Batch consuming: false
Environment: development
Kafka seed brokers: ["kafka://127.0.0.1:9092"]
```

**Comment by mensfeld** [comment]
Closing. Justified here: https://github.com/karafka/example-apps/pull/153#issuecomment-1153001834=
