### ISSUE TITLE
karafka consumer did not consume message immediately, got several mins delay

### ISSUE THREAD

**Issue by kevinleeTCA** [karafka/karafka#92]
We tested it locally (start kafka/zookeeper locally) which works fine, it can immediate consume the data and pass to a sidekiq worker to perform.

But it will got the delay when running it on docker-cloud, where we build our kafka cluster in docker cloud as well. We are pretty sure that the kafka message is delivered correctly to kafka sever (no delay), which we verified in the docker container.
 

The following the karafka boot file

```
ENV['KARAFKA_ENV'] ||= ENV['RACK_ENV']

Bundler.require(:default, ENV['KARAFKA_ENV'])
Karafka::Loader.new.load(Karafka::App.root)

class App < Karafka::App
  setup do |config|
    config.zookeeper.hosts = ENV['ZOOKEEPER_HOSTS'].split(',')
    config.wait_timeout = 60 # 1 minute
    config.max_concurrency = 5
    config.name = ENV['CLIENT_ID']
    config.redis = {
        url: ENV['REDIS_URL']
    }
    routes.draw do
      topic :activities do
        controller ActivitiesController
      end
    end
  end
end
```

sidekiq.yml is as follows

```
:verbose: true
:concurrency: 10

:timeout: 8

production:
  :concurrency: 10
development:
  :concurrency: 1
test:
  :concurrency: 1`
```

the handler controller is
```
require 'services/activity'

class ActivitiesController < Karafka::BaseController

  def perform
    data = JSON.parse(self.to_h['content'])
    Services::Activity.create(data)
  end

  def after_failure
    puts "handling failure #{params}"
  end
end`
```

and both the `karafka sever` and `karafka work` are running in the docker-cloud, together with unicorn and nginx, it just takes like 10mins to consume and perform it in the controller.

**Comment by mensfeld** [comment]
Can you specify a) what is the delay time b) how do you measure the delay time from the karafka side?

**Comment by mensfeld** [comment]
Once you send the data, could you please try to run from your apps console a manual consumtion like that?
```ruby
 Karafka::Consumer.run
```

does it consume immediately or is there a delay as well?

**Comment by kevinleeTCA** [comment]
@mensfeld  thanks for ur reply. The delay that I mean is that the time difference between the kafka message was received in kafka server and the time that karafka consume it and assign a worker to perform it, we derived from the `created_at` that we probed in the code.

in the docker cloud we can see the sidekiq log saying like
```
 2016-08-31T06:21:37.065304474Z 2016-08-31T06:21:37.064Z 183 TID-e411k ActivitiesWorker JID-4febf07dc7adc7eec59fae10 INFO: start
2016-08-31T06:21:37.070451043Z 2016-08-31T06:21:37.070Z 183 TID-e411k ActivitiesWorker JID-4febf07dc7adc7eec59fae10 INFO: done: 0.005 sec
```
but it will takes 1-10 mins to see this in the console log.

But when we running it locally, it just immediate show up. Also locally we can see karafka sever running logs like
```
Karafka::Connection::Listener#block in fetch with {:topic=>"activities", :message_count=>0}
...
```
but we can not see these logs in docker-cloud remotely.
We checked the port and process that karafka sever is running correctly.

**Comment by mensfeld** [comment]
@kevinleeTCA  you're welcome. Please try the consumer run from the console. Can you also confirm, that the jobs aren't hanging in sidekiq waiting to be started?

**Comment by mensfeld** [comment]
@kevinleeTCA FYI I will be on a holiday for the next 2 weeks. @agwozdowski  and @pavlo-vavruk will do their best to help you out :)

**Comment by kevinleeTCA** [comment]
@mensfeld  sidekiq jobs works fine, there is no job waiting or stuck, once it was scheduled, it will be finished very quickly. I will try directly run consumer.run command

**Comment by kevinleeTCA** [comment]
@mensfeld thanks for ur reply, enjoy ur holiday.

We also tried `karafka consume` command, which is one-time consume process, it just timeout without consume anything.

We also find an interesting thing, if we set `config.wait_timeout=1`, which will kill and establish socket to kafka sever very frequently, the delay decreased to 5 sec (which is still not acceptable), all our docker containers are deployed in the same zone.

It seems that when the karafka consumer establish the socket and listen on it, it did not immediately consume the message or be trigger for some reason.

When we test locally, we only start one kafka sever and one zookeeper sever.

In our docker-cloud, we have 3 kafka severs running a in cluster and 3 zookeeper severs running in a cluster mode, they all works as expected with leadership and follower.

**Comment by nagliyvred** [comment]
What are the implications of setting `wait_timeout` to a really low value? What we are trying to achieve is to read a message from kafka as soon as it is available

**Comment by kevinleeTCA** [comment]
Also we found found that if we deploy kafka/zookeeper in a stand alone mode, which means 1 kafka sever controlled by one zookeeper sever, then karafka consumer seems working fine, it can consume message as soon as possbile. 
But it will got latency (1-10mins) to consume message when we scaling kafka/zookeeper to be 2 or 3.

Does consumer process related to the number of replication-factor or in sync brokers ?

**Comment by mensfeld** [comment]
@kevinleeTCA the consumer should autobalance. Do you set the config manually or do you use kafka cluster autodiscovery?

**Comment by kevinleeTCA** [comment]
@mensfeld We did not set any consumer side config of kafka, just use the default one.

**Comment by mensfeld** [comment]
@kevinleeTCA  is there an option that you will give ma access to a demo infrustructre under which karafka doesn't work? I'm back from my holidays so I can take care of that. Also - did you try to point kafka serves directly in the config file instead of relying on autodiscovery?

**Comment by mensfeld** [comment]
@kevinleeTCA pleaase try with the driver branch if it works (new kafka driver). Since no replies I will close for now

**Comment by kevinleeTCA** [comment]
@mensfeld  sorry for the delay relay. We actually try this locally(by either setting the kafka.hosts or not), it still got several minutes delay when consuming messages.
It only happens when we running kafka/zookeeper in a cluster mode.
I just set up 3 kafka sever running locally, with a single zookeeper sever, following (http://kafka.apache.org/documentation.html#quickstart)

the karafka set up is the same as the first message.

**Comment by kevinleeTCA** [comment]
Ok, now we will give it try on the new driver (branched) to see if it works

**Comment by mensfeld** [comment]
@kevinleeTCA this branch no longer supporst Ruby 2.2. Please switch to at least 2.3

**Comment by kevinleeTCA** [comment]
@mensfeld  I just upgrade the new version of karafka and playing around it with kafka cluster (built locally), it now works as expected, it seems the new version does not use `config.zookeeper.hosts` anymore, it directly link to kafka brokers by config `kafka.host`, also it did not use `wait_timeout` to config the socket pipe timeout.

From the running logs, It seems it just round robin all the brokers (send heartbeat request) to fetch the offset info, if lag, then just consume the message, am I understand correctly ?

**Comment by mensfeld** [comment]
@kevinleeTCA  that is great! :)

It does not use zookeeper at all. You can find the most impotant changes and examples here: http://mensfeld.pl/2016/09/karafka-ruby-kafka-framework-0-5-0-release-details/

and full changelog here: https://github.com/karafka/karafka/blob/master/CHANGELOG.md

New Karafka requires at least one (but the more the better) host based on which it will discover a whole cluster. 

And yes, is uses round for the assigments :)
