### ISSUE TITLE
karafka-2.0.0.rc3 uninitialized constant WaterDrop::Contractable (NameError)

### ISSUE THREAD

**Issue by Thurys** [karafka/karafka#929]
RC3 seems to use WaterDrop::Contractable which got deleted in Waterdrop 2.4.0.

Pinning Karafka to RC2 seems to work

```
Karafka version: 2.0.0.rc3
Ruby version: 2.7.5
Rdkafka version: 0.12.0
Subscription groups count: 1
Workers count: 5
Application client id: *****
Boot file: *****
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
rc4 is going to be released soon

**Comment by mensfeld** [comment]
ref https://github.com/karafka/karafka/pull/928

**Comment by mensfeld** [comment]
ref 2 https://github.com/karafka/karafka/pull/930

**Comment by mensfeld** [comment]
@Thurys can you try https://rubygems.org/gems/karafka/versions/2.0.0.rc4 ?

**Comment by Thurys** [comment]
@mensfeld I can confirm that RC4 is working like a charm. Thank you very much for your fast response! (Update fell right into our deployment)

**Comment by mensfeld** [comment]
@Thurys really sorry for the issues. I have a plan to work on a batch releasing system and will try to lock dependencies better in the future.
