### ISSUE TITLE
Karafka release on rubygems.org

### ISSUE THREAD

**Issue by gnilrets** [karafka/karafka#94]

**Comment by gnilrets** [comment]
I guess it is versioned, but I'm used to having versions marked on specific commits, instead of just pulling from the master.

**Comment by mensfeld** [comment]
@gnilrets haha I thought the samee yesterday ;) there is no reason to be honest. We just focused on development, adding stuff constantly without a release cycle. I will finish the 0.5.0 version in the few incoming days (it's in the driver branch now) and I will make sure to release it to rubygems.

The funny thing is that subparts of Karafka (like waterdrop and other gems) are on the RubyGems. I will close this issue once Karafka is released on rubygems.

**Comment by mensfeld** [comment]
Done: https://rubygems.org/gems/karafka
