### ISSUE TITLE
Karafka Web UI

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#952]
Similar to Resque and Sidekiq, we should (and can!) have a nice web UI.

**Comment by andey** [comment]
The screenshot is in the README. 

However it seems like its suppose to be released in thise milestone 2.1.0.

There doesn't seem to be a branch with that code to try.

It's confusing, that the README in master has a screenshot of the web ui, but there is no web ui to try?

**Comment by mensfeld** [comment]
Hey @andey 

Yeah indeed there's a bit of confusion here and I will do a cleanup tops next week.

- There will not be a 2.1 release mostly because web won't be released as an embedded component but a separate gem. The reason is, that it adds 3 new dependencies and make a decision to abstract it away.
- The Web UI is in a closed alpha now available for karafka slack users. It will be released once I have docs done.
- I added the photo to the readme because I was interested if anyone would actually request the UI or ask about it ;) Now I know!

**Comment by mensfeld** [comment]
Also @andey if you join our slack you will get the early access :) just DM me.

**Comment by mensfeld** [comment]
I cleared the invalid tags as well as cleaned the milestones. Added in-progress because this is what is happening. Alpha is tested + docs are being written.

**Comment by mensfeld** [comment]
Tadam https://karafka.io/docs/Web-UI-Getting-Started/

![web-ui](https://user-images.githubusercontent.com/392754/215793215-59a4f0d6-13c2-40a6-8011-5f65c8fccdcc.png)
