### ISSUE TITLE
Let a consumer read from a topic it isn't subscribed to 

### ISSUE THREAD

**Issue by andrew-speers** [karafka/karafka#973]
## Is your feature request related to a problem? Please describe.

I'm considering a kafka architecture for event deduplication like what is described here https://segment.com/blog/exactly-once-delivery/#:~:text=The%20dedupe%20%E2%80%9Cworker%E2%80%9D%20is%20a,to%20the%20Kafka%20output%20topic. and as a consequence would need to be able to have a single consumergroup be able to read from a topic that it is not subscribed to. The idea being that on failure & restart the consumergroup consuming the input topic would read the output topic to make sure it's synchronized with the log keeping track of what messages have been deduplicated. 

## Describe the solution you'd like

I'd like to be able to have a consumergroup read from a topic that it isn't subscribed to. 

## Describe alternatives you've considered

Using the underlying rdkafka to access the output topic.

**Comment by mensfeld** [comment]
Note to self: we can either expose routing that is not active `active false` that could be used to build a client to poll or we could use the KV approach I am working on for the web ui

**Comment by mensfeld** [comment]
I don't want to call it `virtual` because of `virtual partitions`, so need to come up with a name

**Comment by mensfeld** [comment]
Closing. There is an admin API that allows to do so.

**Comment by mensfeld** [comment]
https://karafka.io/docs/Administration-%28topics-management-and-cluster-info%29/#getting-messages-from-a-given-offset
