### ISSUE TITLE
Karafka.rb appears to be loaded by the railtie outside of `bundle exec karafka server`

### ISSUE THREAD

**Issue by tmtrademarked** [karafka/karafka#974]
With the new railtie for Karafka, it seems like the Karafka configuration and code is running in unexpected places. In Karafka 1.4.13, the `karafka.rb` file was never loaded when running something other than Karafka itself. (Ie, running `rails c` or `bundle exec gruf`) It seems like in Karafka 2.0, the railtie causes the `karafka.rb` file to be loaded in all of these scenarios. This feels like it is undesirable behavior?

In our particular case, this creates an initialization issue when attempting to run a Gruf server because the karafka initialization code is now being run in this process as well.

--------

## Expected behavior

Karafka configuration should only be run when we actually *run* Karafka (ie, `bundle exec karafka server`)

## Actual behavior

It seems that with the new railtie, our karafka.rb file is being run in more processes than previously. Running another process in our app (in our case, Gruf) seems to load the Karafka code unexpectedly.

## Steps to reproduce the problem

For us, this was as simple as starting our Gruf server. `bundle exec gruf` produces an error about unshifting elements of the environment: `/Users/tom.wilson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:588:in `unshift': can't modify frozen Array: `

You can similarly verify this by putting a `binding.pry` or a print statement in karafka.rb and running `rails c`

## Your setup details

This is on Rails 6.1.6 with Ruby 3.0.2. Attached is the Karafka information.

```
Karafka version: 2.0.3
Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]
Rdkafka version: 0.12.0
Subscription groups count: 1
Workers count: 5
Application client id: agora
Boot file: /Volumes/android/agora/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by tmtrademarked** [comment]
It sort of seems like [this](https://github.com/karafka/karafka/blob/master/lib/karafka/railtie.rb#L104) should be set to false unless running via `bundle exec karafka`, unless I'm missing some reason why booting Karafka is desirable in these processes.

**Comment by mensfeld** [comment]
Hello @tmtrademarked, while your error is not intended, the behavior is.

I am still to provide the upgrade path, so first and foremost, thank you for your eagerness and willingness to do it prior to the upgrade docs. I'm taking a short holiday to recover after the release and will follow up with the docs shortly after.

I should change the naming from `boot_file` to something else for sure, as it no longer reflects the nature of `karafka.rb` file. I will keep this in mind for 2.1 :pray: 

Before 2.0 Karafka indeed used `karafka.rb` to boot (start) the server and run consumption.

With Karafka 2.0 this is no longer true. This file is not used to boot karafka as booting happens here: https://github.com/karafka/karafka/blob/master/lib/karafka/cli/server.rb#L25

`karafka.rb` is now needed to be loaded both via Railtie or manually for other frameworks to configure the framework components that can be used outside of the consumption process (messages producer + other things I am working on at the moment).

Would you mind creating a reproduction for me about your error (can't modify)? I would be really grateful if you could use this example app to do so: https://github.com/karafka/example-apps/tree/master/v2.0-rails then I could look into this and fix it.

None of my integration specs that operate on Rails show this, nor the example apps or any of my apps.

**Comment by tmtrademarked** [comment]
Thanks for the detailed reply here @mensfeld ! This is very helpful to understand the intention, and that all makes a lot of sense. (And of course, thank you for all your work developing and maintaining this project!)

After some digging on our end, I'm becoming convinced this is a strange interplay between Gruf (a GRPC framework) and Karafka. I'll see if I can find a way to reproduce using the sample app, though, because it seems plausible that others may run into something similar here.

**Comment by tmtrademarked** [comment]
I was able to update the sample app by adding Gruf. (It won't *do* anything, but it does demonstrate this failure mode!)

You can see here (https://github.com/tmtrademarked/example-apps/tree/add_gruf) by going to the v2.0-rails project and running `bundle exec gruf`. This will produce something like the following error:
```
tom.wilson:v2.0-rails (add_gruf *)$ bundle exec gruf
bundler: failed to load command: gruf (/Users/tom.wilson/.rbenv/versions/3.1.2/bin/gruf)
/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/engine.rb:574:in `unshift': can't modify frozen Array: ["/Volumes/android/example-apps/v2.0-rails/app/consumers", "/Volumes/android/example-apps/v2.0-rails/app/controllers", "/Volumes/android/example-apps/v2.0-rails/app/helpers", "/Volumes/android/example-apps/v2.0-rails/app/jobs", "/Volumes/android/example-apps/v2.0-rails/app/models", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionmailbox-7.0.3.1/app/controllers", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionmailbox-7.0.3.1/app/jobs", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionmailbox-7.0.3.1/app/models", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activestorage-7.0.3.1/app/controllers", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activestorage-7.0.3.1/app/controllers/concerns", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activestorage-7.0.3.1/app/jobs", "/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activestorage-7.0.3.1/app/models", "/Volumes/android/example-apps/v2.0-rails/test/mailers/previews"] (FrozenError)
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/engine.rb:574:in `block in <class:Engine>'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `run'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
```

**Comment by mensfeld** [comment]
Thanks. I will take a look in the upcoming days and I am sure I will fix this :pray:

**Comment by mensfeld** [comment]
I can repro.

**Comment by mensfeld** [comment]
quick patch (please check if works) for now:

in your karafka.rb replace:

```ruby
  require ::File.expand_path('config/environment', __dir__)
```

with 

```ruby

if ENV.key?('KARAFKA_CLI')
  require ::File.expand_path('config/environment', __dir__)
end
```

**Comment by mensfeld** [comment]
this won't double load rails via karafka and gruf

**Comment by mensfeld** [comment]
Would you mind testing this branch: https://github.com/karafka/karafka/pull/981

use it and completely remove the

```ruby
 require ::File.expand_path('config/environment', __dir__)
```

from your `karafka.rb`

**Comment by tmtrademarked** [comment]
It looks like this works! I tested using this branch, and `bundle exec gruf` and `bundle exec karafka server` both appear to run with no issues. Thank you for taking a look at this and for the rapid turnaround here.

**Comment by mensfeld** [comment]
@tmtrademarked will merge and release in the upcoming days then :) thank you for testing :pray:

**Comment by mensfeld** [comment]
released:

https://my.diffend.io/gems/karafka/2.0.3/2.0.4
https://rubygems.org/gems/karafka/versions/2.0.4
