### ISSUE TITLE
Confluent parallel consumer comparison (similar project but in Java)

### ISSUE THREAD

**Issue by astubbs** [karafka/karafka#976]
Hi, in lack of the discussions page, I thought I'd post an issue here just to let people know about the https://github.com/confluentinc/parallel-consumer which is a Java project which has a lot of overlap with Karafka. A Python dev at Confluent just brought Karafka to my attention - very interesting project! 
I'm quite curious to see how they are similar and where there are differences. To start with specifically looking at offset management.
Also key extraction from message content has been something I'm looking at. 

Congratulations on the successful project!

**Comment by mensfeld** [comment]
Since we've connected on Slack, I will close this issue as it's not an... issue ;)
